INSERT INTO ReporteGeneral (ReporteId,TipoSituacionReportada,PersonasElementosInvolucrados,FrecuenciaRecurrenciaHecho,ObservacionesAdicionales)
VALUES
(9401,'Posible riesgo en área común',NULL,NULL,NULL),
(9402,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9403,'Posible riesgo en área común','Conductores y peatones','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9404,'Reportes recurrentes de disturbios nocturnos','Testigos en el lugar','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9405,'Venta ambulante en zona no permitida','Conductores y peatones','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9406,'Posible riesgo en área común',NULL,'Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9407,'Conflicto vial y obstrucción de circulación','Usuarios del transporte público',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9408,'Posible riesgo en área común','Personal de un establecimiento','Ocasional',NULL),
(9409,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9410,'Problema de convivencia vecinal','Usuarios del transporte público','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9411,'Ruido excesivo en la vía pública',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9412,'Posible riesgo en área común','Usuarios del transporte público','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9413,'Posible riesgo en área común','Comerciantes y transeúntes',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9414,'Ruido excesivo en la vía pública','Vecinos de la zona','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9415,'Acumulación de personas y alteración del orden','Testigos en el lugar','Fines de semana',NULL),
(9416,'Acumulación de personas y alteración del orden',NULL,'Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9417,'Incumplimiento de normas de uso de espacios públicos','Comerciantes y transeúntes','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9418,'Posible riesgo en área común','Personal de un establecimiento','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9419,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9420,'Conflicto vial y obstrucción de circulación','Propietario del inmueble y vecinos','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9421,'Problema de convivencia vecinal',NULL,'Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9422,'Posible riesgo en área común','Conductores y peatones','Cada noche',NULL),
(9423,'Posible riesgo en área común','Testigos en el lugar','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9424,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9425,'Reportes recurrentes de disturbios nocturnos','Vecinos de la zona',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9426,'Acumulación de personas y alteración del orden',NULL,'Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9427,'Posible riesgo en área común','Personal de un establecimiento','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9428,'Problema de convivencia vecinal','Comerciantes y transeúntes','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9429,'Acumulación de personas y alteración del orden','Propietario del inmueble y vecinos','Ocasional',NULL),
(9430,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9431,'Problema de convivencia vecinal',NULL,NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9432,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9433,'Posible riesgo en área común','Propietario del inmueble y vecinos','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9434,'Situación sospechosa sin categoría específica','Usuarios del transporte público','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9435,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9436,'Incumplimiento de normas de uso de espacios públicos',NULL,'Diario',NULL),
(9437,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9438,'Acumulación de personas y alteración del orden','Testigos en el lugar','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9439,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9440,'Situación sospechosa sin categoría específica','Comerciantes y transeúntes','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9441,'Invasión de banqueta por comercio',NULL,'Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9442,'Incumplimiento de normas de uso de espacios públicos','Propietario del inmueble y vecinos','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9443,'Reportes recurrentes de disturbios nocturnos','Comerciantes y transeúntes',NULL,NULL),
(9444,'Venta ambulante en zona no permitida','Vecinos de la zona','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9445,'Problema de convivencia vecinal','Comerciantes y transeúntes','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9446,'Incumplimiento de normas de uso de espacios públicos',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9447,'Incumplimiento de normas de uso de espacios públicos','Propietario del inmueble y vecinos','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9448,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9449,'Incumplimiento de normas de uso de espacios públicos','Usuarios del transporte público',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9450,'Invasión de banqueta por comercio','Personal de un establecimiento','Cada noche',NULL),
(9451,'Conflicto vial y obstrucción de circulación',NULL,'Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9452,'Acumulación de personas y alteración del orden','Usuarios del transporte público','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9453,'Conflicto vial y obstrucción de circulación','Personal de un establecimiento','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9454,'Problema de convivencia vecinal','Propietario del inmueble y vecinos','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9455,'Venta ambulante en zona no permitida','Usuarios del transporte público',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9456,'Posible riesgo en área común',NULL,'Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9457,'Venta ambulante en zona no permitida','Vecinos de la zona','Varias veces por semana',NULL),
(9458,'Incumplimiento de normas de uso de espacios públicos','Grupo de personas en la vía pública','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9459,'Ruido excesivo en la vía pública','Grupo de personas en la vía pública','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9460,'Venta ambulante en zona no permitida','Personal de un establecimiento','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9461,'Invasión de banqueta por comercio',NULL,NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9462,'Posible riesgo en área común','Usuarios del transporte público','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9463,'Incumplimiento de normas de uso de espacios públicos','Grupo de personas en la vía pública','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9464,'Venta ambulante en zona no permitida','Personal de un establecimiento','Cada noche',NULL),
(9465,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9466,'Posible riesgo en área común',NULL,'Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9467,'Ruido excesivo en la vía pública','Vecinos de la zona',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9468,'Situación sospechosa sin categoría específica','Personal de un establecimiento','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9469,'Situación sospechosa sin categoría específica','Conductores y peatones','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9470,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9471,'Problema de convivencia vecinal',NULL,'Ocasional',NULL),
(9472,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9473,'Situación sospechosa sin categoría específica','Testigos en el lugar',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9474,'Ruido excesivo en la vía pública','Usuarios del transporte público','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9475,'Reportes recurrentes de disturbios nocturnos','Comerciantes y transeúntes','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9476,'Incumplimiento de normas de uso de espacios públicos',NULL,'Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9477,'Ruido excesivo en la vía pública','Personal de un establecimiento','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9478,'Conflicto vial y obstrucción de circulación','Propietario del inmueble y vecinos','Cada noche',NULL),
(9479,'Situación sospechosa sin categoría específica','Usuarios del transporte público',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9480,'Reportes recurrentes de disturbios nocturnos','Vecinos de la zona','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9481,'Posible riesgo en área común',NULL,'Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9482,'Ruido excesivo en la vía pública','Usuarios del transporte público','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9483,'Posible riesgo en área común','Conductores y peatones','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9484,'Venta ambulante en zona no permitida','Personal de un establecimiento','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9485,'Acumulación de personas y alteración del orden','Comerciantes y transeúntes',NULL,NULL),
(9486,'Ruido excesivo en la vía pública',NULL,'Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9487,'Situación sospechosa sin categoría específica','Usuarios del transporte público','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9488,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9489,'Problema de convivencia vecinal','Propietario del inmueble y vecinos','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9490,'Invasión de banqueta por comercio','Comerciantes y transeúntes','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9491,'Problema de convivencia vecinal',NULL,NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9492,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público','Varias veces por semana',NULL),
(9493,'Venta ambulante en zona no permitida','Comerciantes y transeúntes','Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9494,'Venta ambulante en zona no permitida','Comerciantes y transeúntes','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9495,'Acumulación de personas y alteración del orden','Propietario del inmueble y vecinos','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9496,'Problema de convivencia vecinal',NULL,'Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9497,'Venta ambulante en zona no permitida','Personal de un establecimiento',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9498,'Problema de convivencia vecinal','Usuarios del transporte público','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9499,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Varias veces por semana',NULL),
(9500,'Invasión de banqueta por comercio','Personal de un establecimiento','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9501,'Venta ambulante en zona no permitida',NULL,'Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9502,'Situación sospechosa sin categoría específica','Grupo de personas en la vía pública','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9503,'Invasión de banqueta por comercio','Vecinos de la zona',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9504,'Acumulación de personas y alteración del orden','Personal de un establecimiento','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9505,'Posible riesgo en área común','Usuarios del transporte público','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9506,'Venta ambulante en zona no permitida',NULL,'Ocasional',NULL),
(9507,'Invasión de banqueta por comercio','Comerciantes y transeúntes','Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9508,'Acumulación de personas y alteración del orden','Personal de un establecimiento','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9509,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9510,'Situación sospechosa sin categoría específica','Testigos en el lugar','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9511,'Venta ambulante en zona no permitida',NULL,'Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9512,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9513,'Reportes recurrentes de disturbios nocturnos','Testigos en el lugar','Fines de semana',NULL),
(9514,'Invasión de banqueta por comercio','Testigos en el lugar','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9515,'Problema de convivencia vecinal','Comerciantes y transeúntes',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9516,'Problema de convivencia vecinal',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9517,'Problema de convivencia vecinal','Conductores y peatones','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9518,'Invasión de banqueta por comercio','Vecinos de la zona','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9519,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9520,'Problema de convivencia vecinal','Testigos en el lugar','Fines de semana',NULL),
(9521,'Incumplimiento de normas de uso de espacios públicos',NULL,NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9522,'Invasión de banqueta por comercio','Testigos en el lugar','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9523,'Invasión de banqueta por comercio','Usuarios del transporte público','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9524,'Incumplimiento de normas de uso de espacios públicos','Comerciantes y transeúntes','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9525,'Acumulación de personas y alteración del orden','Usuarios del transporte público','Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9526,'Incumplimiento de normas de uso de espacios públicos',NULL,'Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9527,'Reportes recurrentes de disturbios nocturnos','Propietario del inmueble y vecinos',NULL,NULL),
(9528,'Invasión de banqueta por comercio','Comerciantes y transeúntes','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9529,'Invasión de banqueta por comercio','Testigos en el lugar','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9530,'Posible riesgo en área común','Vecinos de la zona','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9531,'Invasión de banqueta por comercio',NULL,'Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9532,'Conflicto vial y obstrucción de circulación','Propietario del inmueble y vecinos','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9533,'Reportes recurrentes de disturbios nocturnos','Personal de un establecimiento',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9534,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Ocasional',NULL),
(9535,'Incumplimiento de normas de uso de espacios públicos','Conductores y peatones','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9536,'Conflicto vial y obstrucción de circulación',NULL,'Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9537,'Invasión de banqueta por comercio','Testigos en el lugar','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9538,'Problema de convivencia vecinal','Vecinos de la zona','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9539,'Venta ambulante en zona no permitida','Conductores y peatones',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9540,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9541,'Acumulación de personas y alteración del orden',NULL,'Fines de semana',NULL),
(9542,'Incumplimiento de normas de uso de espacios públicos','Propietario del inmueble y vecinos','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9543,'Invasión de banqueta por comercio','Propietario del inmueble y vecinos','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9544,'Incumplimiento de normas de uso de espacios públicos','Conductores y peatones','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9545,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9546,'Posible riesgo en área común',NULL,'Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9547,'Situación sospechosa sin categoría específica','Conductores y peatones','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9548,'Invasión de banqueta por comercio','Vecinos de la zona','Varias veces por semana',NULL),
(9549,'Venta ambulante en zona no permitida','Conductores y peatones','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9550,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9551,'Conflicto vial y obstrucción de circulación',NULL,NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9552,'Invasión de banqueta por comercio','Propietario del inmueble y vecinos','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9553,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9554,'Situación sospechosa sin categoría específica','Comerciantes y transeúntes','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9555,'Conflicto vial y obstrucción de circulación','Comerciantes y transeúntes','Diario',NULL),
(9556,'Posible riesgo en área común',NULL,'Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9557,'Acumulación de personas y alteración del orden','Testigos en el lugar',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9558,'Ruido excesivo en la vía pública','Usuarios del transporte público','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9559,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9560,'Venta ambulante en zona no permitida','Grupo de personas en la vía pública','Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9561,'Incumplimiento de normas de uso de espacios públicos',NULL,'Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9562,'Ruido excesivo en la vía pública','Comerciantes y transeúntes','Ocasional',NULL),
(9563,'Invasión de banqueta por comercio','Usuarios del transporte público',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9564,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9565,'Posible riesgo en área común','Conductores y peatones','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9566,'Invasión de banqueta por comercio',NULL,'Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9567,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9568,'Conflicto vial y obstrucción de circulación','Usuarios del transporte público','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9569,'Acumulación de personas y alteración del orden','Vecinos de la zona',NULL,NULL),
(9570,'Posible riesgo en área común','Usuarios del transporte público','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9571,'Incumplimiento de normas de uso de espacios públicos',NULL,'Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9572,'Acumulación de personas y alteración del orden','Propietario del inmueble y vecinos','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9573,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9574,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9575,'Conflicto vial y obstrucción de circulación','Comerciantes y transeúntes',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9576,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana',NULL),
(9577,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9578,'Venta ambulante en zona no permitida','Conductores y peatones','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9579,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9580,'Ruido excesivo en la vía pública','Conductores y peatones','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9581,'Invasión de banqueta por comercio',NULL,NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9582,'Posible riesgo en área común','Testigos en el lugar','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9583,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Fines de semana',NULL),
(9584,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9585,'Situación sospechosa sin categoría específica','Conductores y peatones','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9586,'Posible riesgo en área común',NULL,'Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9587,'Incumplimiento de normas de uso de espacios públicos','Vecinos de la zona',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9588,'Situación sospechosa sin categoría específica','Vecinos de la zona','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9589,'Venta ambulante en zona no permitida','Comerciantes y transeúntes','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9590,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Diario',NULL),
(9591,'Venta ambulante en zona no permitida',NULL,'Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9592,'Venta ambulante en zona no permitida','Comerciantes y transeúntes','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9593,'Reportes recurrentes de disturbios nocturnos','Propietario del inmueble y vecinos',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9594,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9595,'Incumplimiento de normas de uso de espacios públicos','Conductores y peatones','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9596,'Posible riesgo en área común',NULL,'Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9597,'Acumulación de personas y alteración del orden','Personal de un establecimiento','Fines de semana',NULL),
(9598,'Posible riesgo en área común','Personal de un establecimiento','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9599,'Situación sospechosa sin categoría específica','Usuarios del transporte público',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9600,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9601,'Reportes recurrentes de disturbios nocturnos',NULL,'Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9602,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9603,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9604,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos','Cada noche',NULL),
(9605,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9606,'Venta ambulante en zona no permitida',NULL,'Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9607,'Acumulación de personas y alteración del orden','Vecinos de la zona','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9608,'Invasión de banqueta por comercio','Grupo de personas en la vía pública','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9609,'Acumulación de personas y alteración del orden','Propietario del inmueble y vecinos','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9610,'Incumplimiento de normas de uso de espacios públicos','Vecinos de la zona','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9611,'Posible riesgo en área común',NULL,NULL,NULL),
(9612,'Situación sospechosa sin categoría específica','Conductores y peatones','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9613,'Venta ambulante en zona no permitida','Testigos en el lugar','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9614,'Venta ambulante en zona no permitida','Usuarios del transporte público','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9615,'Posible riesgo en área común','Personal de un establecimiento','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9616,'Reportes recurrentes de disturbios nocturnos',NULL,'Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9617,'Acumulación de personas y alteración del orden','Propietario del inmueble y vecinos',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9618,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Ocasional',NULL),
(9619,'Conflicto vial y obstrucción de circulación','Comerciantes y transeúntes','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9620,'Ruido excesivo en la vía pública','Conductores y peatones','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9621,'Incumplimiento de normas de uso de espacios públicos',NULL,'Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9622,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9623,'Problema de convivencia vecinal','Conductores y peatones',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9624,'Invasión de banqueta por comercio','Propietario del inmueble y vecinos','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9625,'Invasión de banqueta por comercio','Usuarios del transporte público','Varias veces por semana',NULL),
(9626,'Problema de convivencia vecinal',NULL,'Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9627,'Acumulación de personas y alteración del orden','Propietario del inmueble y vecinos','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9628,'Incumplimiento de normas de uso de espacios públicos','Comerciantes y transeúntes','Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9629,'Incumplimiento de normas de uso de espacios públicos','Vecinos de la zona',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9630,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9631,'Ruido excesivo en la vía pública',NULL,'Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9632,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Varias veces por semana',NULL),
(9633,'Ruido excesivo en la vía pública','Conductores y peatones','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9634,'Reportes recurrentes de disturbios nocturnos','Comerciantes y transeúntes','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9635,'Problema de convivencia vecinal','Conductores y peatones',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9636,'Conflicto vial y obstrucción de circulación',NULL,'Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9637,'Invasión de banqueta por comercio','Propietario del inmueble y vecinos','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9638,'Invasión de banqueta por comercio','Testigos en el lugar','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9639,'Venta ambulante en zona no permitida','Usuarios del transporte público','Fines de semana',NULL),
(9640,'Reportes recurrentes de disturbios nocturnos','Conductores y peatones','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9641,'Invasión de banqueta por comercio',NULL,NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9642,'Invasión de banqueta por comercio','Personal de un establecimiento','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9643,'Invasión de banqueta por comercio','Usuarios del transporte público','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9644,'Invasión de banqueta por comercio','Vecinos de la zona','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9645,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9646,'Posible riesgo en área común',NULL,'Varias veces por semana',NULL),
(9647,'Incumplimiento de normas de uso de espacios públicos','Vecinos de la zona',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9648,'Situación sospechosa sin categoría específica','Vecinos de la zona','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9649,'Situación sospechosa sin categoría específica','Usuarios del transporte público','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9650,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9651,'Incumplimiento de normas de uso de espacios públicos',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9652,'Problema de convivencia vecinal','Conductores y peatones','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9653,'Conflicto vial y obstrucción de circulación','Propietario del inmueble y vecinos',NULL,NULL),
(9654,'Acumulación de personas y alteración del orden','Vecinos de la zona','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9655,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9656,'Reportes recurrentes de disturbios nocturnos',NULL,'Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9657,'Posible riesgo en área común','Comerciantes y transeúntes','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9658,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9659,'Invasión de banqueta por comercio','Vecinos de la zona',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9660,'Incumplimiento de normas de uso de espacios públicos','Usuarios del transporte público','Varias veces por semana',NULL),
(9661,'Posible riesgo en área común',NULL,'Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9662,'Conflicto vial y obstrucción de circulación','Propietario del inmueble y vecinos','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9663,'Conflicto vial y obstrucción de circulación','Comerciantes y transeúntes','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9664,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9665,'Problema de convivencia vecinal','Conductores y peatones',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9666,'Conflicto vial y obstrucción de circulación',NULL,'Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9667,'Posible riesgo en área común','Personal de un establecimiento','Diario',NULL),
(9668,'Acumulación de personas y alteración del orden','Vecinos de la zona','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9669,'Conflicto vial y obstrucción de circulación','Propietario del inmueble y vecinos','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9670,'Problema de convivencia vecinal','Propietario del inmueble y vecinos','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9671,'Problema de convivencia vecinal',NULL,NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9672,'Acumulación de personas y alteración del orden','Testigos en el lugar','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9673,'Reportes recurrentes de disturbios nocturnos','Testigos en el lugar','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9674,'Reportes recurrentes de disturbios nocturnos','Conductores y peatones','Diario',NULL),
(9675,'Invasión de banqueta por comercio','Grupo de personas en la vía pública','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9676,'Posible riesgo en área común',NULL,'Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9677,'Venta ambulante en zona no permitida','Vecinos de la zona',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9678,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9679,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9680,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9681,'Venta ambulante en zona no permitida',NULL,'Fines de semana',NULL),
(9682,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9683,'Posible riesgo en área común','Usuarios del transporte público',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9684,'Posible riesgo en área común','Usuarios del transporte público','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9685,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9686,'Conflicto vial y obstrucción de circulación',NULL,'Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9687,'Problema de convivencia vecinal','Testigos en el lugar','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9688,'Reportes recurrentes de disturbios nocturnos','Personal de un establecimiento','Varias veces por semana',NULL),
(9689,'Ruido excesivo en la vía pública','Propietario del inmueble y vecinos',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9690,'Reportes recurrentes de disturbios nocturnos','Testigos en el lugar','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9691,'Situación sospechosa sin categoría específica',NULL,'Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9692,'Ruido excesivo en la vía pública','Propietario del inmueble y vecinos','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9693,'Conflicto vial y obstrucción de circulación','Grupo de personas en la vía pública','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9694,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9695,'Situación sospechosa sin categoría específica','Conductores y peatones',NULL,NULL),
(9696,'Conflicto vial y obstrucción de circulación',NULL,'Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9697,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9698,'Reportes recurrentes de disturbios nocturnos','Propietario del inmueble y vecinos','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9699,'Acumulación de personas y alteración del orden','Testigos en el lugar','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9700,'Acumulación de personas y alteración del orden','Conductores y peatones','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9701,'Incumplimiento de normas de uso de espacios públicos',NULL,NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9702,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Ocasional',NULL),
(9703,'Venta ambulante en zona no permitida','Usuarios del transporte público','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9704,'Situación sospechosa sin categoría específica','Usuarios del transporte público','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9705,'Problema de convivencia vecinal','Usuarios del transporte público','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9706,'Incumplimiento de normas de uso de espacios públicos',NULL,'Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9707,'Conflicto vial y obstrucción de circulación','Grupo de personas en la vía pública',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9708,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9709,'Reportes recurrentes de disturbios nocturnos','Comerciantes y transeúntes','Fines de semana',NULL),
(9710,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9711,'Conflicto vial y obstrucción de circulación',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9712,'Conflicto vial y obstrucción de circulación','Personal de un establecimiento','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9713,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9714,'Ruido excesivo en la vía pública','Propietario del inmueble y vecinos','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9715,'Situación sospechosa sin categoría específica','Testigos en el lugar','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9716,'Conflicto vial y obstrucción de circulación',NULL,'Diario',NULL),
(9717,'Acumulación de personas y alteración del orden','Conductores y peatones','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9718,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9719,'Posible riesgo en área común','Grupo de personas en la vía pública',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9720,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9721,'Incumplimiento de normas de uso de espacios públicos',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9722,'Acumulación de personas y alteración del orden','Personal de un establecimiento','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9723,'Invasión de banqueta por comercio','Vecinos de la zona','Fines de semana',NULL),
(9724,'Posible riesgo en área común','Conductores y peatones','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9725,'Situación sospechosa sin categoría específica','Vecinos de la zona',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9726,'Problema de convivencia vecinal',NULL,'Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9727,'Ruido excesivo en la vía pública','Testigos en el lugar','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9728,'Acumulación de personas y alteración del orden','Usuarios del transporte público','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9729,'Acumulación de personas y alteración del orden','Usuarios del transporte público','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9730,'Ruido excesivo en la vía pública','Testigos en el lugar','Ocasional',NULL),
(9731,'Conflicto vial y obstrucción de circulación',NULL,NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9732,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9733,'Posible riesgo en área común','Personal de un establecimiento','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9734,'Posible riesgo en área común','Usuarios del transporte público','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9735,'Incumplimiento de normas de uso de espacios públicos','Vecinos de la zona','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9736,'Posible riesgo en área común',NULL,'Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9737,'Invasión de banqueta por comercio','Conductores y peatones',NULL,NULL),
(9738,'Acumulación de personas y alteración del orden','Personal de un establecimiento','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9739,'Problema de convivencia vecinal','Usuarios del transporte público','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9740,'Posible riesgo en área común','Conductores y peatones','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9741,'Posible riesgo en área común',NULL,'Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9742,'Incumplimiento de normas de uso de espacios públicos','Grupo de personas en la vía pública','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9743,'Reportes recurrentes de disturbios nocturnos','Vecinos de la zona',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9744,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos','Diario',NULL),
(9745,'Reportes recurrentes de disturbios nocturnos','Personal de un establecimiento','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9746,'Conflicto vial y obstrucción de circulación',NULL,'Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9747,'Incumplimiento de normas de uso de espacios públicos','Usuarios del transporte público','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9748,'Posible riesgo en área común','Vecinos de la zona','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9749,'Posible riesgo en área común','Testigos en el lugar',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9750,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9751,'Invasión de banqueta por comercio',NULL,'Diario',NULL),
(9752,'Incumplimiento de normas de uso de espacios públicos','Comerciantes y transeúntes','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9753,'Acumulación de personas y alteración del orden','Vecinos de la zona','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9754,'Ruido excesivo en la vía pública','Comerciantes y transeúntes','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9755,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9756,'Incumplimiento de normas de uso de espacios públicos',NULL,'Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9757,'Situación sospechosa sin categoría específica','Personal de un establecimiento','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9758,'Invasión de banqueta por comercio','Conductores y peatones','Cada noche',NULL),
(9759,'Ruido excesivo en la vía pública','Conductores y peatones','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9760,'Posible riesgo en área común','Usuarios del transporte público','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9761,'Posible riesgo en área común',NULL,NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9762,'Problema de convivencia vecinal','Personal de un establecimiento','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9763,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9764,'Ruido excesivo en la vía pública','Grupo de personas en la vía pública','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9765,'Acumulación de personas y alteración del orden','Propietario del inmueble y vecinos','Varias veces por semana',NULL),
(9766,'Reportes recurrentes de disturbios nocturnos',NULL,'Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9767,'Ruido excesivo en la vía pública','Propietario del inmueble y vecinos',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9768,'Incumplimiento de normas de uso de espacios públicos','Conductores y peatones','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9769,'Ruido excesivo en la vía pública','Testigos en el lugar','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9770,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9771,'Ruido excesivo en la vía pública',NULL,'Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9772,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Ocasional',NULL),
(9773,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9774,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9775,'Posible riesgo en área común','Grupo de personas en la vía pública','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9776,'Posible riesgo en área común',NULL,'Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9777,'Conflicto vial y obstrucción de circulación','Personal de un establecimiento','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9778,'Posible riesgo en área común','Personal de un establecimiento','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9779,'Invasión de banqueta por comercio','Vecinos de la zona',NULL,NULL),
(9780,'Incumplimiento de normas de uso de espacios públicos','Propietario del inmueble y vecinos','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9781,'Situación sospechosa sin categoría específica',NULL,'Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9782,'Venta ambulante en zona no permitida','Conductores y peatones','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9783,'Problema de convivencia vecinal','Personal de un establecimiento','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9784,'Problema de convivencia vecinal','Personal de un establecimiento','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9785,'Ruido excesivo en la vía pública','Testigos en el lugar',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9786,'Acumulación de personas y alteración del orden',NULL,'Varias veces por semana',NULL),
(9787,'Problema de convivencia vecinal','Vecinos de la zona','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9788,'Situación sospechosa sin categoría específica','Conductores y peatones','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9789,'Conflicto vial y obstrucción de circulación','Vecinos de la zona','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9790,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9791,'Reportes recurrentes de disturbios nocturnos',NULL,NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9792,'Acumulación de personas y alteración del orden','Conductores y peatones','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9793,'Posible riesgo en área común','Comerciantes y transeúntes','Diario',NULL),
(9794,'Problema de convivencia vecinal','Usuarios del transporte público','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9795,'Situación sospechosa sin categoría específica','Usuarios del transporte público','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9796,'Acumulación de personas y alteración del orden',NULL,'Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9797,'Problema de convivencia vecinal','Personal de un establecimiento',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9798,'Incumplimiento de normas de uso de espacios públicos','Usuarios del transporte público','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9799,'Venta ambulante en zona no permitida','Comerciantes y transeúntes','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9800,'Incumplimiento de normas de uso de espacios públicos','Propietario del inmueble y vecinos','Diario',NULL),
(9801,'Posible riesgo en área común',NULL,'Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9802,'Ruido excesivo en la vía pública','Propietario del inmueble y vecinos','Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9803,'Reportes recurrentes de disturbios nocturnos','Comerciantes y transeúntes',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9804,'Posible riesgo en área común','Conductores y peatones','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9805,'Problema de convivencia vecinal','Propietario del inmueble y vecinos','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9806,'Acumulación de personas y alteración del orden',NULL,'Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9807,'Venta ambulante en zona no permitida','Grupo de personas en la vía pública','Ocasional',NULL),
(9808,'Ruido excesivo en la vía pública','Personal de un establecimiento','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9809,'Reportes recurrentes de disturbios nocturnos','Testigos en el lugar',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9810,'Problema de convivencia vecinal','Propietario del inmueble y vecinos','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9811,'Posible riesgo en área común',NULL,'Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9812,'Incumplimiento de normas de uso de espacios públicos','Vecinos de la zona','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9813,'Situación sospechosa sin categoría específica','Conductores y peatones','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9814,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Fines de semana',NULL),
(9815,'Conflicto vial y obstrucción de circulación','Testigos en el lugar',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9816,'Ruido excesivo en la vía pública',NULL,'Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9817,'Incumplimiento de normas de uso de espacios públicos','Grupo de personas en la vía pública','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9818,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9819,'Venta ambulante en zona no permitida','Conductores y peatones','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9820,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9821,'Acumulación de personas y alteración del orden',NULL,NULL,NULL),
(9822,'Situación sospechosa sin categoría específica','Usuarios del transporte público','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9823,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9824,'Posible riesgo en área común','Vecinos de la zona','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9825,'Reportes recurrentes de disturbios nocturnos','Propietario del inmueble y vecinos','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9826,'Problema de convivencia vecinal',NULL,'Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9827,'Ruido excesivo en la vía pública','Vecinos de la zona',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9828,'Posible riesgo en área común','Comerciantes y transeúntes','Fines de semana',NULL),
(9829,'Venta ambulante en zona no permitida','Comerciantes y transeúntes','Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9830,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9831,'Venta ambulante en zona no permitida',NULL,'Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9832,'Incumplimiento de normas de uso de espacios públicos','Comerciantes y transeúntes','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9833,'Situación sospechosa sin categoría específica','Grupo de personas en la vía pública',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9834,'Incumplimiento de normas de uso de espacios públicos','Vecinos de la zona','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9835,'Incumplimiento de normas de uso de espacios públicos','Grupo de personas en la vía pública','Cada noche',NULL),
(9836,'Problema de convivencia vecinal',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9837,'Reportes recurrentes de disturbios nocturnos','Comerciantes y transeúntes','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9838,'Conflicto vial y obstrucción de circulación','Testigos en el lugar','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9839,'Problema de convivencia vecinal','Vecinos de la zona',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9840,'Ruido excesivo en la vía pública','Testigos en el lugar','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9841,'Invasión de banqueta por comercio',NULL,'Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9842,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Cada noche',NULL),
(9843,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9844,'Reportes recurrentes de disturbios nocturnos','Personal de un establecimiento','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9845,'Problema de convivencia vecinal','Vecinos de la zona',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9846,'Invasión de banqueta por comercio',NULL,'Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9847,'Situación sospechosa sin categoría específica','Testigos en el lugar','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9848,'Acumulación de personas y alteración del orden','Testigos en el lugar','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9849,'Incumplimiento de normas de uso de espacios públicos','Propietario del inmueble y vecinos','Cada noche',NULL),
(9850,'Posible riesgo en área común','Personal de un establecimiento','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9851,'Reportes recurrentes de disturbios nocturnos',NULL,NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9852,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9853,'Problema de convivencia vecinal','Comerciantes y transeúntes','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9854,'Invasión de banqueta por comercio','Vecinos de la zona','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9855,'Ruido excesivo en la vía pública','Grupo de personas en la vía pública','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9856,'Venta ambulante en zona no permitida',NULL,'Ocasional',NULL),
(9857,'Situación sospechosa sin categoría específica','Grupo de personas en la vía pública',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9858,'Ruido excesivo en la vía pública','Usuarios del transporte público','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9859,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9860,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9861,'Acumulación de personas y alteración del orden',NULL,'Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9862,'Ruido excesivo en la vía pública','Propietario del inmueble y vecinos','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9863,'Problema de convivencia vecinal','Conductores y peatones',NULL,NULL),
(9864,'Ruido excesivo en la vía pública','Personal de un establecimiento','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9865,'Venta ambulante en zona no permitida','Personal de un establecimiento','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9866,'Situación sospechosa sin categoría específica',NULL,'Fines de semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9867,'Incumplimiento de normas de uso de espacios públicos','Grupo de personas en la vía pública','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9868,'Situación sospechosa sin categoría específica','Conductores y peatones','Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9869,'Invasión de banqueta por comercio','Testigos en el lugar',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9870,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Fines de semana',NULL),
(9871,'Acumulación de personas y alteración del orden',NULL,'Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9872,'Ruido excesivo en la vía pública','Testigos en el lugar','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9873,'Invasión de banqueta por comercio','Vecinos de la zona','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9874,'Situación sospechosa sin categoría específica','Testigos en el lugar','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9875,'Ruido excesivo en la vía pública','Comerciantes y transeúntes',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9876,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9877,'Problema de convivencia vecinal','Conductores y peatones','Ocasional',NULL),
(9878,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9879,'Posible riesgo en área común','Testigos en el lugar','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9880,'Invasión de banqueta por comercio','Usuarios del transporte público','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9881,'Invasión de banqueta por comercio',NULL,NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9882,'Ruido excesivo en la vía pública','Testigos en el lugar','Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9883,'Situación sospechosa sin categoría específica','Vecinos de la zona','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9884,'Posible riesgo en área común','Comerciantes y transeúntes','Ocasional',NULL),
(9885,'Reportes recurrentes de disturbios nocturnos','Propietario del inmueble y vecinos','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9886,'Conflicto vial y obstrucción de circulación',NULL,'Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9887,'Acumulación de personas y alteración del orden','Testigos en el lugar',NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9888,'Problema de convivencia vecinal','Vecinos de la zona','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9889,'Invasión de banqueta por comercio','Usuarios del transporte público','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9890,'Situación sospechosa sin categoría específica','Usuarios del transporte público','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9891,'Posible riesgo en área común',NULL,'Cada noche',NULL),
(9892,'Acumulación de personas y alteración del orden','Personal de un establecimiento','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9893,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9894,'Acumulación de personas y alteración del orden','Comerciantes y transeúntes','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9895,'Reportes recurrentes de disturbios nocturnos','Vecinos de la zona','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9896,'Venta ambulante en zona no permitida',NULL,'Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9897,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9898,'Conflicto vial y obstrucción de circulación','Grupo de personas en la vía pública','Cada noche',NULL),
(9899,'Venta ambulante en zona no permitida','Personal de un establecimiento',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9900,'Problema de convivencia vecinal','Testigos en el lugar','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9901,'Situación sospechosa sin categoría específica',NULL,'Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9902,'Conflicto vial y obstrucción de circulación','Personal de un establecimiento','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9903,'Situación sospechosa sin categoría específica','Propietario del inmueble y vecinos','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9904,'Posible riesgo en área común','Propietario del inmueble y vecinos','Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9905,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos',NULL,NULL),
(9906,'Situación sospechosa sin categoría específica',NULL,'Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9907,'Ruido excesivo en la vía pública','Usuarios del transporte público','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9908,'Problema de convivencia vecinal','Testigos en el lugar','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9909,'Invasión de banqueta por comercio','Testigos en el lugar','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9910,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública','Diario','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9911,'Problema de convivencia vecinal',NULL,NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9912,'Venta ambulante en zona no permitida','Testigos en el lugar','Cada noche',NULL),
(9913,'Ruido excesivo en la vía pública','Grupo de personas en la vía pública','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9914,'Reportes recurrentes de disturbios nocturnos','Testigos en el lugar','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9915,'Posible riesgo en área común','Usuarios del transporte público','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9916,'Acumulación de personas y alteración del orden',NULL,'Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9917,'Conflicto vial y obstrucción de circulación','Usuarios del transporte público',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9918,'Conflicto vial y obstrucción de circulación','Comerciantes y transeúntes','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9919,'Conflicto vial y obstrucción de circulación','Testigos en el lugar','Cada noche',NULL),
(9920,'Posible riesgo en área común','Personal de un establecimiento','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9921,'Ruido excesivo en la vía pública',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9922,'Acumulación de personas y alteración del orden','Personal de un establecimiento','Varias veces por semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9923,'Conflicto vial y obstrucción de circulación','Propietario del inmueble y vecinos',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9924,'Invasión de banqueta por comercio','Personal de un establecimiento','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9925,'Reportes recurrentes de disturbios nocturnos','Vecinos de la zona','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9926,'Acumulación de personas y alteración del orden',NULL,'Cada noche',NULL),
(9927,'Invasión de banqueta por comercio','Conductores y peatones','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9928,'Reportes recurrentes de disturbios nocturnos','Propietario del inmueble y vecinos','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9929,'Reportes recurrentes de disturbios nocturnos','Usuarios del transporte público',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9930,'Acumulación de personas y alteración del orden','Testigos en el lugar','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9931,'Acumulación de personas y alteración del orden',NULL,'Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9932,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9933,'Ruido excesivo en la vía pública','Personal de un establecimiento','Fines de semana',NULL),
(9934,'Incumplimiento de normas de uso de espacios públicos','Grupo de personas en la vía pública','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9935,'Reportes recurrentes de disturbios nocturnos','Grupo de personas en la vía pública',NULL,'El reporte se realiza con fines preventivos y de atención temprana.'),
(9936,'Venta ambulante en zona no permitida',NULL,'Diario','El reporte se realiza con fines preventivos y de atención temprana.'),
(9937,'Venta ambulante en zona no permitida','Vecinos de la zona','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9938,'Venta ambulante en zona no permitida','Propietario del inmueble y vecinos','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9939,'Venta ambulante en zona no permitida','Conductores y peatones','Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9940,'Posible riesgo en área común','Vecinos de la zona','Cada noche',NULL),
(9941,'Situación sospechosa sin categoría específica',NULL,NULL,'Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9942,'Reportes recurrentes de disturbios nocturnos','Vecinos de la zona','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9943,'Ruido excesivo en la vía pública','Usuarios del transporte público','Ocasional','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9944,'Conflicto vial y obstrucción de circulación','Comerciantes y transeúntes','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9945,'Problema de convivencia vecinal','Grupo de personas en la vía pública','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9946,'Conflicto vial y obstrucción de circulación',NULL,'Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9947,'Posible riesgo en área común','Comerciantes y transeúntes',NULL,NULL),
(9948,'Conflicto vial y obstrucción de circulación','Testigos en el lugar','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9949,'Acumulación de personas y alteración del orden','Grupo de personas en la vía pública','Fines de semana','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9950,'Invasión de banqueta por comercio','Comerciantes y transeúntes','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9951,'Invasión de banqueta por comercio',NULL,'Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9952,'Reportes recurrentes de disturbios nocturnos','Testigos en el lugar','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9953,'Conflicto vial y obstrucción de circulación','Conductores y peatones',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9954,'Problema de convivencia vecinal','Usuarios del transporte público','Varias veces por semana',NULL),
(9955,'Posible riesgo en área común','Testigos en el lugar','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9956,'Acumulación de personas y alteración del orden',NULL,'Fines de semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9957,'Posible riesgo en área común','Vecinos de la zona','Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9958,'Situación sospechosa sin categoría específica','Grupo de personas en la vía pública','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9959,'Problema de convivencia vecinal','Usuarios del transporte público',NULL,'Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9960,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9961,'Problema de convivencia vecinal',NULL,'Cada noche',NULL),
(9962,'Incumplimiento de normas de uso de espacios públicos','Personal de un establecimiento','Cada noche','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9963,'Ruido excesivo en la vía pública','Personal de un establecimiento','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9964,'Situación sospechosa sin categoría específica','Conductores y peatones','Cada noche','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9965,'Venta ambulante en zona no permitida','Usuarios del transporte público',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9966,'Ruido excesivo en la vía pública',NULL,'Ocasional','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9967,'Conflicto vial y obstrucción de circulación','Testigos en el lugar','Varias veces por semana','El reporte se realiza con fines preventivos y de atención temprana.'),
(9968,'Posible riesgo en área común','Conductores y peatones','Fines de semana',NULL),
(9969,'Ruido excesivo en la vía pública','Propietario del inmueble y vecinos','Cada noche','El reporte se realiza con fines preventivos y de atención temprana.'),
(9970,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9971,'Conflicto vial y obstrucción de circulación',NULL,NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9972,'Conflicto vial y obstrucción de circulación','Testigos en el lugar','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9973,'Conflicto vial y obstrucción de circulación','Grupo de personas en la vía pública','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9974,'Posible riesgo en área común','Vecinos de la zona','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9975,'Ruido excesivo en la vía pública','Comerciantes y transeúntes','Ocasional',NULL),
(9976,'Conflicto vial y obstrucción de circulación',NULL,'Diario','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9977,'Conflicto vial y obstrucción de circulación','Vecinos de la zona',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9978,'Situación sospechosa sin categoría específica','Vecinos de la zona','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9979,'Conflicto vial y obstrucción de circulación','Conductores y peatones','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9980,'Incumplimiento de normas de uso de espacios públicos','Usuarios del transporte público','Diario','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9981,'Acumulación de personas y alteración del orden',NULL,'Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9982,'Problema de convivencia vecinal','Usuarios del transporte público','Varias veces por semana',NULL),
(9983,'Ruido excesivo en la vía pública','Usuarios del transporte público',NULL,'No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9984,'Conflicto vial y obstrucción de circulación','Vecinos de la zona','Varias veces por semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9985,'Posible riesgo en área común','Vecinos de la zona','Fines de semana','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9986,'Problema de convivencia vecinal',NULL,'Cada noche','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9987,'Situación sospechosa sin categoría específica','Testigos en el lugar','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9988,'Venta ambulante en zona no permitida','Grupo de personas en la vía pública','Fines de semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9989,'Problema de convivencia vecinal','Comerciantes y transeúntes',NULL,NULL),
(9990,'Problema de convivencia vecinal','Usuarios del transporte público','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9991,'Ruido excesivo en la vía pública',NULL,'Diario','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9992,'Problema de convivencia vecinal','Testigos en el lugar','Ocasional','Se solicita verificación y, en su caso, canalización a la autoridad correspondiente.'),
(9993,'Posible riesgo en área común','Usuarios del transporte público','Varias veces por semana','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9994,'Incumplimiento de normas de uso de espacios públicos','Testigos en el lugar','Cada noche','No se cuenta con datos adicionales; se requiere inspección en sitio.'),
(9995,'Acumulación de personas y alteración del orden','Personal de un establecimiento',NULL,'Se recomienda atender en horario indicado por la recurrencia reportada.'),
(9996,'Reportes recurrentes de disturbios nocturnos',NULL,'Ocasional',NULL),
(9997,'Acumulación de personas y alteración del orden','Testigos en el lugar','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.'),
(9998,'Problema de convivencia vecinal','Vecinos de la zona','Ocasional','El reporte se realiza con fines preventivos y de atención temprana.'),
(9999,'Acumulación de personas y alteración del orden','Usuarios del transporte público','Varias veces por semana','Se recomienda atender en horario indicado por la recurrencia reportada.'),
(10000,'Reportes recurrentes de disturbios nocturnos','Personal de un establecimiento','Ocasional','Se pide seguimiento debido a recurrencia y afectación a la comunidad.');