USE ReportesCiudadanos;
INSERT INTO ReporteViolenciaGenero (ReporteId,TipoViolencia,RelacionPersonaAgresora,NombreAgresor)
VALUES
(551,'Violencia sexual','Desconocido','Lucía Vargas'),
(552,'Violencia económica','Pareja actual','Carlos López'),
(553,'Violencia psicológica','Compañero de trabajo/escuela','Ricardo Vega'),
(554,'Violencia física','Pareja actual','Jorge Ortega'),
(555,'Violencia económica','Pareja actual','Laura Rojas'),
(556,'Violencia económica','Pareja actual','Daniela Cruz'),
(557,'Violencia psicológica','Desconocido','Ricardo Vega'),
(558,'Violencia digital','Pareja actual','Daniela Cruz'),
(559,'Violencia física','Desconocido','Pedro Sánchez'),
(560,'Violencia física','Amigo','Ana Torres'),
(561,'Violencia psicológica','Compañero de trabajo/escuela','Lucía Vargas'),
(562,'Violencia digital','Pareja actual','José Ramírez'),
(563,'Violencia psicológica','Expareja','Luis Méndez'),
(564,'Violencia psicológica','Familiar','Lucía Vargas'),
(565,'Violencia económica','Desconocido','Ricardo Vega'),
(566,'Violencia psicológica','Pareja actual','Ana Torres'),
(567,'Violencia sexual','Familiar','José Ramírez'),
(568,'Violencia sexual','Pareja actual','Laura Rojas'),
(569,'Violencia psicológica','Desconocido','Paola Moreno'),
(570,'Violencia digital','Pareja actual','Luis Méndez'),
(571,'Violencia física','Desconocido','José Ramírez'),
(572,'Violencia psicológica','Compañero de trabajo/escuela','María Hernández'),
(573,'Violencia psicológica','Pareja actual','María Hernández'),
(574,'Violencia física','Familiar','María Hernández'),
(575,'Violencia física','Expareja','Jorge Ortega'),
(576,'Violencia digital','Amigo','Miguel Castillo'),
(577,'Violencia económica','Familiar','Luis Méndez'),
(578,'Violencia económica','Familiar','Fernando Díaz'),
(579,'Violencia física','Amigo','Sofía Aguilar'),
(580,'Violencia económica','Compañero de trabajo/escuela','José Ramírez'),
(581,'Violencia física','Expareja','José Ramírez'),
(582,'Violencia psicológica','Amigo','Fernando Díaz'),
(583,'Violencia física','Expareja','Sofía Aguilar'),
(584,'Violencia psicológica','Compañero de trabajo/escuela','Jorge Ortega'),
(585,'Violencia digital','Expareja','Sofía Aguilar'),
(586,'Violencia física','Amigo','Lucía Vargas'),
(587,'Violencia psicológica','Pareja actual','María Hernández'),
(588,'Violencia digital','Pareja actual','Jorge Ortega'),
(589,'Violencia física','Amigo','Laura Rojas'),
(590,'Violencia digital','Familiar','Jorge Ortega'),
(591,'Violencia digital','Expareja','Ricardo Vega'),
(592,'Violencia física','Compañero de trabajo/escuela','Ricardo Vega'),
(593,'Violencia física','Desconocido','Paola Moreno'),
(594,'Violencia psicológica','Pareja actual','Miguel Castillo'),
(595,'Violencia psicológica','Desconocido','Jorge Ortega'),
(596,'Violencia digital','Amigo','Jorge Ortega'),
(597,'Violencia digital','Familiar','Sofía Aguilar'),
(598,'Violencia física','Amigo','Ana Torres'),
(599,'Violencia digital','Familiar','Daniela Cruz'),
(600,'Violencia psicológica','Pareja actual','Luis Méndez'),
(601,'Violencia económica','Compañero de trabajo/escuela','Pedro Sánchez'),
(602,'Violencia sexual','Compañero de trabajo/escuela','Paola Moreno'),
(603,'Violencia económica','Expareja','Pedro Sánchez'),
(604,'Violencia física','Pareja actual','María Hernández'),
(605,'Violencia psicológica','Desconocido','Carlos López'),
(606,'Violencia física','Familiar','Lucía Vargas'),
(607,'Violencia digital','Pareja actual','José Ramírez'),
(608,'Violencia física','Amigo','Jorge Ortega'),
(609,'Violencia digital','Expareja','Andrea Campos'),
(610,'Violencia física','Compañero de trabajo/escuela','Jorge Ortega'),
(611,'Violencia digital','Amigo','Miguel Castillo'),
(612,'Violencia psicológica','Pareja actual','Miguel Castillo'),
(613,'Violencia económica','Pareja actual','Andrea Campos'),
(614,'Violencia física','Compañero de trabajo/escuela','Luis Méndez'),
(615,'Violencia psicológica','Compañero de trabajo/escuela','Jorge Ortega'),
(616,'Violencia sexual','Amigo','Daniela Cruz'),
(617,'Violencia psicológica','Expareja','Ricardo Vega'),
(618,'Violencia sexual','Expareja','Fernando Díaz'),
(619,'Violencia psicológica','Compañero de trabajo/escuela','Jorge Ortega'),
(620,'Violencia económica','Familiar','Pedro Sánchez'),
(621,'Violencia digital','Pareja actual','Paola Moreno'),
(622,'Violencia digital','Compañero de trabajo/escuela','José Ramírez'),
(623,'Violencia digital','Pareja actual','Luis Méndez'),
(624,'Violencia física','Compañero de trabajo/escuela','Sofía Aguilar'),
(625,'Violencia psicológica','Amigo','Fernando Díaz'),
(626,'Violencia psicológica','Amigo','Fernando Díaz'),
(627,'Violencia económica','Amigo','Sofía Aguilar'),
(628,'Violencia digital','Familiar','Ricardo Vega'),
(629,'Violencia física','Amigo','Miguel Castillo'),
(630,'Violencia física','Expareja','Lucía Vargas'),
(631,'Violencia psicológica','Familiar','Ricardo Vega'),
(632,'Violencia económica','Familiar','Ana Torres'),
(633,'Violencia física','Compañero de trabajo/escuela','Carlos López'),
(634,'Violencia digital','Expareja','Fernando Díaz'),
(635,'Violencia económica','Amigo','Pedro Sánchez'),
(636,'Violencia física','Expareja','Daniela Cruz'),
(637,'Violencia digital','Familiar','Miguel Castillo'),
(638,'Violencia psicológica','Compañero de trabajo/escuela','Andrea Campos'),
(639,'Violencia sexual','Amigo','Paola Moreno'),
(640,'Violencia física','Compañero de trabajo/escuela','Jorge Ortega'),
(641,'Violencia digital','Expareja','Luis Méndez'),
(642,'Violencia física','Amigo','Andrea Campos'),
(643,'Violencia económica','Pareja actual','Luis Méndez'),
(644,'Violencia económica','Familiar','Sofía Aguilar'),
(645,'Violencia psicológica','Pareja actual','Fernando Díaz'),
(646,'Violencia digital','Familiar','Laura Rojas'),
(647,'Violencia sexual','Desconocido','Miguel Castillo'),
(648,'Violencia digital','Desconocido','Laura Rojas'),
(649,'Violencia sexual','Amigo','Fernando Díaz'),
(650,'Violencia física','Amigo','Lucía Vargas'),
(651,'Violencia económica','Amigo','Lucía Vargas'),
(652,'Violencia digital','Expareja','Miguel Castillo'),
(653,'Violencia digital','Familiar','Jorge Ortega'),
(654,'Violencia económica','Amigo','Ricardo Vega'),
(655,'Violencia sexual','Pareja actual','María Hernández'),
(656,'Violencia digital','Desconocido','Daniela Cruz'),
(657,'Violencia psicológica','Familiar','Sofía Aguilar'),
(658,'Violencia sexual','Amigo','Jorge Ortega'),
(659,'Violencia psicológica','Familiar','Laura Rojas'),
(660,'Violencia digital','Pareja actual','Pedro Sánchez'),
(661,'Violencia económica','Pareja actual','Carlos López'),
(662,'Violencia psicológica','Amigo','Ana Torres'),
(663,'Violencia económica','Familiar','Laura Rojas'),
(664,'Violencia psicológica','Desconocido','José Ramírez'),
(665,'Violencia económica','Familiar','José Ramírez'),
(666,'Violencia física','Amigo','Miguel Castillo'),
(667,'Violencia sexual','Desconocido','María Hernández'),
(668,'Violencia física','Familiar','Fernando Díaz'),
(669,'Violencia sexual','Compañero de trabajo/escuela','María Hernández'),
(670,'Violencia sexual','Desconocido','Ricardo Vega'),
(671,'Violencia económica','Compañero de trabajo/escuela','María Hernández'),
(672,'Violencia sexual','Desconocido','Luis Méndez'),
(673,'Violencia económica','Compañero de trabajo/escuela','Sofía Aguilar'),
(674,'Violencia física','Amigo','Laura Rojas'),
(675,'Violencia psicológica','Familiar','Paola Moreno'),
(676,'Violencia psicológica','Expareja','Pedro Sánchez'),
(677,'Violencia sexual','Compañero de trabajo/escuela','Pedro Sánchez'),
(678,'Violencia digital','Familiar','José Ramírez'),
(679,'Violencia económica','Compañero de trabajo/escuela','Jorge Ortega'),
(680,'Violencia económica','Compañero de trabajo/escuela','Carlos López'),
(681,'Violencia digital','Expareja','Pedro Sánchez'),
(682,'Violencia sexual','Familiar','José Ramírez'),
(683,'Violencia psicológica','Expareja','Ricardo Vega'),
(684,'Violencia sexual','Compañero de trabajo/escuela','Luis Méndez'),
(685,'Violencia psicológica','Expareja','Luis Méndez'),
(686,'Violencia física','Pareja actual','Andrea Campos'),
(687,'Violencia económica','Amigo','Ana Torres'),
(688,'Violencia psicológica','Desconocido','Miguel Castillo'),
(689,'Violencia psicológica','Familiar','Carlos López'),
(690,'Violencia psicológica','Expareja','Laura Rojas'),
(691,'Violencia digital','Desconocido','Paola Moreno'),
(692,'Violencia económica','Pareja actual','Ricardo Vega'),
(693,'Violencia digital','Familiar','Lucía Vargas'),
(694,'Violencia física','Amigo','Jorge Ortega'),
(695,'Violencia física','Amigo','Laura Rojas'),
(696,'Violencia física','Pareja actual','Paola Moreno'),
(697,'Violencia psicológica','Pareja actual','Carlos López'),
(698,'Violencia sexual','Compañero de trabajo/escuela','Lucía Vargas'),
(699,'Violencia sexual','Familiar','Ana Torres'),
(700,'Violencia económica','Desconocido','Paola Moreno'),
(701,'Violencia sexual','Pareja actual','Paola Moreno'),
(702,'Violencia económica','Pareja actual','Sofía Aguilar'),
(703,'Violencia física','Desconocido','Pedro Sánchez'),
(704,'Violencia digital','Expareja','Miguel Castillo'),
(705,'Violencia física','Desconocido','Sofía Aguilar'),
(706,'Violencia física','Pareja actual','Laura Rojas'),
(707,'Violencia sexual','Desconocido','José Ramírez'),
(708,'Violencia psicológica','Expareja','Ricardo Vega'),
(709,'Violencia física','Compañero de trabajo/escuela','Ana Torres'),
(710,'Violencia física','Desconocido','Daniela Cruz'),
(711,'Violencia sexual','Pareja actual','Sofía Aguilar'),
(712,'Violencia física','Pareja actual','Sofía Aguilar'),
(713,'Violencia digital','Familiar','María Hernández'),
(714,'Violencia física','Expareja','Pedro Sánchez'),
(715,'Violencia económica','Familiar','Ricardo Vega'),
(716,'Violencia digital','Expareja','José Ramírez'),
(717,'Violencia digital','Familiar','Pedro Sánchez'),
(718,'Violencia sexual','Expareja','Lucía Vargas'),
(719,'Violencia psicológica','Pareja actual','Miguel Castillo'),
(720,'Violencia sexual','Compañero de trabajo/escuela','Fernando Díaz'),
(721,'Violencia económica','Compañero de trabajo/escuela','José Ramírez'),
(722,'Violencia física','Expareja','Ricardo Vega'),
(723,'Violencia psicológica','Compañero de trabajo/escuela','Ana Torres'),
(724,'Violencia económica','Pareja actual','Lucía Vargas'),
(725,'Violencia psicológica','Expareja','Laura Rojas'),
(726,'Violencia digital','Desconocido','Sofía Aguilar'),
(727,'Violencia física','Pareja actual','Ricardo Vega'),
(728,'Violencia psicológica','Desconocido','Lucía Vargas'),
(729,'Violencia sexual','Desconocido','Laura Rojas'),
(730,'Violencia económica','Desconocido','Ricardo Vega'),
(731,'Violencia económica','Pareja actual','Ana Torres'),
(732,'Violencia económica','Expareja','Ricardo Vega'),
(733,'Violencia económica','Expareja','Pedro Sánchez'),
(734,'Violencia sexual','Pareja actual','Luis Méndez'),
(735,'Violencia económica','Desconocido','Paola Moreno'),
(736,'Violencia económica','Familiar','Jorge Ortega'),
(737,'Violencia psicológica','Expareja','Pedro Sánchez'),
(738,'Violencia sexual','Desconocido','Daniela Cruz'),
(739,'Violencia psicológica','Compañero de trabajo/escuela','Lucía Vargas'),
(740,'Violencia económica','Amigo','Sofía Aguilar'),
(741,'Violencia psicológica','Compañero de trabajo/escuela','María Hernández'),
(742,'Violencia económica','Familiar','Lucía Vargas'),
(743,'Violencia psicológica','Familiar','Carlos López'),
(744,'Violencia digital','Amigo','Ricardo Vega'),
(745,'Violencia psicológica','Expareja','Carlos López'),
(746,'Violencia digital','Familiar','Fernando Díaz'),
(747,'Violencia psicológica','Amigo','Fernando Díaz'),
(748,'Violencia física','Compañero de trabajo/escuela','Sofía Aguilar'),
(749,'Violencia física','Desconocido','Luis Méndez'),
(750,'Violencia económica','Familiar','Sofía Aguilar'),
(751,'Violencia económica','Familiar','Laura Rojas'),
(752,'Violencia digital','Desconocido','Ana Torres'),
(753,'Violencia psicológica','Amigo','Laura Rojas'),
(754,'Violencia psicológica','Pareja actual','Sofía Aguilar'),
(755,'Violencia física','Compañero de trabajo/escuela','Pedro Sánchez'),
(756,'Violencia digital','Compañero de trabajo/escuela','Ana Torres'),
(757,'Violencia psicológica','Pareja actual','Pedro Sánchez'),
(758,'Violencia psicológica','Expareja','Daniela Cruz'),
(759,'Violencia física','Desconocido','Carlos López'),
(760,'Violencia económica','Desconocido','Daniela Cruz'),
(761,'Violencia sexual','Amigo','Jorge Ortega'),
(762,'Violencia digital','Expareja','Lucía Vargas'),
(763,'Violencia psicológica','Desconocido','María Hernández'),
(764,'Violencia económica','Familiar','Jorge Ortega'),
(765,'Violencia sexual','Expareja','Luis Méndez'),
(766,'Violencia digital','Pareja actual','Pedro Sánchez'),
(767,'Violencia sexual','Familiar','Luis Méndez'),
(768,'Violencia psicológica','Compañero de trabajo/escuela','Miguel Castillo'),
(769,'Violencia sexual','Desconocido','Pedro Sánchez'),
(770,'Violencia sexual','Pareja actual','Andrea Campos'),
(771,'Violencia psicológica','Familiar','Miguel Castillo'),
(772,'Violencia digital','Amigo','Fernando Díaz'),
(773,'Violencia física','Amigo','Lucía Vargas'),
(774,'Violencia física','Familiar','Daniela Cruz'),
(775,'Violencia física','Compañero de trabajo/escuela','Jorge Ortega'),
(776,'Violencia física','Expareja','Ricardo Vega'),
(777,'Violencia sexual','Familiar','Carlos López'),
(778,'Violencia física','Amigo','Ana Torres'),
(779,'Violencia digital','Pareja actual','Luis Méndez'),
(780,'Violencia física','Expareja','Laura Rojas'),
(781,'Violencia económica','Desconocido','José Ramírez'),
(782,'Violencia psicológica','Expareja','Daniela Cruz'),
(783,'Violencia psicológica','Amigo','Jorge Ortega'),
(784,'Violencia psicológica','Desconocido','Ricardo Vega'),
(785,'Violencia física','Familiar','Laura Rojas'),
(786,'Violencia sexual','Amigo','Luis Méndez'),
(787,'Violencia digital','Expareja','Paola Moreno'),
(788,'Violencia sexual','Familiar','Jorge Ortega'),
(789,'Violencia física','Expareja','Laura Rojas'),
(790,'Violencia sexual','Amigo','José Ramírez'),
(791,'Violencia psicológica','Familiar','Ricardo Vega'),
(792,'Violencia digital','Expareja','Andrea Campos'),
(793,'Violencia sexual','Desconocido','Ana Torres'),
(794,'Violencia digital','Desconocido','Sofía Aguilar'),
(795,'Violencia física','Pareja actual','Ana Torres'),
(796,'Violencia física','Expareja','José Ramírez'),
(797,'Violencia digital','Compañero de trabajo/escuela','Pedro Sánchez'),
(798,'Violencia sexual','Compañero de trabajo/escuela','Carlos López'),
(799,'Violencia física','Expareja','Daniela Cruz'),
(800,'Violencia digital','Desconocido','Lucía Vargas'),
(801,'Violencia digital','Amigo','Miguel Castillo'),
(802,'Violencia física','Amigo','Carlos López'),
(803,'Violencia digital','Compañero de trabajo/escuela','María Hernández'),
(804,'Violencia digital','Familiar','Ricardo Vega'),
(805,'Violencia sexual','Familiar','María Hernández'),
(806,'Violencia sexual','Compañero de trabajo/escuela','Lucía Vargas'),
(807,'Violencia económica','Desconocido','Lucía Vargas'),
(808,'Violencia sexual','Compañero de trabajo/escuela','Jorge Ortega'),
(809,'Violencia económica','Amigo','Luis Méndez'),
(810,'Violencia económica','Desconocido','Daniela Cruz'),
(811,'Violencia sexual','Pareja actual','Pedro Sánchez'),
(812,'Violencia física','Compañero de trabajo/escuela','Carlos López'),
(813,'Violencia económica','Desconocido','Ana Torres'),
(814,'Violencia sexual','Pareja actual','Andrea Campos'),
(815,'Violencia digital','Compañero de trabajo/escuela','Laura Rojas'),
(816,'Violencia psicológica','Desconocido','José Ramírez'),
(817,'Violencia digital','Expareja','Andrea Campos'),
(818,'Violencia económica','Pareja actual','Jorge Ortega'),
(819,'Violencia económica','Pareja actual','José Ramírez'),
(820,'Violencia física','Amigo','Fernando Díaz'),
(821,'Violencia sexual','Compañero de trabajo/escuela','Lucía Vargas'),
(822,'Violencia económica','Expareja','Paola Moreno'),
(823,'Violencia sexual','Pareja actual','Luis Méndez'),
(824,'Violencia económica','Amigo','Miguel Castillo'),
(825,'Violencia psicológica','Compañero de trabajo/escuela','José Ramírez'),
(826,'Violencia sexual','Amigo','Andrea Campos'),
(827,'Violencia física','Familiar','Andrea Campos'),
(828,'Violencia digital','Desconocido','Fernando Díaz'),
(829,'Violencia sexual','Expareja','Daniela Cruz'),
(830,'Violencia económica','Pareja actual','Pedro Sánchez'),
(831,'Violencia física','Amigo','Ricardo Vega'),
(832,'Violencia económica','Amigo','Andrea Campos'),
(833,'Violencia física','Pareja actual','Pedro Sánchez'),
(834,'Violencia sexual','Desconocido','Andrea Campos'),
(835,'Violencia económica','Expareja','Jorge Ortega'),
(836,'Violencia psicológica','Amigo','Lucía Vargas'),
(837,'Violencia sexual','Compañero de trabajo/escuela','Fernando Díaz'),
(838,'Violencia sexual','Desconocido','Andrea Campos'),
(839,'Violencia psicológica','Compañero de trabajo/escuela','Ricardo Vega'),
(840,'Violencia psicológica','Desconocido','Sofía Aguilar'),
(841,'Violencia económica','Familiar','Jorge Ortega'),
(842,'Violencia sexual','Compañero de trabajo/escuela','Miguel Castillo'),
(843,'Violencia física','Compañero de trabajo/escuela','Sofía Aguilar'),
(844,'Violencia sexual','Desconocido','Andrea Campos'),
(845,'Violencia sexual','Expareja','Luis Méndez'),
(846,'Violencia económica','Compañero de trabajo/escuela','Daniela Cruz'),
(847,'Violencia sexual','Pareja actual','Jorge Ortega'),
(848,'Violencia económica','Compañero de trabajo/escuela','Fernando Díaz'),
(849,'Violencia psicológica','Compañero de trabajo/escuela','Sofía Aguilar'),
(850,'Violencia física','Compañero de trabajo/escuela','Miguel Castillo'),
(851,'Violencia sexual','Pareja actual','Lucía Vargas'),
(852,'Violencia económica','Amigo','Carlos López'),
(853,'Violencia sexual','Amigo','Andrea Campos'),
(854,'Violencia digital','Amigo','Fernando Díaz'),
(855,'Violencia psicológica','Compañero de trabajo/escuela','Pedro Sánchez'),
(856,'Violencia física','Familiar','Sofía Aguilar'),
(857,'Violencia digital','Compañero de trabajo/escuela','Andrea Campos'),
(858,'Violencia sexual','Familiar','Fernando Díaz'),
(859,'Violencia física','Compañero de trabajo/escuela','Daniela Cruz'),
(860,'Violencia física','Compañero de trabajo/escuela','Luis Méndez'),
(861,'Violencia digital','Pareja actual','Carlos López'),
(862,'Violencia económica','Expareja','Andrea Campos'),
(863,'Violencia digital','Compañero de trabajo/escuela','Pedro Sánchez'),
(864,'Violencia psicológica','Pareja actual','Carlos López'),
(865,'Violencia psicológica','Pareja actual','Pedro Sánchez'),
(866,'Violencia psicológica','Compañero de trabajo/escuela','Luis Méndez'),
(867,'Violencia sexual','Pareja actual','Daniela Cruz'),
(868,'Violencia económica','Pareja actual','María Hernández'),
(869,'Violencia física','Desconocido','Laura Rojas'),
(870,'Violencia económica','Desconocido','Lucía Vargas'),
(871,'Violencia física','Desconocido','Carlos López'),
(872,'Violencia psicológica','Expareja','Jorge Ortega'),
(873,'Violencia económica','Pareja actual','Fernando Díaz'),
(874,'Violencia sexual','Desconocido','José Ramírez'),
(875,'Violencia económica','Familiar','Daniela Cruz'),
(876,'Violencia económica','Desconocido','Luis Méndez'),
(877,'Violencia psicológica','Desconocido','María Hernández'),
(878,'Violencia sexual','Compañero de trabajo/escuela','María Hernández'),
(879,'Violencia física','Amigo','Luis Méndez'),
(880,'Violencia física','Desconocido','Laura Rojas'),
(881,'Violencia digital','Familiar','Luis Méndez'),
(882,'Violencia psicológica','Amigo','Laura Rojas'),
(883,'Violencia digital','Desconocido','Daniela Cruz'),
(884,'Violencia digital','Amigo','Ana Torres'),
(885,'Violencia digital','Compañero de trabajo/escuela','Sofía Aguilar'),
(886,'Violencia sexual','Expareja','Sofía Aguilar'),
(887,'Violencia psicológica','Expareja','Daniela Cruz'),
(888,'Violencia digital','Pareja actual','Lucía Vargas'),
(889,'Violencia económica','Compañero de trabajo/escuela','Paola Moreno'),
(890,'Violencia digital','Compañero de trabajo/escuela','Carlos López'),
(891,'Violencia sexual','Compañero de trabajo/escuela','Andrea Campos'),
(892,'Violencia psicológica','Pareja actual','Carlos López'),
(893,'Violencia económica','Compañero de trabajo/escuela','María Hernández'),
(894,'Violencia digital','Pareja actual','Miguel Castillo'),
(895,'Violencia sexual','Amigo','María Hernández'),
(896,'Violencia económica','Desconocido','Ana Torres'),
(897,'Violencia psicológica','Amigo','Daniela Cruz'),
(898,'Violencia psicológica','Compañero de trabajo/escuela','Sofía Aguilar'),
(899,'Violencia física','Desconocido','Daniela Cruz'),
(900,'Violencia física','Amigo','Jorge Ortega'),
(901,'Violencia sexual','Amigo','María Hernández'),
(902,'Violencia económica','Expareja','Miguel Castillo'),
(903,'Violencia psicológica','Pareja actual','Ricardo Vega'),
(904,'Violencia sexual','Pareja actual','Paola Moreno'),
(905,'Violencia digital','Pareja actual','Andrea Campos'),
(906,'Violencia psicológica','Desconocido','Fernando Díaz'),
(907,'Violencia digital','Amigo','José Ramírez'),
(908,'Violencia sexual','Desconocido','Jorge Ortega'),
(909,'Violencia económica','Compañero de trabajo/escuela','Ricardo Vega'),
(910,'Violencia digital','Familiar','Daniela Cruz'),
(911,'Violencia digital','Pareja actual','Ricardo Vega'),
(912,'Violencia física','Familiar','Sofía Aguilar'),
(913,'Violencia física','Expareja','Sofía Aguilar'),
(914,'Violencia digital','Amigo','Ana Torres'),
(915,'Violencia física','Compañero de trabajo/escuela','Andrea Campos'),
(916,'Violencia física','Desconocido','Andrea Campos'),
(917,'Violencia sexual','Amigo','Pedro Sánchez'),
(918,'Violencia física','Familiar','Carlos López'),
(919,'Violencia digital','Amigo','Andrea Campos'),
(920,'Violencia económica','Amigo','Ana Torres'),
(921,'Violencia sexual','Pareja actual','Sofía Aguilar'),
(922,'Violencia sexual','Desconocido','Jorge Ortega'),
(923,'Violencia digital','Desconocido','Ana Torres'),
(924,'Violencia digital','Desconocido','Laura Rojas'),
(925,'Violencia digital','Familiar','Carlos López'),
(926,'Violencia económica','Familiar','Ricardo Vega'),
(927,'Violencia física','Expareja','Luis Méndez'),
(928,'Violencia económica','Amigo','Ana Torres'),
(929,'Violencia sexual','Pareja actual','Luis Méndez'),
(930,'Violencia física','Pareja actual','Daniela Cruz'),
(931,'Violencia sexual','Expareja','José Ramírez'),
(932,'Violencia física','Pareja actual','Fernando Díaz'),
(933,'Violencia psicológica','Familiar','Daniela Cruz'),
(934,'Violencia digital','Expareja','Fernando Díaz'),
(935,'Violencia digital','Pareja actual','Carlos López'),
(936,'Violencia física','Compañero de trabajo/escuela','Fernando Díaz'),
(937,'Violencia económica','Pareja actual','Miguel Castillo'),
(938,'Violencia psicológica','Expareja','Paola Moreno'),
(939,'Violencia física','Compañero de trabajo/escuela','Laura Rojas'),
(940,'Violencia digital','Familiar','Paola Moreno'),
(941,'Violencia económica','Amigo','Lucía Vargas'),
(942,'Violencia psicológica','Pareja actual','Sofía Aguilar'),
(943,'Violencia física','Expareja','Lucía Vargas'),
(944,'Violencia sexual','Amigo','Ana Torres'),
(945,'Violencia sexual','Desconocido','Ricardo Vega'),
(946,'Violencia económica','Compañero de trabajo/escuela','Miguel Castillo'),
(947,'Violencia física','Amigo','Pedro Sánchez'),
(948,'Violencia sexual','Desconocido','Carlos López'),
(949,'Violencia económica','Familiar','Ana Torres'),
(950,'Violencia psicológica','Pareja actual','Paola Moreno'),
(951,'Violencia psicológica','Compañero de trabajo/escuela','Pedro Sánchez'),
(952,'Violencia digital','Amigo','Fernando Díaz'),
(953,'Violencia sexual','Pareja actual','Miguel Castillo'),
(954,'Violencia económica','Compañero de trabajo/escuela','Andrea Campos'),
(955,'Violencia sexual','Desconocido','Paola Moreno'),
(956,'Violencia económica','Familiar','Carlos López'),
(957,'Violencia digital','Compañero de trabajo/escuela','Luis Méndez'),
(958,'Violencia física','Expareja','Fernando Díaz'),
(959,'Violencia física','Amigo','Miguel Castillo'),
(960,'Violencia sexual','Amigo','José Ramírez'),
(961,'Violencia psicológica','Desconocido','Laura Rojas'),
(962,'Violencia psicológica','Pareja actual','Ricardo Vega'),
(963,'Violencia sexual','Amigo','Sofía Aguilar'),
(964,'Violencia digital','Amigo','José Ramírez'),
(965,'Violencia sexual','Familiar','José Ramírez'),
(966,'Violencia digital','Familiar','Miguel Castillo'),
(967,'Violencia psicológica','Pareja actual','Ricardo Vega'),
(968,'Violencia psicológica','Compañero de trabajo/escuela','Lucía Vargas'),
(969,'Violencia psicológica','Desconocido','Jorge Ortega'),
(970,'Violencia digital','Familiar','María Hernández'),
(971,'Violencia física','Desconocido','Lucía Vargas'),
(972,'Violencia psicológica','Amigo','Jorge Ortega'),
(973,'Violencia física','Amigo','José Ramírez'),
(974,'Violencia sexual','Pareja actual','Luis Méndez'),
(975,'Violencia económica','Amigo','Laura Rojas'),
(976,'Violencia sexual','Familiar','Fernando Díaz'),
(977,'Violencia sexual','Desconocido','Ricardo Vega'),
(978,'Violencia sexual','Familiar','José Ramírez'),
(979,'Violencia psicológica','Pareja actual','Sofía Aguilar'),
(980,'Violencia física','Familiar','Fernando Díaz'),
(981,'Violencia sexual','Amigo','Daniela Cruz'),
(982,'Violencia sexual','Compañero de trabajo/escuela','Pedro Sánchez'),
(983,'Violencia digital','Familiar','Paola Moreno'),
(984,'Violencia sexual','Familiar','Luis Méndez'),
(985,'Violencia digital','Desconocido','Jorge Ortega'),
(986,'Violencia económica','Familiar','Miguel Castillo'),
(987,'Violencia física','Amigo','Lucía Vargas'),
(988,'Violencia digital','Familiar','Andrea Campos'),
(989,'Violencia psicológica','Familiar','Pedro Sánchez'),
(990,'Violencia física','Compañero de trabajo/escuela','Fernando Díaz'),
(991,'Violencia económica','Familiar','Fernando Díaz'),
(992,'Violencia sexual','Compañero de trabajo/escuela','Andrea Campos'),
(993,'Violencia digital','Amigo','José Ramírez'),
(994,'Violencia psicológica','Expareja','Andrea Campos'),
(995,'Violencia psicológica','Compañero de trabajo/escuela','Jorge Ortega'),
(996,'Violencia económica','Familiar','Andrea Campos'),
(997,'Violencia digital','Desconocido','Luis Méndez'),
(998,'Violencia psicológica','Compañero de trabajo/escuela','Luis Méndez'),
(999,'Violencia psicológica','Amigo','Laura Rojas'),
(1000,'Violencia económica','Pareja actual','Fernando Díaz'),
(1001,'Violencia digital','Pareja actual','María Hernández'),
(1002,'Violencia sexual','Desconocido','Andrea Campos'),
(1003,'Violencia económica','Expareja','Ana Torres'),
(1004,'Violencia económica','Amigo','Ana Torres'),
(1005,'Violencia económica','Pareja actual','Miguel Castillo'),
(1006,'Violencia económica','Amigo','María Hernández'),
(1007,'Violencia física','Desconocido','Jorge Ortega'),
(1008,'Violencia psicológica','Expareja','José Ramírez'),
(1009,'Violencia digital','Expareja','Sofía Aguilar'),
(1010,'Violencia digital','Desconocido','Jorge Ortega'),
(1011,'Violencia psicológica','Amigo','Fernando Díaz'),
(1012,'Violencia digital','Amigo','Fernando Díaz'),
(1013,'Violencia económica','Compañero de trabajo/escuela','José Ramírez'),
(1014,'Violencia sexual','Amigo','Laura Rojas'),
(1015,'Violencia sexual','Familiar','Jorge Ortega'),
(1016,'Violencia psicológica','Familiar','Luis Méndez'),
(1017,'Violencia física','Desconocido','Paola Moreno'),
(1018,'Violencia física','Pareja actual','Paola Moreno'),
(1019,'Violencia psicológica','Expareja','Paola Moreno'),
(1020,'Violencia física','Amigo','Sofía Aguilar'),
(1021,'Violencia económica','Amigo','María Hernández'),
(1022,'Violencia digital','Amigo','Daniela Cruz'),
(1023,'Violencia digital','Pareja actual','Ana Torres'),
(1024,'Violencia psicológica','Amigo','Ana Torres'),
(1025,'Violencia económica','Amigo','María Hernández'),
(1026,'Violencia física','Compañero de trabajo/escuela','Carlos López'),
(1027,'Violencia física','Familiar','Jorge Ortega'),
(1028,'Violencia económica','Amigo','Sofía Aguilar'),
(1029,'Violencia física','Familiar','Daniela Cruz'),
(1030,'Violencia digital','Pareja actual','Luis Méndez'),
(1031,'Violencia económica','Desconocido','Luis Méndez'),
(1032,'Violencia física','Familiar','Andrea Campos'),
(1033,'Violencia psicológica','Expareja','Ana Torres'),
(1034,'Violencia sexual','Familiar','María Hernández'),
(1035,'Violencia económica','Expareja','José Ramírez'),
(1036,'Violencia física','Familiar','Daniela Cruz'),
(1037,'Violencia física','Expareja','Luis Méndez'),
(1038,'Violencia física','Familiar','Jorge Ortega'),
(1039,'Violencia psicológica','Amigo','Sofía Aguilar'),
(1040,'Violencia física','Compañero de trabajo/escuela','Laura Rojas'),
(1041,'Violencia psicológica','Expareja','María Hernández'),
(1042,'Violencia económica','Pareja actual','Luis Méndez'),
(1043,'Violencia física','Pareja actual','Fernando Díaz'),
(1044,'Violencia física','Familiar','Daniela Cruz'),
(1045,'Violencia física','Familiar','José Ramírez'),
(1046,'Violencia económica','Familiar','Jorge Ortega'),
(1047,'Violencia económica','Pareja actual','Luis Méndez'),
(1048,'Violencia psicológica','Familiar','Paola Moreno'),
(1049,'Violencia sexual','Familiar','Ricardo Vega'),
(1050,'Violencia psicológica','Familiar','María Hernández'),
(1051,'Violencia económica','Expareja','Carlos López'),
(1052,'Violencia psicológica','Expareja','José Ramírez'),
(1053,'Violencia digital','Expareja','Miguel Castillo'),
(1054,'Violencia física','Desconocido','Sofía Aguilar'),
(1055,'Violencia digital','Compañero de trabajo/escuela','Daniela Cruz'),
(1056,'Violencia psicológica','Desconocido','Fernando Díaz'),
(1057,'Violencia física','Desconocido','José Ramírez'),
(1058,'Violencia sexual','Pareja actual','Miguel Castillo'),
(1059,'Violencia psicológica','Desconocido','Lucía Vargas'),
(1060,'Violencia física','Amigo','Fernando Díaz'),
(1061,'Violencia sexual','Desconocido','Andrea Campos'),
(1062,'Violencia digital','Familiar','Carlos López'),
(1063,'Violencia física','Pareja actual','Laura Rojas'),
(1064,'Violencia física','Pareja actual','Ricardo Vega'),
(1065,'Violencia económica','Familiar','Miguel Castillo'),
(1066,'Violencia psicológica','Compañero de trabajo/escuela','Pedro Sánchez'),
(1067,'Violencia física','Pareja actual','Andrea Campos'),
(1068,'Violencia económica','Expareja','Daniela Cruz'),
(1069,'Violencia sexual','Familiar','Ana Torres'),
(1070,'Violencia económica','Desconocido','Fernando Díaz'),
(1071,'Violencia digital','Pareja actual','Laura Rojas'),
(1072,'Violencia sexual','Pareja actual','María Hernández'),
(1073,'Violencia económica','Compañero de trabajo/escuela','Pedro Sánchez'),
(1074,'Violencia sexual','Expareja','Luis Méndez'),
(1075,'Violencia física','Compañero de trabajo/escuela','Paola Moreno'),
(1076,'Violencia económica','Pareja actual','Ricardo Vega'),
(1077,'Violencia digital','Familiar','Ana Torres'),
(1078,'Violencia psicológica','Desconocido','Luis Méndez'),
(1079,'Violencia sexual','Expareja','Ricardo Vega'),
(1080,'Violencia digital','Desconocido','Sofía Aguilar'),
(1081,'Violencia digital','Desconocido','Sofía Aguilar'),
(1082,'Violencia sexual','Expareja','Daniela Cruz'),
(1083,'Violencia económica','Pareja actual','Fernando Díaz'),
(1084,'Violencia física','Amigo','Andrea Campos'),
(1085,'Violencia económica','Amigo','Laura Rojas'),
(1086,'Violencia digital','Compañero de trabajo/escuela','María Hernández'),
(1087,'Violencia sexual','Expareja','Paola Moreno'),
(1088,'Violencia física','Familiar','Lucía Vargas'),
(1089,'Violencia física','Desconocido','Fernando Díaz'),
(1090,'Violencia económica','Pareja actual','Lucía Vargas'),
(1091,'Violencia económica','Familiar','Fernando Díaz'),
(1092,'Violencia sexual','Pareja actual','Jorge Ortega'),
(1093,'Violencia económica','Pareja actual','Carlos López'),
(1094,'Violencia digital','Desconocido','Sofía Aguilar'),
(1095,'Violencia psicológica','Pareja actual','Pedro Sánchez'),
(1096,'Violencia física','Familiar','Carlos López'),
(1097,'Violencia psicológica','Expareja','Ricardo Vega'),
(1098,'Violencia sexual','Expareja','Paola Moreno'),
(1099,'Violencia económica','Amigo','Fernando Díaz'),
(1100,'Violencia económica','Familiar','Sofía Aguilar'),
(1101,'Violencia física','Desconocido','Carlos López'),
(1102,'Violencia psicológica','Pareja actual','Andrea Campos'),
(1103,'Violencia sexual','Expareja','Luis Méndez'),
(1104,'Violencia sexual','Pareja actual','Daniela Cruz'),
(1105,'Violencia económica','Pareja actual','Pedro Sánchez'),
(1106,'Violencia sexual','Expareja','Carlos López'),
(1107,'Violencia psicológica','Compañero de trabajo/escuela','Lucía Vargas'),
(1108,'Violencia digital','Compañero de trabajo/escuela','Luis Méndez'),
(1109,'Violencia digital','Compañero de trabajo/escuela','Pedro Sánchez'),
(1110,'Violencia económica','Compañero de trabajo/escuela','María Hernández'),
(1111,'Violencia sexual','Desconocido','Sofía Aguilar'),
(1112,'Violencia psicológica','Amigo','Ricardo Vega'),
(1113,'Violencia digital','Amigo','Luis Méndez'),
(1114,'Violencia digital','Desconocido','Luis Méndez'),
(1115,'Violencia psicológica','Pareja actual','Fernando Díaz'),
(1116,'Violencia sexual','Pareja actual','Miguel Castillo'),
(1117,'Violencia psicológica','Expareja','Sofía Aguilar'),
(1118,'Violencia económica','Familiar','Pedro Sánchez'),
(1119,'Violencia psicológica','Pareja actual','Sofía Aguilar'),
(1120,'Violencia psicológica','Expareja','Carlos López'),
(1121,'Violencia sexual','Amigo','Carlos López'),
(1122,'Violencia psicológica','Expareja','María Hernández'),
(1123,'Violencia digital','Compañero de trabajo/escuela','Luis Méndez'),
(1124,'Violencia psicológica','Expareja','Jorge Ortega'),
(1125,'Violencia sexual','Familiar','Ana Torres'),
(1126,'Violencia sexual','Compañero de trabajo/escuela','María Hernández'),
(1127,'Violencia económica','Pareja actual','María Hernández'),
(1128,'Violencia psicológica','Desconocido','Fernando Díaz'),
(1129,'Violencia económica','Compañero de trabajo/escuela','Fernando Díaz'),
(1130,'Violencia física','Amigo','Sofía Aguilar'),
(1131,'Violencia económica','Desconocido','María Hernández'),
(1132,'Violencia digital','Expareja','Lucía Vargas'),
(1133,'Violencia psicológica','Desconocido','Pedro Sánchez'),
(1134,'Violencia económica','Compañero de trabajo/escuela','María Hernández'),
(1135,'Violencia física','Amigo','Carlos López'),
(1136,'Violencia digital','Expareja','José Ramírez'),
(1137,'Violencia económica','Pareja actual','Lucía Vargas'),
(1138,'Violencia sexual','Expareja','Paola Moreno'),
(1139,'Violencia física','Expareja','Miguel Castillo'),
(1140,'Violencia sexual','Desconocido','Andrea Campos'),
(1141,'Violencia sexual','Familiar','Fernando Díaz'),
(1142,'Violencia económica','Compañero de trabajo/escuela','Miguel Castillo'),
(1143,'Violencia económica','Compañero de trabajo/escuela','Fernando Díaz'),
(1144,'Violencia sexual','Familiar','Ana Torres'),
(1145,'Violencia económica','Amigo','Luis Méndez'),
(1146,'Violencia sexual','Compañero de trabajo/escuela','Carlos López'),
(1147,'Violencia económica','Amigo','María Hernández'),
(1148,'Violencia física','Pareja actual','Carlos López'),
(1149,'Violencia psicológica','Pareja actual','Paola Moreno'),
(1150,'Violencia física','Desconocido','Pedro Sánchez');