USE ReportesCiudadanos;
INSERT INTO ReporteNarcomenudeo (ReporteId,TipoActividadSospechosa,NumeroPersonasInvolucradas,DescripcionPersonasInvolucradas,VehiculosRelacionados,FrecuenciaSuceso)
VALUES
(251,'Distribución desde vehículo',NULL,'Hombre con gorra negra entregando paquetes',NULL,'Varias veces por semana'),
(252,'Distribución desde vehículo',5,'Persona vigilando en la esquina',NULL,'Fines de semana'),
(253,'Intercambio sospechoso de paquetes',5,'Grupo de 3 personas intercambiando bolsitas','Taxi','Diario'),
(254,'Entrega rápida a transeúntes',5,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(255,'Entrega rápida a transeúntes',3,'Persona vigilando en la esquina',NULL,'Fines de semana'),
(256,'Venta de drogas en vía pública',5,'Persona vigilando en la esquina','Bicicleta','Fines de semana'),
(257,'Entrega rápida a transeúntes',3,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(258,'Distribución desde vehículo',4,'Persona vigilando en la esquina','Taxi',NULL),
(259,'Puntos de venta recurrentes',NULL,'Dos hombres jóvenes con mochilas','Auto blanco compacto','Varias veces por semana'),
(260,'Intercambio sospechoso de paquetes',2,'Grupo de 3 personas intercambiando bolsitas','Motocicleta negra sin placas','Varias veces por semana'),
(261,'Puntos de venta recurrentes',2,'Persona vigilando en la esquina','Auto blanco compacto','Varias veces por semana'),
(262,'Venta cerca de escuela',2,'Hombre con gorra negra entregando paquetes','Auto blanco compacto','Ocasional'),
(263,'Venta de drogas en vía pública',NULL,NULL,NULL,'Ocasional'),
(264,'Venta de drogas en vía pública',3,'Grupo de 3 personas intercambiando bolsitas',NULL,'Ocasional'),
(265,'Intercambio sospechoso de paquetes',2,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(266,'Entrega rápida a transeúntes',4,NULL,'Camioneta gris','Ocasional'),
(267,'Venta cerca de escuela',5,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Cada noche'),
(268,'Entrega rápida a transeúntes',4,'Grupo de 3 personas intercambiando bolsitas',NULL,'Diario'),
(269,'Puntos de venta recurrentes',NULL,NULL,'Camioneta gris',NULL),
(270,'Distribución desde vehículo',3,'Dos hombres jóvenes con mochilas','Auto blanco compacto',NULL),
(271,'Venta cerca de escuela',4,'Persona vigilando en la esquina','Taxi',NULL),
(272,'Puntos de venta recurrentes',3,'Pareja recibiendo dinero y entregando objetos pequeños','Motocicleta negra sin placas','Varias veces por semana'),
(273,'Distribución desde vehículo',NULL,'Grupo de 3 personas intercambiando bolsitas',NULL,'Diario'),
(274,'Venta de drogas en vía pública',5,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Diario'),
(275,'Intercambio sospechoso de paquetes',4,'Persona vigilando en la esquina',NULL,NULL),
(276,'Venta cerca de escuela',4,'Hombre con gorra negra entregando paquetes','Camioneta gris',NULL),
(277,'Venta cerca de escuela',NULL,NULL,'Bicicleta',NULL),
(278,'Intercambio sospechoso de paquetes',4,'Dos hombres jóvenes con mochilas',NULL,NULL),
(279,'Entrega rápida a transeúntes',2,'Dos hombres jóvenes con mochilas',NULL,'Diario'),
(280,'Venta de drogas en vía pública',5,NULL,NULL,'Fines de semana'),
(281,'Intercambio sospechoso de paquetes',4,NULL,NULL,'Cada noche'),
(282,'Entrega rápida a transeúntes',3,'Hombre con gorra negra entregando paquetes','Motocicleta negra sin placas','Diario'),
(283,'Venta de drogas en vía pública',2,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Varias veces por semana'),
(284,'Puntos de venta recurrentes',2,'Persona vigilando en la esquina','Auto blanco compacto','Fines de semana'),
(285,'Puntos de venta recurrentes',5,NULL,NULL,'Cada noche'),
(286,'Puntos de venta recurrentes',5,'Grupo de 3 personas intercambiando bolsitas','Auto blanco compacto',NULL),
(287,'Entrega rápida a transeúntes',NULL,NULL,NULL,'Varias veces por semana'),
(288,'Entrega rápida a transeúntes',5,NULL,'Bicicleta','Diario'),
(289,'Entrega rápida a transeúntes',3,'Persona vigilando en la esquina','Camioneta gris','Diario'),
(290,'Venta cerca de escuela',5,NULL,'Auto blanco compacto',NULL),
(291,'Puntos de venta recurrentes',2,NULL,NULL,NULL),
(292,'Entrega rápida a transeúntes',3,NULL,NULL,NULL),
(293,'Entrega rápida a transeúntes',5,NULL,NULL,'Cada noche'),
(294,'Intercambio sospechoso de paquetes',NULL,'Dos hombres jóvenes con mochilas',NULL,'Varias veces por semana'),
(295,'Venta de drogas en vía pública',5,'Persona vigilando en la esquina','Motocicleta negra sin placas','Cada noche'),
(296,'Intercambio sospechoso de paquetes',NULL,'Grupo de 3 personas intercambiando bolsitas',NULL,'Fines de semana'),
(297,'Intercambio sospechoso de paquetes',4,'Dos hombres jóvenes con mochilas','Bicicleta','Varias veces por semana'),
(298,'Puntos de venta recurrentes',2,'Persona vigilando en la esquina',NULL,NULL),
(299,'Distribución desde vehículo',5,NULL,'Auto blanco compacto','Varias veces por semana'),
(300,'Puntos de venta recurrentes',2,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Ocasional'),
(301,'Venta cerca de escuela',NULL,'Grupo de 3 personas intercambiando bolsitas',NULL,'Varias veces por semana'),
(302,'Puntos de venta recurrentes',NULL,'Dos hombres jóvenes con mochilas',NULL,'Cada noche'),
(303,'Puntos de venta recurrentes',2,'Persona vigilando en la esquina',NULL,NULL),
(304,'Venta de drogas en vía pública',3,'Dos hombres jóvenes con mochilas','Auto blanco compacto','Varias veces por semana'),
(305,'Venta de drogas en vía pública',2,NULL,'Taxi','Ocasional'),
(306,'Entrega rápida a transeúntes',NULL,'Hombre con gorra negra entregando paquetes',NULL,'Fines de semana'),
(307,'Puntos de venta recurrentes',5,NULL,'Bicicleta','Diario'),
(308,'Entrega rápida a transeúntes',2,NULL,'Bicicleta','Varias veces por semana'),
(309,'Intercambio sospechoso de paquetes',4,'Pareja recibiendo dinero y entregando objetos pequeños','Auto blanco compacto','Ocasional'),
(310,'Venta cerca de escuela',3,'Hombre con gorra negra entregando paquetes','Bicicleta','Diario'),
(311,'Venta de drogas en vía pública',5,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,NULL),
(312,'Venta cerca de escuela',5,NULL,'Auto blanco compacto',NULL),
(313,'Venta de drogas en vía pública',NULL,NULL,NULL,NULL),
(314,'Entrega rápida a transeúntes',2,'Grupo de 3 personas intercambiando bolsitas',NULL,'Ocasional'),
(315,'Intercambio sospechoso de paquetes',5,NULL,NULL,'Diario'),
(316,'Distribución desde vehículo',3,'Dos hombres jóvenes con mochilas',NULL,NULL),
(317,'Entrega rápida a transeúntes',5,NULL,NULL,'Varias veces por semana'),
(318,'Intercambio sospechoso de paquetes',4,NULL,NULL,NULL),
(319,'Venta de drogas en vía pública',2,'Grupo de 3 personas intercambiando bolsitas','Camioneta gris','Ocasional'),
(320,'Entrega rápida a transeúntes',4,'Dos hombres jóvenes con mochilas','Camioneta gris','Ocasional'),
(321,'Venta de drogas en vía pública',4,'Persona vigilando en la esquina',NULL,'Fines de semana'),
(322,'Venta cerca de escuela',4,'Persona vigilando en la esquina',NULL,NULL),
(323,'Intercambio sospechoso de paquetes',5,'Pareja recibiendo dinero y entregando objetos pequeños','Motocicleta negra sin placas',NULL),
(324,'Entrega rápida a transeúntes',4,'Hombre con gorra negra entregando paquetes','Bicicleta',NULL),
(325,'Venta cerca de escuela',NULL,NULL,NULL,'Cada noche'),
(326,'Puntos de venta recurrentes',4,NULL,NULL,'Diario'),
(327,'Distribución desde vehículo',4,NULL,NULL,'Ocasional'),
(328,'Venta cerca de escuela',2,NULL,'Taxi','Diario'),
(329,'Intercambio sospechoso de paquetes',4,NULL,NULL,'Varias veces por semana'),
(330,'Puntos de venta recurrentes',2,'Grupo de 3 personas intercambiando bolsitas','Taxi','Varias veces por semana'),
(331,'Intercambio sospechoso de paquetes',2,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Fines de semana'),
(332,'Venta de drogas en vía pública',NULL,'Hombre con gorra negra entregando paquetes','Bicicleta',NULL),
(333,'Entrega rápida a transeúntes',4,'Grupo de 3 personas intercambiando bolsitas','Auto blanco compacto','Fines de semana'),
(334,'Puntos de venta recurrentes',NULL,'Pareja recibiendo dinero y entregando objetos pequeños','Taxi','Varias veces por semana'),
(335,'Entrega rápida a transeúntes',2,'Hombre con gorra negra entregando paquetes',NULL,'Cada noche'),
(336,'Distribución desde vehículo',4,'Hombre con gorra negra entregando paquetes',NULL,NULL),
(337,'Puntos de venta recurrentes',NULL,NULL,NULL,NULL),
(338,'Intercambio sospechoso de paquetes',3,NULL,'Taxi','Ocasional'),
(339,'Distribución desde vehículo',NULL,'Persona vigilando en la esquina',NULL,NULL),
(340,'Intercambio sospechoso de paquetes',3,'Hombre con gorra negra entregando paquetes','Taxi',NULL),
(341,'Distribución desde vehículo',3,'Pareja recibiendo dinero y entregando objetos pequeños','Taxi','Varias veces por semana'),
(342,'Venta cerca de escuela',4,NULL,NULL,'Diario'),
(343,'Distribución desde vehículo',5,'Grupo de 3 personas intercambiando bolsitas',NULL,'Cada noche'),
(344,'Venta cerca de escuela',NULL,'Persona vigilando en la esquina',NULL,'Ocasional'),
(345,'Venta de drogas en vía pública',2,NULL,NULL,'Cada noche'),
(346,'Distribución desde vehículo',5,NULL,NULL,'Fines de semana'),
(347,'Venta de drogas en vía pública',4,'Pareja recibiendo dinero y entregando objetos pequeños','Auto blanco compacto',NULL),
(348,'Venta cerca de escuela',2,'Dos hombres jóvenes con mochilas','Camioneta gris','Varias veces por semana'),
(349,'Intercambio sospechoso de paquetes',5,NULL,NULL,NULL),
(350,'Venta cerca de escuela',NULL,'Dos hombres jóvenes con mochilas',NULL,NULL),
(351,'Distribución desde vehículo',3,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(352,'Venta cerca de escuela',3,NULL,'Bicicleta','Fines de semana'),
(353,'Venta de drogas en vía pública',3,NULL,NULL,NULL),
(354,'Intercambio sospechoso de paquetes',5,'Persona vigilando en la esquina','Camioneta gris','Diario'),
(355,'Venta de drogas en vía pública',2,NULL,'Taxi','Cada noche'),
(356,'Intercambio sospechoso de paquetes',3,NULL,NULL,'Cada noche'),
(357,'Puntos de venta recurrentes',2,'Persona vigilando en la esquina',NULL,'Ocasional'),
(358,'Distribución desde vehículo',NULL,NULL,NULL,'Fines de semana'),
(359,'Intercambio sospechoso de paquetes',5,'Persona vigilando en la esquina','Auto blanco compacto','Diario'),
(360,'Puntos de venta recurrentes',4,'Grupo de 3 personas intercambiando bolsitas',NULL,'Ocasional'),
(361,'Distribución desde vehículo',2,'Dos hombres jóvenes con mochilas','Auto blanco compacto','Varias veces por semana'),
(362,'Puntos de venta recurrentes',5,NULL,'Bicicleta','Varias veces por semana'),
(363,'Intercambio sospechoso de paquetes',2,NULL,NULL,'Cada noche'),
(364,'Venta de drogas en vía pública',NULL,'Grupo de 3 personas intercambiando bolsitas','Auto blanco compacto','Varias veces por semana'),
(365,'Intercambio sospechoso de paquetes',NULL,NULL,'Camioneta gris',NULL),
(366,'Intercambio sospechoso de paquetes',4,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Ocasional'),
(367,'Distribución desde vehículo',4,NULL,NULL,'Cada noche'),
(368,'Distribución desde vehículo',2,NULL,'Camioneta gris','Diario'),
(369,'Intercambio sospechoso de paquetes',4,NULL,'Motocicleta negra sin placas','Varias veces por semana'),
(370,'Intercambio sospechoso de paquetes',2,NULL,NULL,NULL),
(371,'Venta de drogas en vía pública',5,'Persona vigilando en la esquina',NULL,NULL),
(372,'Puntos de venta recurrentes',4,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Varias veces por semana'),
(373,'Puntos de venta recurrentes',2,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(374,'Puntos de venta recurrentes',4,'Dos hombres jóvenes con mochilas',NULL,'Diario'),
(375,'Entrega rápida a transeúntes',2,'Hombre con gorra negra entregando paquetes','Motocicleta negra sin placas','Diario'),
(376,'Distribución desde vehículo',3,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,NULL),
(377,'Intercambio sospechoso de paquetes',2,'Persona vigilando en la esquina','Motocicleta negra sin placas','Varias veces por semana'),
(378,'Entrega rápida a transeúntes',NULL,NULL,NULL,'Ocasional'),
(379,'Intercambio sospechoso de paquetes',2,'Hombre con gorra negra entregando paquetes',NULL,'Ocasional'),
(380,'Intercambio sospechoso de paquetes',3,NULL,NULL,'Ocasional'),
(381,'Venta de drogas en vía pública',5,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(382,'Puntos de venta recurrentes',4,'Dos hombres jóvenes con mochilas',NULL,'Cada noche'),
(383,'Entrega rápida a transeúntes',5,'Persona vigilando en la esquina',NULL,NULL),
(384,'Distribución desde vehículo',5,NULL,NULL,NULL),
(385,'Intercambio sospechoso de paquetes',3,NULL,NULL,'Ocasional'),
(386,'Venta cerca de escuela',4,'Hombre con gorra negra entregando paquetes',NULL,NULL),
(387,'Venta cerca de escuela',2,NULL,NULL,NULL),
(388,'Entrega rápida a transeúntes',NULL,'Grupo de 3 personas intercambiando bolsitas','Motocicleta negra sin placas','Diario'),
(389,'Venta de drogas en vía pública',NULL,'Grupo de 3 personas intercambiando bolsitas','Motocicleta negra sin placas','Fines de semana'),
(390,'Entrega rápida a transeúntes',NULL,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(391,'Puntos de venta recurrentes',NULL,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Diario'),
(392,'Distribución desde vehículo',2,NULL,'Camioneta gris','Fines de semana'),
(393,'Puntos de venta recurrentes',3,NULL,'Motocicleta negra sin placas','Fines de semana'),
(394,'Venta de drogas en vía pública',2,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Ocasional'),
(395,'Intercambio sospechoso de paquetes',NULL,NULL,NULL,'Varias veces por semana'),
(396,'Distribución desde vehículo',4,NULL,'Motocicleta negra sin placas',NULL),
(397,'Intercambio sospechoso de paquetes',NULL,NULL,NULL,'Cada noche'),
(398,'Venta de drogas en vía pública',4,'Pareja recibiendo dinero y entregando objetos pequeños','Camioneta gris','Cada noche'),
(399,'Puntos de venta recurrentes',4,NULL,NULL,NULL),
(400,'Venta cerca de escuela',NULL,'Dos hombres jóvenes con mochilas',NULL,'Ocasional'),
(401,'Entrega rápida a transeúntes',5,'Dos hombres jóvenes con mochilas','Bicicleta','Ocasional'),
(402,'Intercambio sospechoso de paquetes',3,NULL,'Bicicleta','Cada noche'),
(403,'Venta cerca de escuela',4,NULL,NULL,'Varias veces por semana'),
(404,'Puntos de venta recurrentes',3,NULL,NULL,NULL),
(405,'Puntos de venta recurrentes',2,'Grupo de 3 personas intercambiando bolsitas',NULL,'Fines de semana'),
(406,'Entrega rápida a transeúntes',2,NULL,'Auto blanco compacto','Varias veces por semana'),
(407,'Venta de drogas en vía pública',NULL,'Dos hombres jóvenes con mochilas','Taxi',NULL),
(408,'Puntos de venta recurrentes',5,'Persona vigilando en la esquina','Auto blanco compacto',NULL),
(409,'Entrega rápida a transeúntes',4,'Grupo de 3 personas intercambiando bolsitas','Auto blanco compacto','Ocasional'),
(410,'Entrega rápida a transeúntes',NULL,'Hombre con gorra negra entregando paquetes',NULL,NULL),
(411,'Distribución desde vehículo',3,NULL,NULL,NULL),
(412,'Venta de drogas en vía pública',NULL,NULL,'Taxi',NULL),
(413,'Entrega rápida a transeúntes',2,'Dos hombres jóvenes con mochilas','Camioneta gris','Varias veces por semana'),
(414,'Entrega rápida a transeúntes',5,'Hombre con gorra negra entregando paquetes','Bicicleta','Ocasional'),
(415,'Venta de drogas en vía pública',2,NULL,'Taxi',NULL),
(416,'Puntos de venta recurrentes',4,'Persona vigilando en la esquina','Camioneta gris',NULL),
(417,'Puntos de venta recurrentes',4,NULL,NULL,'Diario'),
(418,'Venta cerca de escuela',NULL,'Grupo de 3 personas intercambiando bolsitas','Bicicleta',NULL),
(419,'Distribución desde vehículo',4,NULL,'Auto blanco compacto','Varias veces por semana'),
(420,'Distribución desde vehículo',3,NULL,NULL,NULL),
(421,'Distribución desde vehículo',4,NULL,'Motocicleta negra sin placas','Fines de semana'),
(422,'Venta cerca de escuela',4,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Ocasional'),
(423,'Entrega rápida a transeúntes',NULL,NULL,'Motocicleta negra sin placas','Diario'),
(424,'Entrega rápida a transeúntes',2,'Dos hombres jóvenes con mochilas',NULL,'Cada noche'),
(425,'Venta de drogas en vía pública',3,NULL,'Taxi','Fines de semana'),
(426,'Intercambio sospechoso de paquetes',NULL,'Hombre con gorra negra entregando paquetes',NULL,'Varias veces por semana'),
(427,'Intercambio sospechoso de paquetes',3,'Grupo de 3 personas intercambiando bolsitas','Motocicleta negra sin placas','Fines de semana'),
(428,'Venta cerca de escuela',4,NULL,NULL,'Fines de semana'),
(429,'Venta cerca de escuela',2,'Dos hombres jóvenes con mochilas','Auto blanco compacto','Fines de semana'),
(430,'Venta de drogas en vía pública',5,'Persona vigilando en la esquina','Taxi','Varias veces por semana'),
(431,'Distribución desde vehículo',NULL,'Dos hombres jóvenes con mochilas',NULL,NULL),
(432,'Entrega rápida a transeúntes',NULL,'Pareja recibiendo dinero y entregando objetos pequeños','Taxi','Cada noche'),
(433,'Puntos de venta recurrentes',2,NULL,NULL,'Diario'),
(434,'Venta cerca de escuela',4,'Dos hombres jóvenes con mochilas','Bicicleta',NULL),
(435,'Entrega rápida a transeúntes',2,'Pareja recibiendo dinero y entregando objetos pequeños','Camioneta gris','Ocasional'),
(436,'Venta de drogas en vía pública',2,'Persona vigilando en la esquina','Auto blanco compacto','Fines de semana'),
(437,'Venta cerca de escuela',4,NULL,'Taxi','Fines de semana'),
(438,'Venta cerca de escuela',NULL,NULL,'Bicicleta',NULL),
(439,'Intercambio sospechoso de paquetes',NULL,NULL,NULL,'Ocasional'),
(440,'Intercambio sospechoso de paquetes',2,'Persona vigilando en la esquina','Camioneta gris','Varias veces por semana'),
(441,'Entrega rápida a transeúntes',3,'Grupo de 3 personas intercambiando bolsitas','Motocicleta negra sin placas','Cada noche'),
(442,'Intercambio sospechoso de paquetes',NULL,'Grupo de 3 personas intercambiando bolsitas','Camioneta gris',NULL),
(443,'Venta cerca de escuela',2,'Pareja recibiendo dinero y entregando objetos pequeños','Camioneta gris',NULL),
(444,'Intercambio sospechoso de paquetes',4,'Persona vigilando en la esquina',NULL,NULL),
(445,'Venta cerca de escuela',2,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Diario'),
(446,'Distribución desde vehículo',5,'Dos hombres jóvenes con mochilas',NULL,'Cada noche'),
(447,'Venta cerca de escuela',5,NULL,NULL,'Varias veces por semana'),
(448,'Distribución desde vehículo',NULL,NULL,NULL,NULL),
(449,'Distribución desde vehículo',4,'Dos hombres jóvenes con mochilas',NULL,'Varias veces por semana'),
(450,'Distribución desde vehículo',5,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Ocasional'),
(451,'Puntos de venta recurrentes',5,'Dos hombres jóvenes con mochilas','Taxi','Ocasional'),
(452,'Puntos de venta recurrentes',5,NULL,'Taxi','Cada noche'),
(453,'Entrega rápida a transeúntes',4,'Grupo de 3 personas intercambiando bolsitas',NULL,'Diario'),
(454,'Puntos de venta recurrentes',4,'Pareja recibiendo dinero y entregando objetos pequeños','Motocicleta negra sin placas','Ocasional'),
(455,'Intercambio sospechoso de paquetes',3,'Dos hombres jóvenes con mochilas',NULL,'Diario'),
(456,'Intercambio sospechoso de paquetes',5,'Pareja recibiendo dinero y entregando objetos pequeños','Auto blanco compacto','Diario'),
(457,'Puntos de venta recurrentes',4,'Persona vigilando en la esquina','Camioneta gris','Diario'),
(458,'Venta cerca de escuela',5,'Hombre con gorra negra entregando paquetes',NULL,NULL),
(459,'Distribución desde vehículo',2,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(460,'Intercambio sospechoso de paquetes',4,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Cada noche'),
(461,'Distribución desde vehículo',2,NULL,'Taxi','Diario'),
(462,'Intercambio sospechoso de paquetes',3,'Dos hombres jóvenes con mochilas',NULL,NULL),
(463,'Venta de drogas en vía pública',3,'Dos hombres jóvenes con mochilas',NULL,NULL),
(464,'Puntos de venta recurrentes',4,'Dos hombres jóvenes con mochilas',NULL,'Cada noche'),
(465,'Venta de drogas en vía pública',2,'Grupo de 3 personas intercambiando bolsitas',NULL,'Varias veces por semana'),
(466,'Venta de drogas en vía pública',4,'Grupo de 3 personas intercambiando bolsitas','Camioneta gris','Diario'),
(467,'Puntos de venta recurrentes',4,'Grupo de 3 personas intercambiando bolsitas',NULL,'Ocasional'),
(468,'Intercambio sospechoso de paquetes',3,'Pareja recibiendo dinero y entregando objetos pequeños','Motocicleta negra sin placas',NULL),
(469,'Venta cerca de escuela',5,'Hombre con gorra negra entregando paquetes',NULL,'Varias veces por semana'),
(470,'Entrega rápida a transeúntes',5,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Diario'),
(471,'Venta de drogas en vía pública',5,'Dos hombres jóvenes con mochilas',NULL,NULL),
(472,'Puntos de venta recurrentes',3,NULL,NULL,'Diario'),
(473,'Intercambio sospechoso de paquetes',4,'Hombre con gorra negra entregando paquetes',NULL,NULL),
(474,'Venta cerca de escuela',NULL,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Diario'),
(475,'Puntos de venta recurrentes',2,NULL,'Auto blanco compacto',NULL),
(476,'Venta de drogas en vía pública',NULL,'Dos hombres jóvenes con mochilas','Camioneta gris','Cada noche'),
(477,'Entrega rápida a transeúntes',4,'Dos hombres jóvenes con mochilas',NULL,NULL),
(478,'Intercambio sospechoso de paquetes',5,NULL,'Motocicleta negra sin placas','Varias veces por semana'),
(479,'Intercambio sospechoso de paquetes',4,'Hombre con gorra negra entregando paquetes',NULL,'Cada noche'),
(480,'Intercambio sospechoso de paquetes',NULL,'Hombre con gorra negra entregando paquetes','Taxi','Diario'),
(481,'Distribución desde vehículo',5,'Hombre con gorra negra entregando paquetes','Auto blanco compacto',NULL),
(482,'Entrega rápida a transeúntes',2,NULL,NULL,NULL),
(483,'Puntos de venta recurrentes',NULL,'Hombre con gorra negra entregando paquetes','Auto blanco compacto','Ocasional'),
(484,'Venta de drogas en vía pública',3,'Persona vigilando en la esquina','Bicicleta','Cada noche'),
(485,'Distribución desde vehículo',2,'Persona vigilando en la esquina','Taxi','Ocasional'),
(486,'Distribución desde vehículo',2,'Persona vigilando en la esquina','Bicicleta','Fines de semana'),
(487,'Venta cerca de escuela',5,'Dos hombres jóvenes con mochilas','Motocicleta negra sin placas','Diario'),
(488,'Puntos de venta recurrentes',3,'Persona vigilando en la esquina','Taxi','Cada noche'),
(489,'Intercambio sospechoso de paquetes',2,'Pareja recibiendo dinero y entregando objetos pequeños','Camioneta gris',NULL),
(490,'Venta de drogas en vía pública',4,NULL,'Motocicleta negra sin placas',NULL),
(491,'Venta de drogas en vía pública',2,'Pareja recibiendo dinero y entregando objetos pequeños','Taxi','Fines de semana'),
(492,'Puntos de venta recurrentes',3,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Ocasional'),
(493,'Venta cerca de escuela',4,'Pareja recibiendo dinero y entregando objetos pequeños','Bicicleta','Varias veces por semana'),
(494,'Entrega rápida a transeúntes',3,'Dos hombres jóvenes con mochilas',NULL,'Varias veces por semana'),
(495,'Puntos de venta recurrentes',3,NULL,'Motocicleta negra sin placas',NULL),
(496,'Entrega rápida a transeúntes',NULL,'Dos hombres jóvenes con mochilas',NULL,NULL),
(497,'Entrega rápida a transeúntes',3,NULL,'Auto blanco compacto',NULL),
(498,'Venta de drogas en vía pública',4,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Cada noche'),
(499,'Distribución desde vehículo',2,'Dos hombres jóvenes con mochilas','Motocicleta negra sin placas','Cada noche'),
(500,'Intercambio sospechoso de paquetes',3,'Grupo de 3 personas intercambiando bolsitas',NULL,'Diario'),
(501,'Entrega rápida a transeúntes',2,'Pareja recibiendo dinero y entregando objetos pequeños','Bicicleta',NULL),
(502,'Distribución desde vehículo',2,NULL,'Motocicleta negra sin placas',NULL),
(503,'Distribución desde vehículo',5,'Hombre con gorra negra entregando paquetes','Bicicleta','Varias veces por semana'),
(504,'Intercambio sospechoso de paquetes',2,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Cada noche'),
(505,'Entrega rápida a transeúntes',NULL,NULL,'Bicicleta','Varias veces por semana'),
(506,'Venta de drogas en vía pública',3,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Varias veces por semana'),
(507,'Venta cerca de escuela',4,'Dos hombres jóvenes con mochilas','Camioneta gris',NULL),
(508,'Entrega rápida a transeúntes',4,NULL,'Camioneta gris','Varias veces por semana'),
(509,'Distribución desde vehículo',4,NULL,NULL,'Cada noche'),
(510,'Venta de drogas en vía pública',3,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Diario'),
(511,'Venta cerca de escuela',5,NULL,'Bicicleta','Ocasional'),
(512,'Entrega rápida a transeúntes',4,'Persona vigilando en la esquina',NULL,'Ocasional'),
(513,'Venta de drogas en vía pública',NULL,NULL,NULL,'Fines de semana'),
(514,'Puntos de venta recurrentes',4,NULL,NULL,'Cada noche'),
(515,'Intercambio sospechoso de paquetes',4,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,NULL),
(516,'Entrega rápida a transeúntes',5,'Hombre con gorra negra entregando paquetes','Motocicleta negra sin placas','Fines de semana'),
(517,'Venta de drogas en vía pública',5,NULL,NULL,NULL),
(518,'Venta de drogas en vía pública',4,'Hombre con gorra negra entregando paquetes','Auto blanco compacto','Varias veces por semana'),
(519,'Intercambio sospechoso de paquetes',NULL,'Grupo de 3 personas intercambiando bolsitas',NULL,NULL),
(520,'Distribución desde vehículo',4,NULL,'Auto blanco compacto',NULL),
(521,'Entrega rápida a transeúntes',2,'Persona vigilando en la esquina','Auto blanco compacto','Varias veces por semana'),
(522,'Entrega rápida a transeúntes',3,NULL,'Camioneta gris',NULL),
(523,'Puntos de venta recurrentes',NULL,'Grupo de 3 personas intercambiando bolsitas','Camioneta gris','Diario'),
(524,'Puntos de venta recurrentes',4,'Hombre con gorra negra entregando paquetes',NULL,'Cada noche'),
(525,'Distribución desde vehículo',2,NULL,NULL,'Diario'),
(526,'Venta de drogas en vía pública',3,NULL,'Camioneta gris',NULL),
(527,'Venta de drogas en vía pública',3,'Hombre con gorra negra entregando paquetes',NULL,'Ocasional'),
(528,'Distribución desde vehículo',3,NULL,'Camioneta gris','Varias veces por semana'),
(529,'Distribución desde vehículo',5,NULL,NULL,'Ocasional'),
(530,'Venta cerca de escuela',5,'Pareja recibiendo dinero y entregando objetos pequeños','Camioneta gris','Ocasional'),
(531,'Venta de drogas en vía pública',NULL,NULL,NULL,'Diario'),
(532,'Distribución desde vehículo',3,NULL,NULL,NULL),
(533,'Puntos de venta recurrentes',NULL,'Persona vigilando en la esquina','Bicicleta',NULL),
(534,'Entrega rápida a transeúntes',NULL,'Persona vigilando en la esquina',NULL,'Varias veces por semana'),
(535,'Venta cerca de escuela',NULL,'Dos hombres jóvenes con mochilas','Taxi','Cada noche'),
(536,'Venta de drogas en vía pública',5,'Dos hombres jóvenes con mochilas','Camioneta gris','Ocasional'),
(537,'Distribución desde vehículo',NULL,'Grupo de 3 personas intercambiando bolsitas',NULL,'Varias veces por semana'),
(538,'Venta cerca de escuela',NULL,'Persona vigilando en la esquina','Motocicleta negra sin placas','Varias veces por semana'),
(539,'Distribución desde vehículo',4,'Grupo de 3 personas intercambiando bolsitas',NULL,'Ocasional'),
(540,'Venta de drogas en vía pública',2,NULL,'Auto blanco compacto','Varias veces por semana'),
(541,'Venta de drogas en vía pública',2,'Hombre con gorra negra entregando paquetes','Taxi',NULL),
(542,'Puntos de venta recurrentes',4,'Pareja recibiendo dinero y entregando objetos pequeños',NULL,'Varias veces por semana'),
(543,'Distribución desde vehículo',3,'Dos hombres jóvenes con mochilas','Auto blanco compacto',NULL),
(544,'Puntos de venta recurrentes',3,'Grupo de 3 personas intercambiando bolsitas',NULL,'Varias veces por semana'),
(545,'Puntos de venta recurrentes',2,'Persona vigilando en la esquina','Motocicleta negra sin placas','Diario'),
(546,'Distribución desde vehículo',NULL,'Grupo de 3 personas intercambiando bolsitas','Taxi','Ocasional'),
(547,'Venta cerca de escuela',3,NULL,'Motocicleta negra sin placas','Varias veces por semana'),
(548,'Entrega rápida a transeúntes',2,'Dos hombres jóvenes con mochilas','Auto blanco compacto','Diario'),
(549,'Venta de drogas en vía pública',5,'Pareja recibiendo dinero y entregando objetos pequeños','Taxi','Cada noche'),
(550,'Distribución desde vehículo',2,'Persona vigilando en la esquina','Motocicleta negra sin placas','Fines de semana');