USE ReportesCiudadanos;
INSERT INTO ReporteGeneral (ReporteId,TipoSituacionReportada,PersonasElementosInvolucrados,FrecuenciaRecurrenciaHecho,ObservacionesAdicionales)
VALUES
(4401,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Varias veces por semana',NULL),
(4402,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4403,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4404,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.'),
(4405,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4406,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4407,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4408,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Diario',NULL),
(4409,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4410,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4411,'Uso indebido del espacio público','Vecinos de la zona','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4412,'Uso indebido del espacio público','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4413,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche',NULL),
(4414,'Actividad sospechosa reportada por vecinos',NULL,'Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4415,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4416,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4417,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana',NULL),
(4418,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Ocasional','La situación genera preocupación en la comunidad.'),
(4419,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Cada noche',NULL),
(4420,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Cada noche','La situación genera preocupación en la comunidad.'),
(4421,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Fines de semana',NULL),
(4422,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche',NULL),
(4423,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4424,'Grupo de personas alterando el orden','Personas desconocidas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4425,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4426,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4427,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4428,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4429,'Actividad sospechosa reportada por vecinos',NULL,'Cada noche',NULL),
(4430,'Ruido excesivo en la vía pública',NULL,'Fines de semana',NULL),
(4431,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4432,'Actividad sospechosa reportada por vecinos',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4433,'Grupo de personas alterando el orden',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4434,'Ruido excesivo en la vía pública','Vecinos de la zona','Ocasional','La situación genera preocupación en la comunidad.'),
(4435,'Comportamiento sospechoso en zona residencial',NULL,'Diario',NULL),
(4436,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4437,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4438,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche',NULL),
(4439,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4440,'Uso indebido del espacio público','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.'),
(4441,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4442,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Varias veces por semana',NULL),
(4443,'Grupo de personas alterando el orden','Vecinos de la zona','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4444,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Fines de semana',NULL),
(4445,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4446,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4447,'Uso indebido del espacio público','Personas desconocidas','Diario','La situación genera preocupación en la comunidad.'),
(4448,'Grupo de personas alterando el orden','Vecinos de la zona','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4449,'Grupo de personas alterando el orden','Personas desconocidas','Varias veces por semana',NULL),
(4450,'Actividad sospechosa reportada por vecinos',NULL,'Ocasional',NULL),
(4451,'Grupo de personas alterando el orden','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4452,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4453,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Diario','La situación genera preocupación en la comunidad.'),
(4454,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4455,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Fines de semana',NULL),
(4456,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4457,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4458,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4459,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4460,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Fines de semana',NULL),
(4461,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Diario',NULL),
(4462,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4463,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4464,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4465,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4466,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4467,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Diario',NULL),
(4468,'Ruido excesivo en la vía pública',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4469,'Actividad sospechosa reportada por vecinos',NULL,'Ocasional','La situación genera preocupación en la comunidad.'),
(4470,'Grupo de personas alterando el orden','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4471,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4472,'Comportamiento sospechoso en zona residencial',NULL,'Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4473,'Grupo de personas alterando el orden','Personas desconocidas','Ocasional',NULL),
(4474,'Ruido excesivo en la vía pública','Personas desconocidas','Fines de semana',NULL),
(4475,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4476,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4477,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Diario','La situación genera preocupación en la comunidad.'),
(4478,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4479,'Actividad sospechosa reportada por vecinos',NULL,'Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4480,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4481,'Comportamiento sospechoso en zona residencial',NULL,'Fines de semana','La situación genera preocupación en la comunidad.'),
(4482,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4483,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4484,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4485,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4486,'Actividad sospechosa reportada por vecinos',NULL,'Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4487,'Uso indebido del espacio público','Vecinos de la zona','Cada noche',NULL),
(4488,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Ocasional',NULL),
(4489,'Grupo de personas alterando el orden',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4490,'Comportamiento sospechoso en zona residencial',NULL,'Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4491,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Diario',NULL),
(4492,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4493,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4494,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4495,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4496,'Uso indebido del espacio público',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4497,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4498,'Uso indebido del espacio público',NULL,'Fines de semana',NULL),
(4499,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4500,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Diario',NULL),
(4501,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4502,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4503,'Grupo de personas alterando el orden','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4504,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4505,'Uso indebido del espacio público',NULL,'Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4506,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4507,'Uso indebido del espacio público','Personas desconocidas','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4508,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4509,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Diario',NULL),
(4510,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4511,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4512,'Uso indebido del espacio público','Vecinos de la zona','Ocasional','La situación genera preocupación en la comunidad.'),
(4513,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4514,'Comportamiento sospechoso en zona residencial',NULL,'Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4515,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4516,'Grupo de personas alterando el orden',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4517,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4518,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4519,'Grupo de personas alterando el orden',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4520,'Ruido excesivo en la vía pública',NULL,'Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4521,'Uso indebido del espacio público',NULL,'Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4522,'Uso indebido del espacio público','Personas desconocidas','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4523,'Ruido excesivo en la vía pública','Vecinos de la zona','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4524,'Uso indebido del espacio público','Vecinos de la zona','Fines de semana',NULL),
(4525,'Comportamiento sospechoso en zona residencial',NULL,'Fines de semana',NULL),
(4526,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4527,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4528,'Ruido excesivo en la vía pública','Personas desconocidas','Ocasional','La situación genera preocupación en la comunidad.'),
(4529,'Grupo de personas alterando el orden',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4530,'Ruido excesivo en la vía pública',NULL,'Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4531,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana',NULL),
(4532,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario',NULL),
(4533,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Cada noche',NULL),
(4534,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4535,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Cada noche',NULL),
(4536,'Ruido excesivo en la vía pública',NULL,'Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4537,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4538,'Uso indebido del espacio público',NULL,'Cada noche',NULL),
(4539,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Cada noche',NULL),
(4540,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4541,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Varias veces por semana',NULL),
(4542,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4543,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4544,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4545,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4546,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4547,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4548,'Uso indebido del espacio público','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4549,'Ruido excesivo en la vía pública','Personas desconocidas','Diario',NULL),
(4550,'Grupo de personas alterando el orden',NULL,'Fines de semana',NULL),
(4551,'Ruido excesivo en la vía pública',NULL,'Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4552,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4553,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4554,'Actividad sospechosa reportada por vecinos',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4555,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Cada noche','La situación genera preocupación en la comunidad.'),
(4556,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4557,'Grupo de personas alterando el orden',NULL,'Ocasional','La situación genera preocupación en la comunidad.'),
(4558,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4559,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4560,'Ruido excesivo en la vía pública','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4561,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4562,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4563,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Diario',NULL),
(4564,'Grupo de personas alterando el orden',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4565,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Diario','La situación genera preocupación en la comunidad.'),
(4566,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4567,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Diario',NULL),
(4568,'Comportamiento sospechoso en zona residencial',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4569,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4570,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4571,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Fines de semana',NULL),
(4572,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Cada noche',NULL),
(4573,'Grupo de personas alterando el orden','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4574,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4575,'Actividad sospechosa reportada por vecinos',NULL,'Fines de semana',NULL),
(4576,'Uso indebido del espacio público','Personas desconocidas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4577,'Grupo de personas alterando el orden','Personas desconocidas','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4578,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4579,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4580,'Ruido excesivo en la vía pública',NULL,'Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4581,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4582,'Grupo de personas alterando el orden',NULL,'Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4583,'Uso indebido del espacio público','Personas desconocidas','Diario','La situación genera preocupación en la comunidad.'),
(4584,'Grupo de personas alterando el orden','Vecinos de la zona','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4585,'Uso indebido del espacio público','Vecinos de la zona','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4586,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4587,'Actividad sospechosa reportada por vecinos',NULL,'Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4588,'Grupo de personas alterando el orden',NULL,'Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4589,'Grupo de personas alterando el orden','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4590,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana',NULL),
(4591,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4592,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Diario','La situación genera preocupación en la comunidad.'),
(4593,'Comportamiento sospechoso en zona residencial',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4594,'Uso indebido del espacio público','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4595,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4596,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4597,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Diario',NULL),
(4598,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4599,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4600,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Fines de semana',NULL),
(4601,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4602,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4603,'Uso indebido del espacio público','Personas desconocidas','Ocasional',NULL),
(4604,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Cada noche',NULL),
(4605,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4606,'Uso indebido del espacio público','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4607,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4608,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4609,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana',NULL),
(4610,'Ruido excesivo en la vía pública','Personas desconocidas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4611,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4612,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche',NULL),
(4613,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.'),
(4614,'Uso indebido del espacio público','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4615,'Grupo de personas alterando el orden','Personas desconocidas','Varias veces por semana',NULL),
(4616,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4617,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4618,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional','La situación genera preocupación en la comunidad.'),
(4619,'Uso indebido del espacio público','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4620,'Uso indebido del espacio público','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4621,'Uso indebido del espacio público','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4622,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche',NULL),
(4623,'Ruido excesivo en la vía pública',NULL,'Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4624,'Grupo de personas alterando el orden',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4625,'Ruido excesivo en la vía pública','Personas desconocidas','Ocasional',NULL),
(4626,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4627,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4628,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4629,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Ocasional',NULL),
(4630,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4631,'Actividad sospechosa reportada por vecinos',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4632,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4633,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4634,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional','La situación genera preocupación en la comunidad.'),
(4635,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4636,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4637,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4638,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4639,'Uso indebido del espacio público','Vecinos de la zona','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4640,'Uso indebido del espacio público','Personas desconocidas','Ocasional',NULL),
(4641,'Actividad sospechosa reportada por vecinos',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4642,'Comportamiento sospechoso en zona residencial',NULL,'Diario',NULL),
(4643,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4644,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4645,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario',NULL),
(4646,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Fines de semana',NULL),
(4647,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Cada noche',NULL),
(4648,'Grupo de personas alterando el orden','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4649,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.'),
(4650,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4651,'Ruido excesivo en la vía pública',NULL,'Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4652,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4653,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4654,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4655,'Ruido excesivo en la vía pública','Personas desconocidas','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4656,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Ocasional','La situación genera preocupación en la comunidad.'),
(4657,'Ruido excesivo en la vía pública','Vecinos de la zona','Ocasional','La situación genera preocupación en la comunidad.'),
(4658,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Ocasional',NULL),
(4659,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4660,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario',NULL),
(4661,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana',NULL),
(4662,'Grupo de personas alterando el orden','Vecinos de la zona','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4663,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4664,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional',NULL),
(4665,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4666,'Actividad sospechosa reportada por vecinos',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4667,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana',NULL),
(4668,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4669,'Grupo de personas alterando el orden',NULL,'Varias veces por semana',NULL),
(4670,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4671,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4672,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.'),
(4673,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4674,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4675,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4676,'Uso indebido del espacio público','Personas desconocidas','Fines de semana',NULL),
(4677,'Grupo de personas alterando el orden','Vecinos de la zona','Diario',NULL),
(4678,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4679,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4680,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4681,'Ruido excesivo en la vía pública','Vecinos de la zona','Ocasional',NULL),
(4682,'Grupo de personas alterando el orden',NULL,'Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4683,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4684,'Ruido excesivo en la vía pública','Personas desconocidas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4685,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4686,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Fines de semana',NULL),
(4687,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4688,'Ruido excesivo en la vía pública','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4689,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4690,'Ruido excesivo en la vía pública',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4691,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana',NULL),
(4692,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4693,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4694,'Grupo de personas alterando el orden','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4695,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana',NULL),
(4696,'Grupo de personas alterando el orden','Vecinos de la zona','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4697,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4698,'Uso indebido del espacio público',NULL,'Diario',NULL),
(4699,'Uso indebido del espacio público','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4700,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Diario',NULL),
(4701,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana',NULL),
(4702,'Ruido excesivo en la vía pública','Vecinos de la zona','Fines de semana',NULL),
(4703,'Grupo de personas alterando el orden',NULL,'Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4704,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4705,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Fines de semana','La situación genera preocupación en la comunidad.'),
(4706,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4707,'Uso indebido del espacio público',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4708,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Cada noche',NULL),
(4709,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4710,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Cada noche','La situación genera preocupación en la comunidad.'),
(4711,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4712,'Uso indebido del espacio público','Personas desconocidas','Cada noche',NULL),
(4713,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4714,'Grupo de personas alterando el orden',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4715,'Ruido excesivo en la vía pública','Personas desconocidas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4716,'Uso indebido del espacio público','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4717,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4718,'Grupo de personas alterando el orden',NULL,'Ocasional','La situación genera preocupación en la comunidad.'),
(4719,'Actividad sospechosa reportada por vecinos',NULL,'Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4720,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4721,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4722,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Cada noche',NULL),
(4723,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4724,'Ruido excesivo en la vía pública',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4725,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4726,'Comportamiento sospechoso en zona residencial',NULL,'Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4727,'Ruido excesivo en la vía pública','Personas desconocidas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4728,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4729,'Actividad sospechosa reportada por vecinos',NULL,'Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4730,'Uso indebido del espacio público','Vecinos de la zona','Cada noche',NULL),
(4731,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4732,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4733,'Ruido excesivo en la vía pública','Personas desconocidas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4734,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4735,'Grupo de personas alterando el orden',NULL,'Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4736,'Actividad sospechosa reportada por vecinos',NULL,'Ocasional',NULL),
(4737,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4738,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4739,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4740,'Uso indebido del espacio público','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4741,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4742,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4743,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Diario','La situación genera preocupación en la comunidad.'),
(4744,'Ruido excesivo en la vía pública','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4745,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4746,'Actividad sospechosa reportada por vecinos',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4747,'Uso indebido del espacio público','Personas desconocidas','Ocasional','La situación genera preocupación en la comunidad.'),
(4748,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Ocasional',NULL),
(4749,'Uso indebido del espacio público','Personas desconocidas','Varias veces por semana',NULL),
(4750,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4751,'Uso indebido del espacio público','Personas desconocidas','Ocasional',NULL),
(4752,'Uso indebido del espacio público','Personas desconocidas','Diario','La situación genera preocupación en la comunidad.'),
(4753,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4754,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4755,'Actividad sospechosa reportada por vecinos',NULL,'Ocasional','La situación genera preocupación en la comunidad.'),
(4756,'Uso indebido del espacio público',NULL,'Fines de semana','La situación genera preocupación en la comunidad.'),
(4757,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana',NULL),
(4758,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4759,'Comportamiento sospechoso en zona residencial',NULL,'Fines de semana','La situación genera preocupación en la comunidad.'),
(4760,'Uso indebido del espacio público','Vecinos de la zona','Ocasional','La situación genera preocupación en la comunidad.'),
(4761,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4762,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4763,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4764,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Fines de semana',NULL),
(4765,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4766,'Ruido excesivo en la vía pública',NULL,'Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4767,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Cada noche','La situación genera preocupación en la comunidad.'),
(4768,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4769,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Cada noche',NULL),
(4770,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4771,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4772,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4773,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4774,'Comportamiento sospechoso en zona residencial',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4775,'Uso indebido del espacio público','Personas desconocidas','Diario','La situación genera preocupación en la comunidad.'),
(4776,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4777,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4778,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4779,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Fines de semana',NULL),
(4780,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Cada noche','La situación genera preocupación en la comunidad.'),
(4781,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Cada noche',NULL),
(4782,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4783,'Comportamiento sospechoso en zona residencial',NULL,'Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4784,'Uso indebido del espacio público','Vecinos de la zona','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4785,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4786,'Uso indebido del espacio público','Personas desconocidas','Cada noche','La situación genera preocupación en la comunidad.'),
(4787,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4788,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4789,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4790,'Ruido excesivo en la vía pública','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4791,'Ruido excesivo en la vía pública','Personas desconocidas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4792,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Diario',NULL),
(4793,'Actividad sospechosa reportada por vecinos',NULL,'Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4794,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4795,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4796,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4797,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4798,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4799,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4800,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4801,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Fines de semana','La situación genera preocupación en la comunidad.'),
(4802,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4803,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Diario',NULL),
(4804,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4805,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4806,'Ruido excesivo en la vía pública','Personas desconocidas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4807,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4808,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4809,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4810,'Grupo de personas alterando el orden','Vecinos de la zona','Ocasional','La situación genera preocupación en la comunidad.'),
(4811,'Uso indebido del espacio público','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4812,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Cada noche','La situación genera preocupación en la comunidad.'),
(4813,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4814,'Actividad sospechosa reportada por vecinos',NULL,'Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4815,'Ruido excesivo en la vía pública',NULL,'Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4816,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4817,'Ruido excesivo en la vía pública','Personas desconocidas','Ocasional',NULL),
(4818,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4819,'Uso indebido del espacio público','Personas desconocidas','Diario',NULL),
(4820,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4821,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4822,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche',NULL),
(4823,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4824,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4825,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana',NULL),
(4826,'Actividad sospechosa reportada por vecinos',NULL,'Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4827,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4828,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Diario','La situación genera preocupación en la comunidad.'),
(4829,'Ruido excesivo en la vía pública',NULL,'Diario',NULL),
(4830,'Grupo de personas alterando el orden','Personas desconocidas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4831,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Ocasional',NULL),
(4832,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4833,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4834,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4835,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario',NULL),
(4836,'Comportamiento sospechoso en zona residencial',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4837,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4838,'Ruido excesivo en la vía pública',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4839,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4840,'Uso indebido del espacio público',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4841,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4842,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Diario','La situación genera preocupación en la comunidad.'),
(4843,'Ruido excesivo en la vía pública','Personas desconocidas','Ocasional','La situación genera preocupación en la comunidad.'),
(4844,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4845,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4846,'Uso indebido del espacio público','Personas desconocidas','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4847,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Fines de semana','La situación genera preocupación en la comunidad.'),
(4848,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4849,'Ruido excesivo en la vía pública','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4850,'Comportamiento sospechoso en zona residencial',NULL,'Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4851,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4852,'Ruido excesivo en la vía pública',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4853,'Uso indebido del espacio público','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4854,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4855,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4856,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4857,'Actividad sospechosa reportada por vecinos',NULL,'Fines de semana',NULL),
(4858,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4859,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4860,'Uso indebido del espacio público','Personas desconocidas','Cada noche','La situación genera preocupación en la comunidad.'),
(4861,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Diario','La situación genera preocupación en la comunidad.'),
(4862,'Grupo de personas alterando el orden','Personas desconocidas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4863,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4864,'Actividad sospechosa reportada por vecinos',NULL,'Fines de semana',NULL),
(4865,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Diario','La situación genera preocupación en la comunidad.'),
(4866,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4867,'Grupo de personas alterando el orden','Personas desconocidas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4868,'Grupo de personas alterando el orden',NULL,'Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4869,'Actividad sospechosa reportada por vecinos',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4870,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4871,'Comportamiento sospechoso en zona residencial',NULL,'Diario',NULL),
(4872,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Fines de semana',NULL),
(4873,'Ruido excesivo en la vía pública',NULL,'Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4874,'Grupo de personas alterando el orden','Personas desconocidas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4875,'Ruido excesivo en la vía pública','Vecinos de la zona','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4876,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4877,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4878,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4879,'Uso indebido del espacio público',NULL,'Ocasional','La situación genera preocupación en la comunidad.'),
(4880,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4881,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Varias veces por semana',NULL),
(4882,'Uso indebido del espacio público','Personas desconocidas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4883,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.'),
(4884,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4885,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4886,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Cada noche',NULL),
(4887,'Uso indebido del espacio público',NULL,'Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4888,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4889,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4890,'Uso indebido del espacio público','Vecinos de la zona','Fines de semana','La situación genera preocupación en la comunidad.'),
(4891,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4892,'Uso indebido del espacio público','Personas desconocidas','Varias veces por semana',NULL),
(4893,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4894,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4895,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4896,'Ruido excesivo en la vía pública',NULL,'Diario','La situación genera preocupación en la comunidad.'),
(4897,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4898,'Uso indebido del espacio público','Personas desconocidas','Ocasional','Vecinos mencionan que ocurre con frecuencia.'),
(4899,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4900,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4901,'Actividad sospechosa reportada por vecinos',NULL,'Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4902,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Cada noche','La situación genera preocupación en la comunidad.'),
(4903,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4904,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4905,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Ocasional','La situación genera preocupación en la comunidad.'),
(4906,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Cada noche',NULL),
(4907,'Uso indebido del espacio público','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4908,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Diario',NULL),
(4909,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4910,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Cada noche','La situación genera preocupación en la comunidad.'),
(4911,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional','La situación genera preocupación en la comunidad.'),
(4912,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4913,'Comportamiento sospechoso en zona residencial',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4914,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4915,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4916,'Uso indebido del espacio público',NULL,'Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4917,'Uso indebido del espacio público',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4918,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Fines de semana',NULL),
(4919,'Uso indebido del espacio público','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4920,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4921,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4922,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Cada noche',NULL),
(4923,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Ocasional','La situación genera preocupación en la comunidad.'),
(4924,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4925,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4926,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4927,'Uso indebido del espacio público','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4928,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4929,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Fines de semana','La situación genera preocupación en la comunidad.'),
(4930,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Diario',NULL),
(4931,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Fines de semana',NULL),
(4932,'Actividad sospechosa reportada por vecinos',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4933,'Grupo de personas alterando el orden',NULL,'Cada noche','La situación genera preocupación en la comunidad.'),
(4934,'Ruido excesivo en la vía pública',NULL,'Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4935,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4936,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Cada noche','La situación genera preocupación en la comunidad.'),
(4937,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4938,'Ruido excesivo en la vía pública',NULL,'Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4939,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4940,'Comportamiento sospechoso en zona residencial',NULL,'Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4941,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4942,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Diario',NULL),
(4943,'Ruido excesivo en la vía pública','Vecinos de la zona','Ocasional','La situación genera preocupación en la comunidad.'),
(4944,'Grupo de personas alterando el orden','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4945,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Fines de semana',NULL),
(4946,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Cada noche',NULL),
(4947,'Ruido excesivo en la vía pública','Vecinos de la zona','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4948,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4949,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4950,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Diario','Se solicita revisión por autoridades correspondientes.'),
(4951,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4952,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.'),
(4953,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4954,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Fines de semana','La situación genera preocupación en la comunidad.'),
(4955,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Cada noche','La situación genera preocupación en la comunidad.'),
(4956,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4957,'Uso indebido del espacio público','Personas desconocidas','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4958,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche','Vecinos mencionan que ocurre con frecuencia.'),
(4959,'Comportamiento sospechoso en zona residencial','Personas desconocidas','Cada noche','La situación genera preocupación en la comunidad.'),
(4960,'Uso indebido del espacio público',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4961,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4962,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana',NULL),
(4963,'Actividad sospechosa reportada por vecinos','Jóvenes reunidos en la vía pública','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4964,'Ruido excesivo en la vía pública',NULL,'Ocasional','La situación genera preocupación en la comunidad.'),
(4965,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Ocasional',NULL),
(4966,'Ruido excesivo en la vía pública','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4967,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4968,'Grupo de personas alterando el orden','Grupo de 3 a 5 personas','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4969,'Grupo de personas alterando el orden','Personas desconocidas','Diario','Se solicita revisión por autoridades correspondientes.'),
(4970,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4971,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4972,'Ruido excesivo en la vía pública','Personas desconocidas','Diario',NULL),
(4973,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Ocasional','Se solicita revisión por autoridades correspondientes.'),
(4974,'Comportamiento sospechoso en zona residencial','Grupo de 3 a 5 personas','Varias veces por semana',NULL),
(4975,'Grupo de personas alterando el orden','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4976,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4977,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Fines de semana',NULL),
(4978,'Uso indebido del espacio público','Vecinos de la zona','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4979,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Diario',NULL),
(4980,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Cada noche','Se solicita revisión por autoridades correspondientes.'),
(4981,'Ruido excesivo en la vía pública','Vecinos de la zona','Diario','Se solicita revisión por autoridades correspondientes.'),
(4982,'Ruido excesivo en la vía pública',NULL,'Diario','Se solicita revisión por autoridades correspondientes.'),
(4983,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Varias veces por semana',NULL),
(4984,'Uso indebido del espacio público',NULL,'Fines de semana','Vecinos mencionan que ocurre con frecuencia.'),
(4985,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4986,'Comportamiento sospechoso en zona residencial',NULL,'Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4987,'Ruido excesivo en la vía pública','Personas desconocidas','Fines de semana','Se solicita revisión por autoridades correspondientes.'),
(4988,'Uso indebido del espacio público','Grupo de 3 a 5 personas','Ocasional','La situación genera preocupación en la comunidad.'),
(4989,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(4990,'Actividad sospechosa reportada por vecinos','Vecinos de la zona','Varias veces por semana',NULL),
(4991,'Ruido excesivo en la vía pública','Vecinos de la zona','Cada noche',NULL),
(4992,'Grupo de personas alterando el orden','Jóvenes reunidos en la vía pública','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4993,'Comportamiento sospechoso en zona residencial','Vecinos de la zona','Varias veces por semana','Se solicita revisión por autoridades correspondientes.'),
(4994,'Uso indebido del espacio público','Jóvenes reunidos en la vía pública','Diario','Vecinos mencionan que ocurre con frecuencia.'),
(4995,'Actividad sospechosa reportada por vecinos','Personas desconocidas','Diario','La situación genera preocupación en la comunidad.'),
(4996,'Ruido excesivo en la vía pública','Jóvenes reunidos en la vía pública','Varias veces por semana','La situación genera preocupación en la comunidad.'),
(4997,'Actividad sospechosa reportada por vecinos','Grupo de 3 a 5 personas','Cada noche','La situación genera preocupación en la comunidad.'),
(4998,'Comportamiento sospechoso en zona residencial','Jóvenes reunidos en la vía pública','Ocasional',NULL),
(4999,'Grupo de personas alterando el orden','Personas desconocidas','Varias veces por semana','Vecinos mencionan que ocurre con frecuencia.'),
(5000,'Grupo de personas alterando el orden','Vecinos de la zona','Cada noche','La situación genera preocupación en la comunidad.');