USE ReportesCiudadanos;
INSERT INTO ReporteCorrupcion (ReporteId,TipoFaltaReportada,DependenciaInstitucionInvolucrada,NombreServidorPublico,CargoServidorPublico)
VALUES
(1,'Negativa de servicio','Alcaldía Álvaro Obregón',NULL,NULL),
(2,'Negativa de servicio','Sistema de Aguas de la CDMX',NULL,'Coordinador'),
(3,'Omisión de funciones','Secretaría de Movilidad',NULL,'Analista'),
(4,'Soborno','Sistema de Aguas de la CDMX','Lucía Vargas',NULL),
(5,'Soborno','Sistema de Aguas de la CDMX',NULL,'Analista'),
(6,'Tráfico de influencias','Secretaría de Obras',NULL,NULL),
(7,'Tráfico de influencias','Alcaldía Álvaro Obregón','José Ramírez',NULL),
(8,'Uso indebido de recursos','Sistema de Aguas de la CDMX',NULL,'Inspector'),
(9,'Abuso de autoridad','Instituto de Verificación Administrativa','Carlos López','Director'),
(10,'Tráfico de influencias','Sistema de Aguas de la CDMX',NULL,'Director'),
(11,'Tráfico de influencias','Sistema de Aguas de la CDMX','Ricardo Vega','Director'),
(12,'Negativa de servicio','Alcaldía Álvaro Obregón',NULL,'Jefe de área'),
(13,'Abuso de autoridad','Alcaldía Álvaro Obregón',NULL,NULL),
(14,'Tráfico de influencias','Secretaría de Obras','Laura Rojas','Inspector'),
(15,'Tráfico de influencias','Instituto de Verificación Administrativa','Carlos López','Coordinador'),
(16,'Negativa de servicio','Alcaldía Álvaro Obregón','Miguel Castillo',NULL),
(17,'Uso indebido de recursos','Alcaldía Álvaro Obregón','José Ramírez',NULL),
(18,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Ricardo Vega','Jefe de área'),
(19,'Uso indebido de recursos','Sistema de Aguas de la CDMX',NULL,NULL),
(20,'Uso indebido de recursos','Instituto de Verificación Administrativa','Lucía Vargas','Coordinador'),
(21,'Tráfico de influencias','Secretaría de Seguridad Ciudadana','Paola Moreno',NULL),
(22,'Tráfico de influencias','Secretaría de Obras',NULL,'Coordinador'),
(23,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,NULL),
(24,'Soborno','Secretaría de Seguridad Ciudadana',NULL,'Supervisor'),
(25,'Soborno','Sistema de Aguas de la CDMX','Paola Moreno','Analista'),
(26,'Soborno','Secretaría de Obras',NULL,'Jefe de área'),
(27,'Soborno','Sistema de Aguas de la CDMX',NULL,'Jefe de área'),
(28,'Tráfico de influencias','Secretaría de Obras',NULL,NULL),
(29,'Abuso de autoridad','Alcaldía Azcapotzalco',NULL,'Analista'),
(30,'Omisión de funciones','Secretaría de Seguridad Ciudadana','Ricardo Vega','Coordinador'),
(31,'Negativa de servicio','Secretaría de Movilidad','Luis Méndez',NULL),
(32,'Negativa de servicio','Sistema de Aguas de la CDMX',NULL,'Analista'),
(33,'Tráfico de influencias','Instituto de Verificación Administrativa','Pedro Sánchez','Inspector'),
(34,'Uso indebido de recursos','Alcaldía Benito Juárez',NULL,NULL),
(35,'Soborno','Instituto de Verificación Administrativa','Carlos López',NULL),
(36,'Abuso de autoridad','Secretaría de Obras',NULL,'Coordinador'),
(37,'Negativa de servicio','Sistema de Aguas de la CDMX','Daniela Cruz',NULL),
(38,'Uso indebido de recursos','Instituto de Verificación Administrativa',NULL,'Inspector'),
(39,'Soborno','Secretaría de Obras','María Hernández','Supervisor'),
(40,'Abuso de autoridad','Secretaría de Movilidad','José Ramírez',NULL),
(41,'Tráfico de influencias','Secretaría de Obras',NULL,NULL),
(42,'Omisión de funciones','Alcaldía Benito Juárez',NULL,'Inspector'),
(43,'Tráfico de influencias','Alcaldía Benito Juárez','Miguel Castillo',NULL),
(44,'Abuso de autoridad','Instituto de Verificación Administrativa',NULL,NULL),
(45,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Luis Méndez',NULL),
(46,'Soborno','Secretaría de Seguridad Ciudadana',NULL,'Coordinador'),
(47,'Tráfico de influencias','Sistema de Aguas de la CDMX',NULL,'Inspector'),
(48,'Omisión de funciones','Alcaldía Coyoacán',NULL,'Jefe de área'),
(49,'Abuso de autoridad','Sistema de Aguas de la CDMX',NULL,'Analista'),
(50,'Abuso de autoridad','Secretaría de Movilidad','Daniela Cruz','Coordinador'),
(51,'Negativa de servicio','Alcaldía Coyoacán',NULL,NULL),
(52,'Tráfico de influencias','Secretaría de Movilidad','Daniela Cruz','Analista'),
(53,'Tráfico de influencias','Secretaría de Movilidad',NULL,NULL),
(54,'Omisión de funciones','Secretaría de Obras',NULL,'Analista'),
(55,'Tráfico de influencias','Secretaría de Obras','Miguel Castillo','Analista'),
(56,'Uso indebido de recursos','Secretaría de Obras','María Hernández','Analista'),
(57,'Uso indebido de recursos','Secretaría de Obras','Paola Moreno',NULL),
(58,'Soborno','Secretaría de Obras','Lucía Vargas','Director'),
(59,'Uso indebido de recursos','Sistema de Aguas de la CDMX',NULL,NULL),
(60,'Negativa de servicio','Secretaría de Obras',NULL,'Supervisor'),
(61,'Soborno','Alcaldía Coyoacán',NULL,NULL),
(62,'Omisión de funciones','Secretaría de Seguridad Ciudadana',NULL,NULL),
(63,'Soborno','Secretaría de Obras','Lucía Vargas','Analista'),
(64,'Negativa de servicio','Alcaldía Cuajimalpa de Morelos',NULL,'Jefe de área'),
(65,'Omisión de funciones','Sistema de Aguas de la CDMX',NULL,'Inspector'),
(66,'Negativa de servicio','Sistema de Aguas de la CDMX',NULL,NULL),
(67,'Uso indebido de recursos','Instituto de Verificación Administrativa','Ana Torres',NULL),
(68,'Negativa de servicio','Alcaldía Cuauhtémoc',NULL,'Supervisor'),
(69,'Tráfico de influencias','Sistema de Aguas de la CDMX',NULL,'Director'),
(70,'Tráfico de influencias','Secretaría de Seguridad Ciudadana','Pedro Sánchez','Coordinador'),
(71,'Tráfico de influencias','Alcaldía Cuauhtémoc','Daniela Cruz','Coordinador'),
(72,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana','Miguel Castillo',NULL),
(73,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Laura Rojas',NULL),
(74,'Tráfico de influencias','Instituto de Verificación Administrativa','Ricardo Vega',NULL),
(75,'Omisión de funciones','Secretaría de Seguridad Ciudadana',NULL,NULL),
(76,'Tráfico de influencias','Secretaría de Obras','José Ramírez',NULL),
(77,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana','Luis Méndez',NULL),
(78,'Tráfico de influencias','Secretaría de Obras',NULL,'Coordinador'),
(79,'Soborno','Alcaldía Cuauhtémoc',NULL,NULL),
(80,'Omisión de funciones','Secretaría de Seguridad Ciudadana','Paola Moreno','Jefe de área'),
(81,'Uso indebido de recursos','Instituto de Verificación Administrativa',NULL,NULL),
(82,'Omisión de funciones','Instituto de Verificación Administrativa','Pedro Sánchez','Analista'),
(83,'Omisión de funciones','Instituto de Verificación Administrativa',NULL,'Jefe de área'),
(84,'Omisión de funciones','Instituto de Verificación Administrativa','Ricardo Vega','Analista'),
(85,'Negativa de servicio','Secretaría de Movilidad',NULL,NULL),
(86,'Negativa de servicio','Secretaría de Seguridad Ciudadana','José Ramírez','Coordinador'),
(87,'Uso indebido de recursos','Secretaría de Movilidad',NULL,NULL),
(88,'Uso indebido de recursos','Alcaldía Gustavo A. Madero','Carlos López',NULL),
(89,'Tráfico de influencias','Sistema de Aguas de la CDMX','Miguel Castillo',NULL),
(90,'Soborno','Instituto de Verificación Administrativa','Ricardo Vega','Supervisor'),
(91,'Omisión de funciones','Instituto de Verificación Administrativa','Miguel Castillo',NULL),
(92,'Abuso de autoridad','Sistema de Aguas de la CDMX','Daniela Cruz','Director'),
(93,'Omisión de funciones','Secretaría de Obras','Miguel Castillo','Coordinador'),
(94,'Negativa de servicio','Secretaría de Obras','Ricardo Vega','Inspector'),
(95,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Laura Rojas',NULL),
(96,'Negativa de servicio','Instituto de Verificación Administrativa',NULL,'Director'),
(97,'Uso indebido de recursos','Secretaría de Obras','Pedro Sánchez','Analista'),
(98,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','José Ramírez','Analista'),
(99,'Omisión de funciones','Instituto de Verificación Administrativa','Daniela Cruz',NULL),
(100,'Abuso de autoridad','Sistema de Aguas de la CDMX','Luis Méndez',NULL),
(101,'Tráfico de influencias','Secretaría de Movilidad','Pedro Sánchez','Jefe de área'),
(102,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,'Supervisor'),
(103,'Negativa de servicio','Alcaldía Gustavo A. Madero','Ricardo Vega','Jefe de área'),
(104,'Uso indebido de recursos','Alcaldía Gustavo A. Madero','Miguel Castillo',NULL),
(105,'Negativa de servicio','Instituto de Verificación Administrativa',NULL,NULL),
(106,'Negativa de servicio','Secretaría de Seguridad Ciudadana',NULL,'Coordinador'),
(107,'Uso indebido de recursos','Sistema de Aguas de la CDMX','Laura Rojas','Analista'),
(108,'Abuso de autoridad','Alcaldía Gustavo A. Madero',NULL,'Analista'),
(109,'Negativa de servicio','Secretaría de Movilidad','Carlos López','Director'),
(110,'Tráfico de influencias','Secretaría de Seguridad Ciudadana',NULL,NULL),
(111,'Abuso de autoridad','Secretaría de Obras','Luis Méndez','Analista'),
(112,'Soborno','Sistema de Aguas de la CDMX',NULL,'Jefe de área'),
(113,'Tráfico de influencias','Secretaría de Obras','Ricardo Vega','Jefe de área'),
(114,'Negativa de servicio','Secretaría de Movilidad','Lucía Vargas',NULL),
(115,'Omisión de funciones','Secretaría de Movilidad',NULL,'Jefe de área'),
(116,'Soborno','Instituto de Verificación Administrativa','Paola Moreno',NULL),
(117,'Omisión de funciones','Secretaría de Movilidad','María Hernández',NULL),
(118,'Omisión de funciones','Secretaría de Obras','Ricardo Vega','Coordinador'),
(119,'Negativa de servicio','Secretaría de Seguridad Ciudadana',NULL,NULL),
(120,'Abuso de autoridad','Secretaría de Movilidad','Daniela Cruz','Supervisor'),
(121,'Omisión de funciones','Sistema de Aguas de la CDMX',NULL,'Inspector'),
(122,'Negativa de servicio','Secretaría de Seguridad Ciudadana',NULL,'Director'),
(123,'Tráfico de influencias','Sistema de Aguas de la CDMX','Laura Rojas','Coordinador'),
(124,'Negativa de servicio','Secretaría de Obras','Paola Moreno',NULL),
(125,'Omisión de funciones','Alcaldía Iztacalco','María Hernández','Coordinador'),
(126,'Negativa de servicio','Sistema de Aguas de la CDMX','Carlos López',NULL),
(127,'Abuso de autoridad','Secretaría de Obras','Carlos López','Supervisor'),
(128,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Inspector'),
(129,'Omisión de funciones','Alcaldía Iztapalapa','Paola Moreno','Director'),
(130,'Soborno','Instituto de Verificación Administrativa','José Ramírez',NULL),
(131,'Negativa de servicio','Alcaldía Iztapalapa',NULL,NULL),
(132,'Omisión de funciones','Alcaldía Iztapalapa',NULL,'Jefe de área'),
(133,'Negativa de servicio','Instituto de Verificación Administrativa','Pedro Sánchez',NULL),
(134,'Negativa de servicio','Alcaldía Iztapalapa',NULL,'Jefe de área'),
(135,'Abuso de autoridad','Instituto de Verificación Administrativa',NULL,'Coordinador'),
(136,'Negativa de servicio','Secretaría de Movilidad',NULL,NULL),
(137,'Negativa de servicio','Secretaría de Obras',NULL,NULL),
(138,'Soborno','Alcaldía Iztapalapa','Carlos López',NULL),
(139,'Negativa de servicio','Instituto de Verificación Administrativa',NULL,'Analista'),
(140,'Tráfico de influencias','Secretaría de Obras','Paola Moreno','Analista'),
(141,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','Carlos López','Coordinador'),
(142,'Soborno','Secretaría de Movilidad',NULL,'Analista'),
(143,'Uso indebido de recursos','Secretaría de Movilidad','José Ramírez',NULL),
(144,'Negativa de servicio','Alcaldía Iztapalapa','Miguel Castillo','Analista'),
(145,'Omisión de funciones','Instituto de Verificación Administrativa','José Ramírez',NULL),
(146,'Soborno','Sistema de Aguas de la CDMX',NULL,NULL),
(147,'Negativa de servicio','Instituto de Verificación Administrativa','Pedro Sánchez',NULL),
(148,'Negativa de servicio','Secretaría de Seguridad Ciudadana',NULL,NULL),
(149,'Abuso de autoridad','Instituto de Verificación Administrativa','María Hernández','Jefe de área'),
(150,'Uso indebido de recursos','Secretaría de Obras','José Ramírez',NULL),
(151,'Negativa de servicio','Secretaría de Obras',NULL,NULL),
(152,'Uso indebido de recursos','Sistema de Aguas de la CDMX','Laura Rojas','Coordinador'),
(153,'Negativa de servicio','Alcaldía Iztapalapa','Laura Rojas','Inspector'),
(154,'Omisión de funciones','Alcaldía Iztapalapa',NULL,'Coordinador'),
(155,'Soborno','Instituto de Verificación Administrativa',NULL,'Director'),
(156,'Tráfico de influencias','Secretaría de Seguridad Ciudadana',NULL,NULL),
(157,'Omisión de funciones','Instituto de Verificación Administrativa',NULL,'Analista'),
(158,'Soborno','Instituto de Verificación Administrativa',NULL,NULL),
(159,'Omisión de funciones','Sistema de Aguas de la CDMX','José Ramírez','Jefe de área'),
(160,'Negativa de servicio','Secretaría de Movilidad',NULL,'Supervisor'),
(161,'Negativa de servicio','Secretaría de Movilidad','Miguel Castillo',NULL),
(162,'Tráfico de influencias','Secretaría de Movilidad','Laura Rojas','Jefe de área'),
(163,'Tráfico de influencias','Secretaría de Obras',NULL,NULL),
(164,'Negativa de servicio','Alcaldía Iztapalapa',NULL,NULL),
(165,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','Lucía Vargas','Director'),
(166,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana','Ana Torres','Analista'),
(167,'Negativa de servicio','Secretaría de Obras','María Hernández','Supervisor'),
(168,'Negativa de servicio','Secretaría de Movilidad',NULL,NULL),
(169,'Abuso de autoridad','Secretaría de Movilidad','Paola Moreno','Coordinador'),
(170,'Uso indebido de recursos','Alcaldía Iztapalapa','Daniela Cruz','Coordinador'),
(171,'Soborno','Secretaría de Movilidad',NULL,NULL),
(172,'Negativa de servicio','Secretaría de Seguridad Ciudadana',NULL,NULL),
(173,'Tráfico de influencias','Sistema de Aguas de la CDMX','Miguel Castillo','Director'),
(174,'Uso indebido de recursos','Sistema de Aguas de la CDMX',NULL,'Analista'),
(175,'Soborno','Secretaría de Obras','Carlos López','Analista'),
(176,'Abuso de autoridad','Alcaldía Iztapalapa',NULL,'Jefe de área'),
(177,'Tráfico de influencias','Secretaría de Seguridad Ciudadana',NULL,NULL),
(178,'Omisión de funciones','Secretaría de Movilidad',NULL,NULL),
(179,'Uso indebido de recursos','Secretaría de Movilidad','Luis Méndez',NULL),
(180,'Soborno','Secretaría de Seguridad Ciudadana','José Ramírez',NULL),
(181,'Uso indebido de recursos','Sistema de Aguas de la CDMX','María Hernández','Analista'),
(182,'Soborno','Secretaría de Seguridad Ciudadana','Ana Torres',NULL),
(183,'Tráfico de influencias','Alcaldía La Magdalena Contreras','José Ramírez',NULL),
(184,'Soborno','Sistema de Aguas de la CDMX','Laura Rojas','Jefe de área'),
(185,'Negativa de servicio','Alcaldía Miguel Hidalgo','Paola Moreno','Inspector'),
(186,'Uso indebido de recursos','Secretaría de Obras',NULL,NULL),
(187,'Soborno','Alcaldía Miguel Hidalgo','María Hernández',NULL),
(188,'Tráfico de influencias','Secretaría de Seguridad Ciudadana','Pedro Sánchez','Coordinador'),
(189,'Omisión de funciones','Instituto de Verificación Administrativa',NULL,NULL),
(190,'Abuso de autoridad','Secretaría de Obras',NULL,'Inspector'),
(191,'Omisión de funciones','Secretaría de Seguridad Ciudadana','Carlos López','Analista'),
(192,'Omisión de funciones','Secretaría de Obras','Lucía Vargas','Jefe de área'),
(193,'Uso indebido de recursos','Sistema de Aguas de la CDMX','Daniela Cruz','Jefe de área'),
(194,'Tráfico de influencias','Secretaría de Movilidad','Pedro Sánchez',NULL),
(195,'Soborno','Alcaldía Milpa Alta','Ana Torres','Jefe de área'),
(196,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Coordinador'),
(197,'Omisión de funciones','Secretaría de Movilidad',NULL,NULL),
(198,'Tráfico de influencias','Secretaría de Obras','Ricardo Vega','Inspector'),
(199,'Tráfico de influencias','Instituto de Verificación Administrativa',NULL,NULL),
(200,'Abuso de autoridad','Secretaría de Movilidad','Paola Moreno',NULL),
(201,'Abuso de autoridad','Secretaría de Movilidad',NULL,'Coordinador'),
(202,'Soborno','Secretaría de Seguridad Ciudadana',NULL,'Director'),
(203,'Negativa de servicio','Sistema de Aguas de la CDMX',NULL,'Supervisor'),
(204,'Tráfico de influencias','Alcaldía Tláhuac','Pedro Sánchez',NULL),
(205,'Omisión de funciones','Secretaría de Obras',NULL,'Jefe de área'),
(206,'Omisión de funciones','Secretaría de Seguridad Ciudadana','Lucía Vargas','Analista'),
(207,'Soborno','Alcaldía Tláhuac',NULL,NULL),
(208,'Negativa de servicio','Secretaría de Obras','Laura Rojas','Supervisor'),
(209,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,'Coordinador'),
(210,'Omisión de funciones','Secretaría de Movilidad',NULL,'Director'),
(211,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,'Jefe de área'),
(212,'Negativa de servicio','Alcaldía Tlalpan','María Hernández',NULL),
(213,'Tráfico de influencias','Sistema de Aguas de la CDMX','Carlos López',NULL),
(214,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana','María Hernández',NULL),
(215,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana',NULL,'Director'),
(216,'Tráfico de influencias','Alcaldía Tlalpan',NULL,'Analista'),
(217,'Omisión de funciones','Secretaría de Movilidad',NULL,'Analista'),
(218,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Director'),
(219,'Omisión de funciones','Sistema de Aguas de la CDMX','Ricardo Vega',NULL),
(220,'Uso indebido de recursos','Instituto de Verificación Administrativa','Luis Méndez','Director'),
(221,'Soborno','Secretaría de Obras',NULL,'Analista'),
(222,'Abuso de autoridad','Instituto de Verificación Administrativa','Pedro Sánchez','Director'),
(223,'Uso indebido de recursos','Secretaría de Obras','Daniela Cruz','Inspector'),
(224,'Tráfico de influencias','Secretaría de Seguridad Ciudadana','Pedro Sánchez',NULL),
(225,'Negativa de servicio','Instituto de Verificación Administrativa',NULL,'Director'),
(226,'Uso indebido de recursos','Secretaría de Obras',NULL,'Jefe de área'),
(227,'Omisión de funciones','Sistema de Aguas de la CDMX',NULL,NULL),
(228,'Omisión de funciones','Secretaría de Obras','María Hernández','Coordinador'),
(229,'Soborno','Secretaría de Seguridad Ciudadana','Lucía Vargas','Jefe de área'),
(230,'Negativa de servicio','Secretaría de Obras','Miguel Castillo',NULL),
(231,'Tráfico de influencias','Sistema de Aguas de la CDMX','María Hernández','Inspector'),
(232,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','Laura Rojas','Jefe de área'),
(233,'Abuso de autoridad','Instituto de Verificación Administrativa',NULL,'Analista'),
(234,'Negativa de servicio','Secretaría de Movilidad',NULL,'Coordinador'),
(235,'Soborno','Sistema de Aguas de la CDMX','Laura Rojas','Jefe de área'),
(236,'Soborno','Secretaría de Obras','Laura Rojas','Jefe de área'),
(237,'Omisión de funciones','Sistema de Aguas de la CDMX','Pedro Sánchez',NULL),
(238,'Omisión de funciones','Sistema de Aguas de la CDMX','Ricardo Vega','Coordinador'),
(239,'Abuso de autoridad','Alcaldía Venustiano Carranza',NULL,NULL),
(240,'Negativa de servicio','Alcaldía Xochimilco',NULL,'Supervisor'),
(241,'Omisión de funciones','Sistema de Aguas de la CDMX','Carlos López','Director'),
(242,'Soborno','Alcaldía Xochimilco',NULL,'Analista'),
(243,'Tráfico de influencias','Sistema de Aguas de la CDMX',NULL,'Supervisor'),
(244,'Tráfico de influencias','Alcaldía Xochimilco',NULL,NULL),
(245,'Negativa de servicio','Alcaldía Xochimilco','José Ramírez','Analista'),
(246,'Uso indebido de recursos','Secretaría de Obras',NULL,'Analista'),
(247,'Omisión de funciones','Secretaría de Movilidad','Paola Moreno','Coordinador'),
(248,'Tráfico de influencias','Sistema de Aguas de la CDMX',NULL,'Jefe de área'),
(249,'Soborno','Alcaldía Xochimilco',NULL,NULL),
(250,'Soborno','Alcaldía Xochimilco',NULL,'Director');