USE ReportesCiudadanos;
SELECT * FROM Instituciones;
INSERT INTO Instituciones (IdInstitucion, NombreInstitucion, TipoReporteId, Descripcion, Telefono, CorreoElectronico, HorarioAtencion, Direccion, EnlaceWeb)
VALUES
(1, 'SOBSE - Secretaría de Obras y Servicios de la CDMX', 1, 'Atiende reportes sobre alumbrado público, baches, recolección de basura, mantenimiento urbano y limpieza de calles. Supervisa empresas concesionadas y cuadrillas de servicios.', '55 5002 6300', NULL, 
'Lunes a viernes de 09:00 a 17:00 horas.', 'Plaza de la Constitución 1, Piso 2, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX', 
'https://www.obras.cdmx.gob.mx'),
(2, 'SEDEMA - Secretaría del Medio Ambiente', 1, 'Atiende reportes sobre contaminación, ruido excesivo, tala ilegal, emisiones de vehículos y afectaciones ambientales. Coordina inspecciones y sanciones.', '55 5265 0780', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Oficina principal: Plaza de la Constitución 1, Tercer piso, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX; Oficina Xochimilco: Avenida Año de Juárez 9700, Colonia Quirino Mendoza, Alcaldía Xochimilco, C.P. 16710, Ciudad de México, CDMX', 
'https://www.sedema.cdmx.gob.mx'),
(3, 'SACMEX - Sistema de Aguas de la Ciudad de México', 1, 'Recibe reportes de fugas, falta de suministro, encharcamientos, taponamientos de drenaje y temas relacionados con agua potable y alcantarillado.', '55 5654 3210', NULL, 'Lunes a viernes de 08:00 a 20:00 horas.', 
'Plaza Inn: Avenida Insurgentes Sur 1971, Local 160 Nivel Fuente, Colonia San Ángel Inn, Alcaldía Álvaro Obregón, C.P. 01020, Ciudad de México, CDMX; Azcapotzalco: Avenida Aquiles Serdán 400, Local L116, Colonia Nextengo, Alcaldía Azcapotzalco, C.P. 02070, Ciudad de México, CDMX; Benito Juárez: Avenida Xola 611, Colonia Del Valle Norte, Alcaldía Benito Juárez, C.P. 03103, Ciudad de México, CDMX; Coyoacán: Calle Estrella Cefeida 40, Colonia Prados de Coyoacán, Alcaldía Coyoacán, C.P. 04810, Ciudad de México, CDMX; Cuajimalpa: Avenida José María Castorena 425, Local 11 PB, Colonia San José de los Cedros, Alcaldía Cuajimalpa, C.P. 05200, Ciudad de México, CDMX; Cuauhtémoc: Monterrey 132, Colonia Roma Norte, Alcaldía Cuauhtémoc, C.P. 06700, Ciudad de México, CDMX; Gustavo A. Madero: Avenida Othón de Mendizábal 343, Locales 3 y 4, Colonia Nueva Industrial Vallejo, Alcaldía Gustavo A. Madero, C.P. 07700, Ciudad de México, CDMX; Iztacalco: Avenida Río Churubusco 264, Colonia Granjas México, Alcaldía Iztacalco, C.P. 08400, Ciudad de México, CDMX; Iztapalapa: Calle 2 219, Colonia Granjas San Antonio, Alcaldía Iztapalapa, C.P. 09070, Ciudad de México, CDMX; Magdalena Contreras: Avenida San Bernabé 327, Local 2, Colonia San Jerónimo Lídice, Alcaldía La Magdalena Contreras, C.P. 10200, Ciudad de México, CDMX; Miguel Hidalgo: Gutenberg 50, Colonia Verónica Anzures, Alcaldía Miguel Hidalgo, C.P. 11300, Ciudad de México, CDMX; Milpa Alta: Avenida Jalisco Poniente 36, Colonia Barrio San Mateo, Alcaldía Milpa Alta, C.P. 12000, Ciudad de México, CDMX; Tláhuac: Avenida Tláhuac 5618, Colonia Santa Ana Poniente, Alcaldía Tláhuac, C.P. 13300, Ciudad de México, CDMX; Tlalpan: Avenida Prolongación División del Norte 4551, Local 8, Colonia Residencial Chimali, Alcaldía Tlalpan, C.P. 14370, Ciudad de México, CDMX; Venustiano Carranza: Avenida H. Congreso de la Unión 444, Colonia Magdalena Mixhuca, Alcaldía Venustiano Carranza, C.P. 15850, Ciudad de México, CDMX; Xochimilco: Camino a Nativitas 471, Colonia Xaltocan, Alcaldía Xochimilco, C.P. 16090, Ciudad de México, CDMX', 
'https://www.sacmex.cdmx.gob.mx'),
(4, 'STE - Servicio de Transportes Eléctricos de la CDMX', 1, 'Recibe reportes sobre fallas en el trolebús, tren ligero y unidades eléctricas; también canaliza quejas por conducta de operadores o daños a infraestructura.', '55 5674 4342', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Municipio Libre 402, Colonia San Andrés Tetepilco, Alcaldía Iztapalapa, C.P. 09440, Ciudad de México, CDMX', 
'https://www.ste.cdmx.gob.mx'),
(5, 'AGATAN - Agencia de Atención Animal', 1, 'Atiende denuncias sobre maltrato animal, abandono, omisión de cuidados y condiciones inadecuadas en espacios públicos. También supervisa centros de control animal y promueve la adopción responsable.', '55 5208 9898 Extensión 3418', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Centro Miguel Hidalgo: Avenida Ignacio Zaragoza S/N, Sección III Bosque de Chapultepec, Alcaldía Miguel Hidalgo, C.P. 11100, Ciudad de México, CDMX; Centro Iztapalapa: Avenida Ermita Iztapalapa 2451, Colonia San Andrés Tetepilco, Alcaldía Iztapalapa, C.P. 09440, Ciudad de México, CDMX; Centro Azcapotzalco: Avenida 22 de febrero 421, Colonia San Marcos, Alcaldía Azcapotzalco, C.P. 02260, Ciudad de México, CDMX', 
'https://www.agatan.cdmx.gob.mx'),
(6, 'SESNSP - Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública', 2, 'Coordina estadísticas y estrategias nacionales contra delitos de robo, asalto y violencia. Canaliza información hacia las fiscalías estatales.', '800 00 POLICÍA (76542)', NULL, 'Las 24 horas, los 365 días del año.', 
'Avenida Constituyentes 947, Colonia Belén de las Flores, Alcaldía Álvaro Obregón, C.P. 01110, Ciudad de México, CDMX', 
'https://www.gob.mx/sesnsp'),
(7, 'FGJCDMX - Policía de Investigación', 2, 'Encargada de investigar robos, asaltos y delitos patrimoniales. Coordina operativos y seguimiento de denuncias a través del Ministerio Público.', '55 5200 9000', NULL, 'Las 24 horas, todos los días.', 
'Calle Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(8, 'Policía Auxiliar - Secretaría de Seguridad Ciudadana', 2, 'Brinda servicios de vigilancia y prevención en zonas públicas, comercios y transporte. Apoya en atención inmediata a víctimas de robo.', '55 5242 5100', NULL, 'Las 24 horas, los 365 días del año.', 
'Calle Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(9, 'C5 - Centro de Comando, Control, Cómputo, Comunicaciones y Contacto Ciudadano', 2, 'Atiende emergencias en tiempo real, activa cámaras de videovigilancia y canaliza denuncias al 911 o 089. Coordina el monitoreo urbano para respuesta inmediata.', '911 / 089', NULL, 'Las 24 horas, todos los días.', 
'Avenida Coyoacán 1909, Colonia Xoco, Alcaldía Benito Juárez, C.P. 03330, Ciudad de México, CDMX', 
'https://www.c5.cdmx.gob.mx'),
(10, 'CEJUR - Consejería Jurídica y de Servicios Legales de la CDMX', 2, 'Ofrece asesoría jurídica gratuita para víctimas de robo, fraude o asalto; orienta sobre denuncias, recuperación de bienes y derechos de las víctimas.', '55 5128 1100', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Plaza de la Constitución 2, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06068, Ciudad de México, CDMX', 
'https://www.consejeria.cdmx.gob.mx'),
(11, 'SCG - Secretaría de la Contraloría General de la Ciudad de México', 3, 'Recibe denuncias por corrupción, abuso de autoridad, tráfico de influencias y omisiones de servidores públicos.', '55 5627 9700', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Calle Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX',
'https://www.contraloria.cdmx.gob.mx'),
(12, 'ASCM - Auditoría Superior de la Ciudad de México', 3, 'Vigila el uso correcto de los recursos públicos, detecta irregularidades financieras y recibe denuncias ciudadanas por desvío o mal manejo de fondos.', '55 5130 1500', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida 20 de noviembre #700 Huichapan, San Marcos, Xochimilco, C.P. 16050, Ciudad de México, CDMX', 
'https://www.ascm.cdmx.gob.mx'),
(13, 'INFOCDMX - Instituto de Transparencia de la Ciudad de México', 3, 'Promueve la transparencia gubernamental y permite solicitar información o denunciar irregularidades en la gestión pública.', '55 5636 4636', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Calle La Morena 865, Colonia Narvarte Poniente, Alcaldía Benito Juárez, C.P. 03020, Ciudad de México, CDMX', 
'https://www.infocdmx.org.mx'),
(14, 'OIC - Órgano Interno de Control en la Administración Pública de la CDMX', 3, 'Supervisa el cumplimiento de las normas administrativas en dependencias del Gobierno de la Ciudad. Atiende denuncias internas contra funcionarios.', '55 5627 9700 Extensión 5001', NULL, 'Lunes a viernes de 09:00 a 17:00 horas.', 
'Secretaría de Gobierno: Av. San Antonio Abad 130, Col. Tránsito, Cuauhtémoc; Servicios de Salud Pública: Av. Insurgentes Norte 423, Nonoalco-Tlatelolco; Jefatura de Gobierno: Plaza de la Constitución 2, Centro; Consejería Jurídica: Calle Tolsá 63, Centro; Secretaría de Obras: Av. Universidad 800, Santa Cruz Atoyac', 
'https://www.contraloria.cdmx.gob.mx/oic'),
(15, 'FGJCDMX - Fiscalía de Servidores Públicos', 3, 'Investiga delitos como abuso de autoridad, cohecho, extorsión o negligencia cometidos por funcionarios del gobierno local.', '55 5200 9000 Extensión 1120', NULL, 'Lunes a viernes de 09:00 a 19:00 horas.', 
'Avenida Dr. Río de la Loza #156, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(16, 'FGJCDMX - Fiscalía General de Justicia de la Ciudad de México', 4, 'Es la instancia para presentar la denuncia formal, solicitar seguimiento e integridad de la investigación. Ofrece atención telefónica 24/7 y la opción de Denuncia Digital para ciertos delitos.', '(55) 5200 9000', 'gestion_fiscal@fgjcdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Calle Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(17, 'CEJUM-CDMX - Centro de Justicia para las Mujeres de la Ciudad de México', 4, 'Brinda atención integral, gratuita y confidencial a mujeres, niñas y adolescentes víctimas de violencia. Ofrece acompañamiento jurídico, psicológico, médico y de trabajo social. Facilita el acceso a la justicia con perspectiva de género, garantizando un entorno seguro para la denuncia y protección inmediata.', '55 5346 8100 Extensión 5082 / 55 5200 9000', NULL, 'Lunes a domingo, las 24 horas del día.', 
'CEJUM Azcapotzalco: Av. San Pablo Xalpa 396, Col. San Martin Xochinahuac, Azcapotzalco, C.P. 02128; CEJUM Iztapalapa: Calle 20 de noviembre, junto a CT Iztapalapa 3, Col. San Pablo, Iztapalapa, C.P. 09089; CEJUM Tlalpan: Periférico Sur esq. Canal de Miramontes, Col. Guadalupe, Tlalpan, C.P. 14387; CEJUM Magdalena Contreras: Cerrada Soledad S/N, Col. San Bernabé Ocotepec, La Magdalena Contreras, C.P. 10300', 
'https://www.fgjcdmx.gob.mx/nuestros-servicios/centro-de-justicia-para-las-mujeres'),
(18, 'SEM - Secretaría de las Mujeres de la Ciudad de México', 4, 'Institución encargada de prevenir, atender y erradicar la violencia contra mujeres, niñas y adolescentes. Ofrece asesoría jurídica y psicológica, unidades territoriales de atención y canalización hacia otros servicios especializados.', '55 5512 2836', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Av. Morelos 20, Col. Centro, Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX', 
'https://www.semujeres.cdmx.gob.mx'),
(19, 'LUNAS - Unidades Territoriales de Atención y Prevención de la Violencia de Género', 4, 'Las unidades territoriales de la Secretaría de las Mujeres ofrecen asesoría jurídica y psicológica, acompañamiento y canalización para mujeres que viven violencia. También brindan información sobre derechos sexuales y reproductivos e Interrupción Legal del Embarazo. El modelo de atención identifica el nivel de riesgo y fortalece emocionalmente a las usuarias para lograr su autonomía.', '55 5512 2836 Extensión 502', NULL, 'Lunes a viernes de 09:00 a 17:00 horas.', 
'Álvaro Obregón: Prol. Calle 4, Col. Tolteca, C.P. 01150 y Calle 22 y Av. Hidalgo esq. Calle 17, Col. Preconcreto, C.P. 01400; Azcapotzalco: Av. 22 de febrero 421, Col. Barrio San Marcos, C.P. 02260; Benito Juárez: Eje Central Lázaro Cárdenas 695 piso 1, Col. Narvarte Poniente, C.P. 03020 y Eje 5 Sur Ramos Millán 95, Col. Niños Héroes, C.P. 03440; Coyoacán: Leopoldo Salazar s/n casi esq. Carlos Glez Peña, Col. Copilco el Alto, C.P. 04360 y Av. Rey Nezahualcóyotl s/n esq. Yaquis, Col. Ajusco Huayamilpas, C.P. 04300; Cuajimalpa: Prol. 16 de septiembre s/n casi esq. Av. Veracruz, Col. Contadero y José María Castorena 187, Col. Cuajimalpa, C.P. 05500; Cuauhtémoc: Aldama/Violeta/Mina s/n, Col. Buenavista, C.P. 06350 y Río Danubio 126 esq. Río Lerma, Col. Cuauhtémoc, C.P. 06500; Gustavo A. Madero: Av. Fray Juan de Zumárraga s/n, Col. Aragón la Villa, C.P. 07050 y Camellón Oriente 95 y Norte 50, Col. La Joyita, C.P. 07860; Iztacalco: Av. Santiago s/n esq. Playa Rosarito, Col. Barrio Santiago, C.P. 08800 y Av. Sur 8 s/n casi Av. Javier Rojo Gómez, Col. Agrícola Oriental, C.P. 08500; Iztapalapa: Camino Cerro de la Estrella s/n, Col. El Santuario Aculco, C.P. 09009; La Magdalena Contreras: Piaztic s/n, Col. San José Atacaxco, C.P. 10378; Miguel Hidalgo: Av. Parque Lira 128, Col. Ampliación Daniel Garza, C.P. 11800 y Av. Observatorio s/n esq. Gral. José Ma. Mendívil, Col. Daniel Garza, C.P. 11830; Milpa Alta: Calle Yucatán s/n esq. Constitución, Col. Villa Milpa Alta Centro, C.P. 12000 y Av. Puebla 250 esq. Av. Nuevo León, Col. Villa Milpa Alta, C.P. 12000; Tláhuac: Margarita 5 entre Geranio y Jacaranda, Col. Quiahuatla, C.P. 13090; Tlalpan: Carretera Federal a Cuernavaca 2, Col. La Joya, C.P. 14090 y Camino a Santa Úrsula 24 esq. Textitlán, Col. Santa Úrsula Xitla, C.P. 14420; Venustiano Carranza: Prol. Lucas Alamán 11 piso 1, Col. Del Parque, C.P. 15960; Xochimilco: Francisco I. Madero 11, Col. Barrio El Rosario, C.P. 16070 y Dalia s/n Plaza San Cristóbal, Col. Barrio San Cristóbal, C.P. 16080', 
'https://www.semujeres.cdmx.gob.mx/lunas'),
(20, 'CTA - Centro de Terapia de Apoyo a Víctimas de Delitos Sexuales', 4, 'Atención multidisciplinaria a víctimas directas e indirectas de delitos sexuales. Ofrece orientación psicológica, trabajo social, asistencia médica (incluyendo anticoncepción de emergencia y medicamentos antirretrovirales dentro de las 72 horas posteriores a la exposición de riesgo) y asesoría jurídica. El objetivo es empoderar a la víctima y garantizar el respeto a sus derechos.', '55 5200 9632 / 55 5200 9633', NULL, 'Lunes a viernes de 09:00 a 19:00 horas.', 
'Calle Enrique Pestalozzi No. 1115, Colonia del Valle, Alcaldía Benito Juárez, C.P. 03100, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx/nuestros-servicios/en-linea/mp-virtual/cta-centro-de-terapia-de-apoyo-victimas-de-delitos-sexuales'),
(21, 'FIDN - Fiscalía de Investigación del Delito de Narcomenudeo (FGJCDMX)', 5, 'Encargada de recibir denuncias anónimas y directas sobre puntos de venta, almacenamiento y distribución de drogas en la Ciudad de México.', '55 5200 9000 Extensión 5083', NULL, 'Las 24 horas, los 365 días del año.', 
'Sede Central: Calle Dr. Río de la Loza 156, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX; Agencia Norte: Avenida 100 Metros 1200, Colonia Lindavista, Alcaldía Gustavo A. Madero, C.P. 07300, Ciudad de México, CDMX; Agencia Sur: Calzada de Tlalpan 2962, Colonia Espartaco, Alcaldía Coyoacán, C.P. 04870, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(22, 'GN - Guardia Nacional', 5, 'Fuerza federal encargada de la prevención y combate de delitos relacionados con el narcotráfico y narcomenudeo.', '800 627 4621', NULL, 'Las 24 horas, los 365 días del año.', 
'Avenida Casa de la Moneda 198, Colonia Loma Hermosa, Alcaldía Miguel Hidalgo, C.P. 11200, Ciudad de México, CDMX', 
'https://www.gob.mx/gn'),
(23, 'SSC - Secretaría de Seguridad Ciudadana de la CDMX', 5, 'Realiza operativos de vigilancia y prevención de narcomenudeo en espacios públicos. Coordina con la Fiscalía y la Guardia Nacional para el aseguramiento de sustancias ilícitas.', '55 5242 5100', NULL, 'Las 24 horas, los 365 días del año.', 
'Calle Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(24, 'CNI - Centro Nacional de Inteligencia', 5, 'Órgano de inteligencia del Estado mexicano responsable de recopilar y analizar información sobre delitos de alto impacto, incluyendo narcotráfico y narcomenudeo. Apoya a las fiscalías en investigaciones estratégicas.', '55 5484 7400', 'cni@cni.gob.mx', 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Camino Real a Contreras 35, Colonia La Concepción, Alcaldía La Magdalena Contreras, C.P. 10830, Ciudad de México, CDMX', 
'https://www.gob.mx/cni'),
(25, 'SEDENA - Secretaría de la Defensa Nacional', 5, 'A través de la Policía Militar y los Batallones de Seguridad, apoya en la erradicación de narco cultivos, aseguramiento de sustancias y detención de grupos delictivos relacionados con el narcomenudeo.', '800 832 4770', NULL, 'Las 24 horas, los 365 días del año.', 
'Avenida Industria Militar S/N, esquina con Boulevard Manuel Ávila Camacho, Colonia Lomas de Sotelo, Alcaldía Miguel Hidalgo, C.P. 11640, Ciudad de México, CDMX', 
'https://www.gob.mx/sedena'),
(26, 'LOCATEL - Servicio Público de Localización Telefónica', 6, 'Brinda atención telefónica y digital sobre reportes ciudadanos, asesoría jurídica, orientación psicológica, objetos extraviados y servicios públicos. Canaliza solicitudes hacia las dependencias correspondientes o instancias de emergencia.', '*0311 / 55 5658 1111', NULL, 'Las 24 horas, los 365 días del año.', 
'Atención telefónica y digital, sin atención presencial, Ciudad de México, CDMX', 
'https://www.locatel.cdmx.gob.mx'),
(27, 'SEMOVI - Secretaría de Movilidad de la Ciudad de México', 6, 'Atiende reportes relacionados con transporte público, taxis, bici estaciones, infracciones, semáforos, ciclovías y vehículos abandonados. Supervisa la movilidad sustentable y los sistemas de transporte concesionado.', '55 5709 9271 / 800 999 1391', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Módulo Roma: Avenida Álvaro Obregón 269, Colonia Roma Norte, Alcaldía Cuauhtémoc, C.P. 06700, Ciudad de México, CDMX; Módulo Insurgentes: Avenida Insurgentes Sur 263, Planta Baja, Colonia Roma Norte, Alcaldía Cuauhtémoc, C.P. 06700, Ciudad de México, CDMX; Módulo Plaza de las Estrellas: Circuito Interior Melchor Ocampo 193, Local J-24, Colonia Verónica Anzures, Alcaldía Miguel Hidalgo, Ciudad de México, CDMX; Módulo División del Norte: Avenida Municipio Libre 314, Colonia División del Norte, Alcaldía Benito Juárez, Ciudad de México, CDMX', 
'https://www.semovi.cdmx.gob.mx'),
(28, 'SGIRPC - Secretaría de Gestión Integral de Riesgos y Protección Civil', 6, 'Coordina la atención a emergencias por sismos, incendios, lluvias, derrumbes o accidentes. Recibe reportes ciudadanos y activa protocolos de protección civil en coordinación con el C5 y dependencias locales.', '55 5683 2222', 'contacto@proteccioncivil.cdmx.gob.mx', 'Lunes a viernes de 08:00 a 18:00 horas.', 
'Avenida Patriotismo 711, Colonia San Juan, Alcaldía Benito Juárez, C.P. 03730, Ciudad de México, CDMX', 
'https://www.proteccioncivil.cdmx.gob.mx'),
(29, 'PAOT - Procuraduría Ambiental y del Ordenamiento Territorial', 6, 'Recibe denuncias ambientales, urbanas y vecinales: ruido excesivo, tala o poda ilegal, invasión de áreas verdes, maltrato animal y construcciones irregulares. Atiende y canaliza los reportes a las áreas competentes.', '55 5265 0780', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Calle Medellín 202, esquina con Tapachula, Colonia Roma Sur, Alcaldía Cuauhtémoc, C.P. 06700, Ciudad de México, CDMX', 
'https://www.paot.org.mx'),
(30, 'JGCDMX - Jefatura de Gobierno de la Ciudad de México', 6, 'Recibe peticiones, quejas y sugerencias ciudadanas mediante el sistema Atención Ciudadana CDMX. Permite registrar reportes sobre trámites, servicios o anomalías relacionadas con cualquier dependencia del gobierno local.', '55 5345 8000 Extensión 1600', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Plaza de la Constitución 2, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX', 
'https://www.cdmx.gob.mx'),
(31, 'SSC - Secretaría de Seguridad Ciudadana de la CDMX', 1, 'Atiende reportes relacionados con seguridad pública, disturbios, robos, violencia y emergencias. Coordina la actuación de la policía preventiva y canaliza denuncias ciudadanas.', '55 5242 5100', NULL, 'Atención 24 horas, todos los días del año.', 
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(32, 'FGJCDMX - Fiscalía General de Justicia de la CDMX', 1, 'Recibe denuncias sobre delitos, investiga hechos delictivos y brinda atención a víctimas. También gestiona servicios periciales y ministeriales.', '55 5200 9000', NULL, 'Atención 24 horas, todos los días del año.', 
'Digna Ochoa y Plácido 56, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(33, 'SEMOVI - Secretaría de Movilidad de la CDMX', 1, 'Atiende reportes relacionados con transporte público, concesiones, infracciones, taxis irregulares y problemas de movilidad urbana.', '55 5209 9913', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Álvaro Obregón 269, Colonia Roma Norte, Alcaldía Cuauhtémoc, C.P. 06700, Ciudad de México, CDMX', 
'https://www.semovi.cdmx.gob.mx'),
(34, 'PAOT - Procuraduría Ambiental y del Ordenamiento Territorial de la CDMX', 1, 'Atiende denuncias sobre uso de suelo, construcciones irregulares, daño ambiental, ruido excesivo y afectaciones al entorno urbano.', '55 5265 0780', NULL, 'Lunes a jueves de 09:00 a 18:00 horas, viernes de 09:00 a 15:00 horas.', 
'Medellín 202, Colonia Roma Sur, Alcaldía Cuauhtémoc, C.P. 06760, Ciudad de México, CDMX', 
'https://www.paot.org.mx'),
(35, 'DIF CDMX - Sistema para el Desarrollo Integral de la Familia de la Ciudad de México', 1, 'Atiende reportes sobre violencia familiar, abandono, apoyo a menores, adultos mayores y personas en situación vulnerable. Brinda asistencia social y canalización a servicios especializados.', '55 8957 3450', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'San Francisco 1374, Colonia Tlacoquemécatl del Valle, Alcaldía Benito Juárez, C.P. 03200, Ciudad de México, CDMX', 
'https://www.dif.cdmx.gob.mx'),
(36, 'SGIRPC - Secretaría de Gestión Integral de Riesgos y Protección Civil de la CDMX', 1, 'Atiende reportes sobre riesgos estructurales, incendios, fugas de gas, derrumbes, inundaciones y situaciones de emergencia. Coordina acciones de protección civil y prevención de desastres.', '55 5683 2222', NULL, 'Atención 24 horas, todos los días del año.', 
'Avenida Patriotismo 711, Colonia San Juan, Alcaldía Benito Juárez, C.P. 03730, Ciudad de México, CDMX', 
'https://www.proteccioncivil.cdmx.gob.mx'),
(37, 'HCB - Heroico Cuerpo de Bomberos de la Ciudad de México', 1, 'Atiende reportes de incendios, explosiones, fugas de gas, rescates y emergencias relacionadas con siniestros. Brinda atención inmediata en situaciones de riesgo.', '55 5768 2532', NULL, 'Atención 24 horas, todos los días del año.', 
'Avenida Insurgentes Centro 95, Colonia San Rafael, Alcaldía Cuauhtémoc, C.P. 06470, Ciudad de México, CDMX', 
'https://www.bomberos.cdmx.gob.mx'),
(38, 'CDHCM - Comisión de Derechos Humanos de la Ciudad de México', 1, 'Atiende quejas por violaciones a derechos humanos cometidas por autoridades. Brinda orientación, acompañamiento y seguimiento a casos.', '55 5229 5600', NULL, 'Atención 24 horas, todos los días del año.', 
'Avenida Universidad 1449, Colonia Florida, Alcaldía Álvaro Obregón, C.P. 01030, Ciudad de México, CDMX', 
'https://www.cdhcm.org.mx'),
(39, 'INVEA - Instituto de Verificación Administrativa de la CDMX', 1, 'Atiende reportes sobre establecimientos mercantiles irregulares, incumplimiento de normas, uso de suelo indebido y verificación administrativa.', '55 4737 7700', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Carolina 132, Colonia Nochebuena, Alcaldía Benito Juárez, C.P. 03720, Ciudad de México, CDMX', 
'https://www.invea.cdmx.gob.mx'),
(40, 'SEDESA - Secretaría de Salud de la CDMX', 1, 'Atiende reportes relacionados con servicios de salud pública, hospitales, centros de salud, campañas sanitarias y riesgos sanitarios.', '55 5132 1200', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Insurgentes Norte 423, Colonia Santa María la Ribera, Alcaldía Cuauhtémoc, C.P. 06400, Ciudad de México, CDMX', 
'https://www.salud.cdmx.gob.mx'),
(41, 'STC - Sistema de Transporte Colectivo Metro', 1, 'Atiende reportes sobre fallas en el servicio del metro, retrasos, incidentes en estaciones, condiciones de trenes y seguridad dentro de las instalaciones.', '55 5627 4950', NULL, 'Atención 24 horas, todos los días del año.', 
'Avenida Balderas 58, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06010, Ciudad de México, CDMX', 
'https://www.metro.cdmx.gob.mx'),
(42, 'Metrobús - Sistema de Corredores de Transporte Público de Pasajeros de la CDMX', 1, 'Atiende reportes sobre unidades, estaciones, retrasos, fallas en el servicio y conducta de operadores del sistema Metrobús.', '55 5761 6858', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Cuauhtémoc 16, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.metrobus.cdmx.gob.mx'),
(43, 'CFE - Comisión Federal de Electricidad', 1, 'Atiende reportes sobre fallas en el suministro eléctrico, apagones, variaciones de voltaje, postes dañados y problemas relacionados con energía eléctrica.', '071', NULL, 'Atención 24 horas, todos los días del año.', 
'Avenida Paseo de la Reforma 164, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.cfe.mx'),
(44, 'CONAGUA - Comisión Nacional del Agua', 1, 'Atiende reportes relacionados con cuerpos de agua federales, inundaciones, infraestructura hidráulica y gestión de recursos hídricos.', '55 5174 4000', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Insurgentes Sur 2416, Colonia Copilco El Bajo, Alcaldía Coyoacán, C.P. 04340, Ciudad de México, CDMX', 
'https://www.gob.mx/conagua'),
(45, 'ADIP - Agencia Digital de Innovación Pública de la CDMX', 1, 'Atiende reportes relacionados con plataformas digitales del gobierno, fallas en sistemas, trámites en línea y servicios digitales de la ciudad.', '55 3090 0500', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Plaza de la Constitución 1, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX', 
'https://www.adip.cdmx.gob.mx'),
(46, 'Guardia Nacional - Gobierno de México', 2, 'Atiende reportes de delitos federales, incluyendo robos en carreteras, transporte y zonas de jurisdicción federal. Apoya en operativos de seguridad.', '088', NULL, 'Las 24 horas, los 365 días del año.',
'Periférico Sur 3641, Colonia Fuentes del Pedregal, Alcaldía Tlalpan, C.P. 14140, Ciudad de México, CDMX', 
'https://www.gob.mx/gn'),
(47, 'PBI - Policía Bancaria e Industrial de la CDMX', 2, 'Brinda seguridad en bancos, empresas y zonas comerciales. Atiende reportes de robos en establecimientos y protege valores.', '55 5242 5100', NULL, 'Las 24 horas, los 365 días del año.',
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(48, 'UCS - Unidad de Contacto del Secretario de Seguridad Ciudadana', 2, 'Recibe denuncias ciudadanas de robo o asalto mediante redes sociales y atención directa. Canaliza reportes a las áreas correspondientes.', '55 5208 9898', NULL, 'Las 24 horas, los 365 días del año.',
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(49, 'FGJCDMX - Fiscalía de Robo', 2, 'Especializada en la investigación de robos a casa habitación, negocio, transporte y transeúnte. Integra carpetas de investigación.', '55 5200 9000', NULL, 'Las 24 horas, los 365 días del año.',
'Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(50, 'LOCATEL - Servicio Público de Localización Telefónica', 2, 'Brinda orientación y canalización a dependencias en caso de robo o asalto. Apoya con información inmediata y contacto con autoridades.', '55 5658 1111', NULL, 'Las 24 horas, los 365 días del año.',
'Avenida Universidad 1200, Colonia Xoco, Alcaldía Benito Juárez, C.P. 03330, Ciudad de México, CDMX', 
'https://www.locatel.cdmx.gob.mx'),
(51, 'Consejo Ciudadano - Seguridad y Justicia CDMX', 2, 'Brinda apoyo psicológico y asesoría legal a víctimas de robo o asalto. Permite realizar denuncias anónimas.', '55 5533 5533', 'contacto@consejociudadanomx.org', 'Las 24 horas, los 365 días del año.',
'Amberes 54, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.consejociudadanomx.org'),
(52, 'FEDA - Fiscalía Especializada en Delitos de Alto Impacto', 2, 'Atiende delitos graves como robo con violencia, asalto armado y crimen organizado. Realiza investigaciones especializadas.', '55 5200 9000', NULL, 'Las 24 horas, los 365 días del año.',
'Avenida Jardín 356, Colonia Del Gas, Alcaldía Azcapotzalco, C.P. 02950, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(53, 'SECGOB - Secretaría de Gobierno de la CDMX', 2, 'Canaliza reportes ciudadanos relacionados con seguridad, conflictos y delitos. Coordina acciones con dependencias de seguridad.', '55 5345 8000', NULL, 'Las 24 horas, los 365 días del año.',
'Plaza de la Constitución 1, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX', 
'https://www.secgob.cdmx.gob.mx'),
(54, 'Policía Preventiva - Secretaría de Seguridad Ciudadana', 2, 'Realiza patrullajes y atiende reportes de robo o asalto en vía pública. Es el primer contacto en emergencias de seguridad.', '911', NULL, 'Las 24 horas, los 365 días del año.',
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(55, 'FGJCDMX - Denuncia Digital', 2, 'Permite levantar denuncias en línea por robo sin violencia, extravío de documentos y otros delitos menores. Facilita el inicio de carpetas de investigación.', '55 5200 9000', NULL, 'Las 24 horas, los 365 días del año.',
'Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(56, 'SSC CDMX - Policía Cibernética', 2, 'Atiende reportes de fraudes electrónicos, robo de identidad, estafas en línea y delitos digitales relacionados con robo o engaño.', '55 5242 5100', 'policia.cibernetica@ssc.cdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(57, 'FGJCDMX - Fiscalía Transporte', 2, 'Atiende robos y asaltos ocurridos en transporte público como microbuses, metro y taxis. Realiza investigaciones especializadas.', '55 5200 9000', NULL, 'Las 24 horas, los 365 días del año.',
'Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(58, 'FGJCDMX - Fiscalía Territorial', 2, 'Atiende denuncias de robo o asalto según la zona territorial. Da seguimiento a carpetas de investigación en cada alcaldía.', '55 5200 9000', NULL, 'Las 24 horas, los 365 días del año.',
'Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(59, 'SEDENA - Secretaría de la Defensa Nacional', 2, 'Apoya en operativos de seguridad y combate a delitos de alto impacto, incluyendo robos con violencia en coordinación con autoridades civiles.', '55 5557 7888', NULL, 'Las 24 horas, los 365 días del año.',
'Boulevard Manuel Ávila Camacho S/N, Colonia Lomas de Sotelo, Alcaldía Miguel Hidalgo, C.P. 11200, Ciudad de México, CDMX', 
'https://www.gob.mx/sedena'),
(60, 'SEMAR - Secretaría de Marina', 2, 'Apoya en seguridad pública y operativos contra delitos en coordinación con autoridades locales y federales.', '55 5624 6500', NULL, 'Las 24 horas, los 365 días del año.',
'Eje 2 Oriente Tramo Heroica Escuela Naval Militar 861, Colonia Los Cipreses, Alcaldía Coyoacán, C.P. 04830, Ciudad de México, CDMX', 
'https://www.gob.mx/semar'),
(61, 'SFP - Secretaría de la Función Pública', 3, 'Atiende denuncias por actos de corrupción de servidores públicos federales, incluyendo faltas administrativas, abuso de funciones y conflictos de interés.', '55 2000 3000', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Insurgentes Sur 1735, Colonia Guadalupe Inn, Alcaldía Álvaro Obregón, C.P. 01020, Ciudad de México, CDMX', 
'https://www.gob.mx/sfp'),
(62, 'FECC - Fiscalía Especializada en Combate a la Corrupción', 3, 'Investiga delitos relacionados con corrupción a nivel federal, como soborno, peculado y enriquecimiento ilícito.', '55 5346 0000', NULL, 'Las 24 horas, todos los días.', 
'Avenida Paseo de la Reforma 211-213, Colonia Cuauhtémoc, Alcaldía Cuauhtémoc, C.P. 06500, Ciudad de México, CDMX', 
'https://www.gob.mx/fgr'),
(63, 'TJACDMX - Tribunal de Justicia Administrativa de la Ciudad de México', 3, 'Resuelve controversias entre ciudadanos y autoridades administrativas, incluyendo sanciones por faltas graves de servidores públicos.', '55 5130 1900', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Insurgentes Sur 825, Colonia Nápoles, Alcaldía Benito Juárez, C.P. 03810, Ciudad de México, CDMX', 
'https://www.tjacdmx.gob.mx'),
(64, 'CJCDMX - Consejo de la Judicatura de la Ciudad de México', 3, 'Supervisa la conducta de jueces y personal judicial, recibiendo quejas por irregularidades o malas prácticas dentro del sistema judicial.', '55 9157 0000', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Niños Héroes 132, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.poderjudicialcdmx.gob.mx'),
(65, 'CNDH - Comisión Nacional de los Derechos Humanos', 3, 'Atiende quejas por violaciones a derechos humanos cometidas por autoridades, incluyendo abuso de poder y negligencia.', '800 715 2000', NULL, 'Las 24 horas, todos los días.', 
'Periférico Sur 3469, Colonia San Jerónimo Lídice, Alcaldía Magdalena Contreras, C.P. 10200, Ciudad de México, CDMX', 
'https://www.cndh.org.mx'),
(66, 'UIF - Unidad de Inteligencia Financiera', 3, 'Investiga operaciones financieras ilícitas relacionadas con corrupción, lavado de dinero y enriquecimiento indebido de funcionarios.', '55 3688 4500', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Constituyentes 1001, Colonia Belén de las Flores, Alcaldía Álvaro Obregón, C.P. 01110, Ciudad de México, CDMX', 
'https://www.gob.mx/uif'),
(67, 'PDN - Plataforma Digital Nacional', 3, 'Permite consultar y reportar información relacionada con servidores públicos, declaraciones patrimoniales y posibles actos de corrupción.', '55 2000 3000', NULL, 'Las 24 horas, todos los días.', 
'Avenida Insurgentes Sur 1735, Colonia Guadalupe Inn, Alcaldía Álvaro Obregón, C.P. 01020, Ciudad de México, CDMX', 
'https://www.plataformadigitalnacional.org'),
(68, 'CPC - Comité de Participación Ciudadana del Sistema Anticorrupción de la CDMX', 3, 'Canaliza denuncias ciudadanas sobre corrupción y promueve la participación social en el combate a prácticas indebidas en el gobierno.', '55 5130 1500', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida 20 de Noviembre 700, Colonia Huichapan, Alcaldía Xochimilco, C.P. 16050, Ciudad de México, CDMX', 
'https://www.sacdmx.org'),
(69, 'FECC-CDMX - Fiscalía Especializada en Combate a la Corrupción de la Ciudad de México', 3, 'Investiga delitos de corrupción cometidos por servidores públicos locales, incluyendo cohecho, abuso de funciones y desvío de recursos.', '55 5200 9000', NULL, 'Las 24 horas, todos los días.', 
'Avenida Dr. Río de la Loza 156, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(70, 'SNA - Sistema Nacional Anticorrupción', 3, 'Coordina políticas públicas para prevenir, detectar y sancionar faltas administrativas y hechos de corrupción a nivel nacional.', '55 2000 3000', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida Insurgentes Sur 1735, Colonia Guadalupe Inn, Alcaldía Álvaro Obregón, C.P. 01020, Ciudad de México, CDMX', 
'https://www.gob.mx/sna'),
(71, 'OIC-SSC - Órgano Interno de Control en la Secretaría de Seguridad Ciudadana', 3, 'Supervisa la actuación de elementos de seguridad y recibe denuncias por abuso de autoridad, corrupción o conductas indebidas.', '55 5242 5100', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(72, 'FGJCDMX - Visitaduría General', 3, 'Investiga irregularidades cometidas por personal ministerial, pericial y policial dentro de la fiscalía. Atiende quejas internas y ciudadanas.', '55 5200 9000', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(73, 'UAI-SSC - Unidad de Asuntos Internos de la Secretaría de Seguridad Ciudadana', 3, 'Investiga conductas indebidas de policías, incluyendo corrupción, abuso de autoridad y omisión en el cumplimiento de funciones.', '55 5242 5100', NULL, 'Las 24 horas, todos los días.', 
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(74, 'PFCDMX - Procuraduría Fiscal de la Ciudad de México', 3, 'Atiende irregularidades fiscales y actos indebidos relacionados con el manejo de recursos públicos en materia tributaria.', '55 5134 2500', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Doctor Lavista 144, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.finanzas.cdmx.gob.mx'),
(75, 'SESACDMX - Secretaría Ejecutiva del Sistema Anticorrupción de la Ciudad de México', 3, 'Coordina acciones del sistema anticorrupción local y recibe reportes ciudadanos sobre posibles actos de corrupción.', '55 5130 1500', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Avenida 20 de Noviembre 700, Colonia Huichapan, Alcaldía Xochimilco, C.P. 16050, Ciudad de México, CDMX', 
'https://www.sacdmx.org'),
(76, 'CONAPRED - Consejo Nacional para Prevenir la Discriminación', 4, 'Atiende denuncias por discriminación y violencia de género en ámbitos institucionales y sociales.', '800 543 0033', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Londres 247, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.conapred.org.mx'),
(77, 'PCCDMX - Policía Cibernética de la Ciudad de México', 4, 'Atiende casos de violencia digital, acoso, sextorsión y amenazas en línea contra mujeres.', '55 5242 5100', 'policia.cibernetica@ssp.df.gob.mx', 'Las 24 horas, todos los días.', 
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.ssc.cdmx.gob.mx'),
(78, 'CAVI - Centro de Atención a la Violencia Intrafamiliar', 4, 'Brinda atención psicológica, legal y social a víctimas de violencia familiar y de género.', '55 5200 9000', NULL, 'Lunes a viernes de 09:00 a 19:00 horas.', 
'Dr. Río de la Loza 156, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(79, 'IFPES - Instituto de Formación Profesional y Estudios Superiores', 4, 'Capacita a servidores públicos y recibe reportes relacionados con actuación indeb en casos de violencia de género.', '55 5345 5901', 'ifpes@fjgcdmx.gob.mx', 'Lunes a viernes de 09:00 a 21:00 horas.', 
'4ta Cerrada de Avenida Jardín, Colonia Ampliación Cosmopolita, Alcaldía Azcapotzalco, C.P. 02920, Ciudad de México, CDMX', 
'https://ifpes.fgjcdmx.gob.mx'),
(80, 'SEDESA - Secretaría de Salud de la Ciudad de México', 4, 'Ofrece atención médica, psicológica y seguimiento a víctimas de violencia de género en hospitales públicos.', '55 5132 1250', NULL, 'Las 24 horas, todos los días.', 
'Avenida Insurgentes Norte 423, Colonia Nonoalco Tlatelolco, Alcaldía Cuauhtémoc, C.P. 06900, Ciudad de México, CDMX', 
'https://www.salud.cdmx.gob.mx'),
(81, 'PDI - Policía de Investigación (Atención a Víctimas)', 4, 'Apoya en la investigación de delitos de violencia de género y protección de víctimas.', '55 5200 9000', NULL, 'Las 24 horas, todos los días.', 
'Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(82, 'CEAVI-CDMX - Comisión Ejecutiva de Atención a Víctimas de la Ciudad de México', 4, 'Brinda atención integral a víctimas de violencia de género en el ámbito local.', '55 5345 5060', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'República de Cuba 43, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX', 
'https://www.ceavi.cdmx.gob.mx'),
(83, 'RIR - Red Intercultural de Refugios', 4, 'Ofrece refugio y protección a mujeres víctimas de violencia en contextos interculturales.', '800 836 8880', NULL, 'Las 24 horas, todos los días.', 
'Dirección confidencial por seguridad de las víctimas, Ciudad de México, CDMX', 
'https://www.gob.mx'),
(84, 'CCSJCDMX - Consejo Ciudadano para la Seguridad y Justicia de la Ciudad de México', 4, 'Brinda atención psicológica, asesoría legal y acompañamiento a víctimas de violencia de género. Permite denuncias anónimas y canalización inmediata.', '55 5533 5533', 'contacto@consejociudadanomx.org', 'Las 24 horas, todos los días.', 
'Amberes 54, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX', 
'https://www.consejociudadanomx.org'),
(85, 'CEAV - Comisión Ejecutiva de Atención a Víctimas', 4, 'Proporciona atención integral a víctimas de delitos, incluyendo violencia de género, con apoyo psicológico, legal y compensación.', '800 842 8462', NULL, 'Las 24 horas, todos los días.', 
'Ángel Urraza 1137, Colonia Del Valle Centro, Alcaldía Benito Juárez, C.P. 03100, Ciudad de México, CDMX', 
'https://www.gob.mx/ceav'),
(86, 'CONAVIM - Comisión Nacional para Prevenir y Erradicar la Violencia contra las Mujeres', 4, 'Diseña políticas públicas y coordina acciones para prevenir y erradicar la violencia contra mujeres en todo el país.', '55 5209 8800', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.', 
'Dr. José María Vértiz 852, Colonia Narvarte Poniente, Alcaldía Benito Juárez, C.P. 03020, Ciudad de México, CDMX', 
'https://www.gob.mx/conavim'),
(87, 'INMUJERES - Instituto Nacional de las Mujeres', 4, 'Promueve la igualdad de género y atiende situaciones de violencia contra mujeres mediante orientación y canalización.', '800 911 2511', NULL, 'Las 24 horas, todos los días.', 
'Barranca del Muerto 209, Colonia San José Insurgentes, Alcaldía Benito Juárez, C.P. 03900, Ciudad de México, CDMX', 
'https://www.gob.mx/inmujeres'),
(88, 'LOCATEL-MUJERES - Línea Mujeres LOCATEL', 4, 'Línea especializada que brinda orientación, contención emocional y canalización a mujeres víctimas de violencia.', '*765', NULL, 'Las 24 horas, todos los días.', 
'Avenida Universidad 1200, Colonia Xoco, Alcaldía Benito Juárez, C.P. 03330, Ciudad de México, CDMX', 
'https://www.locatel.cdmx.gob.mx'),
(89, 'UNAVI - Unidad de Atención a la Violencia Familiar', 4, 'Brinda atención psicológica, asesoría legal y acompañamiento a víctimas de violencia familiar en coordinación con autoridades.', '55 5200 9000', NULL, 'Las 24 horas, todos los días.', 
'Digna Ochoa y Plácido, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX', 
'https://www.fgjcdmx.gob.mx'),
(90, 'CDHCM - Comisión de Derechos Humanos de la Ciudad de México', 4, 'Atiende quejas por violaciones a derechos humanos, incluyendo violencia institucional y de género.', '55 5229 5600', NULL, 'Las 24 horas, todos los días.', 
'Avenida Universidad 1449, Colonia Florida, Alcaldía Álvaro Obregón, C.P. 01030, Ciudad de México, CDMX', 
'https://www.cdhcm.org.mx'),
(91, 'FGJCDMX - Fiscalía General de Justicia de la Ciudad de México', 5, 'Recibe denuncias de delitos en general, incluyendo narcomenudeo, y las canaliza a fiscalías especializadas.', '55 5200 9000', 'gestion_fiscal@fgjcdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Digna Ochoa y Plácido 56, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX',
'https://www.fgjcdmx.gob.mx'),
(92, 'FIDAI - Fiscalía de Delitos de Alto Impacto', 5, 'Atiende delitos de alto impacto, incluyendo redes de narcomenudeo vinculadas a crimen organizado.', '55 5346 8800', 'jose_onofre@fgjcdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Av. Jardín 356, Colonia Del Gas, Alcaldía Azcapotzalco, C.P. 02950, Ciudad de México, CDMX',
'https://www.fgjcdmx.gob.mx'),
(93, 'PDI - Policía de Investigación (FGJCDMX)', 5, 'Apoya en investigaciones de delitos, incluyendo narcomenudeo, mediante trabajo de campo e inteligencia.', '55 5200 9000', 'gestion_fiscal@fgjcdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Dr. Lavista 139, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México, CDMX',
'https://www.fgjcdmx.gob.mx'),
(94, 'CCSJ - Consejo Ciudadano para la Seguridad y Justicia de la CDMX', 5, 'Recibe denuncias anónimas sobre delitos, incluyendo narcomenudeo, y brinda orientación jurídica y psicológica.', '55 5533 5533', 'consejociudadano@fgjcdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Amberes 54, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX',
'https://www.consejociudadanomx.org'),
(95, '089 - Denuncia Anónima', 5, 'Línea nacional para reportar de forma anónima delitos como narcomenudeo sin proporcionar datos personales.', '089', NULL, 'Las 24 horas, los 365 días del año.',
'Servicio telefónico nacional (sin dirección física)',
'https://www.gob.mx/secretariadoejecutivo'),
(96, 'FGR - Fiscalía General de la República', 5, 'Atiende delitos federales relacionados con drogas y puede atraer casos de narcomenudeo vinculados a redes mayores.', '800 890 9780', NULL, 'Las 24 horas, los 365 días del año.',
'Av. Insurgentes Sur 20, Colonia Roma Norte, Alcaldía Cuauhtémoc, C.P. 06700, Ciudad de México, CDMX',
'https://www.gob.mx/fgr'),
(97, 'PC - Policía Cibernética CDMX', 5, 'Atiende denuncias relacionadas con venta de drogas en línea y redes sociales.', '55 5242 5100', 'ucontacto@ssc.cdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Liverpool 136, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México, CDMX',
'https://www.ssc.cdmx.gob.mx'),
(98, 'UCS - Unidades de Contacto del Secretario', 5, 'Módulos donde ciudadanos pueden reportar delitos directamente a mandos policiales.', '55 5242 5100', 'ucontacto@ssc.cdmx.gob.mx', 'Lunes a domingo de 08:00 a 20:00 horas.',
'Cuauhtémoc: Eje Central Lázaro Cárdenas 898, Col. Narvarte Poniente; Iztapalapa: Anillo Periférico Canal de Garay S/N, Col. Chinampac de Juárez; Gustavo A. Madero: Av. Vicente Villada 1000; Álvaro Obregón: Calle 10 y Canario S/N; Coyoacán: Calzada de Tlalpan 2700, Ciudad de México, CDMX',
'https://www.ssc.cdmx.gob.mx'),
(99, 'MP - Ministerio Público CDMX', 5, 'Recibe denuncias formales de delitos, incluyendo narcomenudeo, e inicia carpetas de investigación.', '55 5200 9000', 'gestion_fiscal@fgjcdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Cuauhtémoc: Digna Ochoa 56, Col. Doctores; Iztapalapa: Eje 6 Sur S/N, Col. San José Aculco; GAM: Av. Eduardo Molina S/N; Álvaro Obregón: Av. Toluca 115; Coyoacán: Calzada de Tlalpan 2962, Ciudad de México, CDMX',
'https://www.fgjcdmx.gob.mx'),
(100, 'SEMAR - Secretaría de Marina', 5, 'Participa en operativos contra el narcotráfico y puede recibir información ciudadana.', '800 627 4621', NULL, 'Las 24 horas, los 365 días del año.',
'Eje 2 Oriente Heroica Escuela Naval Militar 861, Colonia Los Cipreses, Alcaldía Coyoacán, C.P. 04830, Ciudad de México, CDMX',
'https://www.gob.mx/semar'),
(101, 'C5 - Centro de Comando, Control, Cómputo, Comunicaciones y Contacto Ciudadano', 5, 'Recibe reportes ciudadanos y coordina la atención inmediata con cuerpos de seguridad.', '911', NULL, 'Las 24 horas, los 365 días del año.',
'Av. Canal de Garay 260, Colonia Tepalcates, Alcaldía Iztapalapa, C.P. 09210, Ciudad de México, CDMX',
'https://www.c5.cdmx.gob.mx'),
(102, 'FGJCDMX - Denuncia Digital', 5, 'Plataforma en línea para levantar denuncias relacionadas con delitos.', NULL, 'gestion_fiscal@fgjcdmx.gob.mx', 'Las 24 horas, los 365 días del año.',
'Plataforma digital (sin ubicación física)',
'https://www.fgjcdmx.gob.mx'),
(103, 'LOCATEL - Localización Telefónica', 5, 'Brinda orientación y canaliza reportes ciudadanos hacia autoridades correspondientes.', '55 5658 1111', NULL, 'Las 24 horas, los 365 días del año.',
'Av. Patriotismo 230, Colonia San Pedro de los Pinos, Alcaldía Benito Juárez, C.P. 03800, Ciudad de México, CDMX',
'https://www.locatel.cdmx.gob.mx'),
(104, 'CDHCM - Comisión de Derechos Humanos de la CDMX', 5, 'Atiende quejas relacionadas con abusos en operativos y orienta a denunciantes.', '55 5229 5600', NULL, 'Las 24 horas, los 365 días del año.',
'Av. Universidad 1449, Colonia Pueblo Axotla, Alcaldía Álvaro Obregón, C.P. 01030, Ciudad de México, CDMX',
'https://cdhcm.org.mx'),
(105, 'ADIP - Agencia Digital de Innovación Pública', 5, 'Administra plataformas digitales de reporte ciudadano.', NULL, NULL, 'Lunes a domingo, de 08:00 a 20:00 horas.',
'Plaza de la Constitución 1, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México, CDMX',
'https://www.adip.cdmx.gob.mx'),
(106, 'SACMEX - Sistema de Aguas de la Ciudad de México', 6, 'Atiende reportes sobre fugas de agua, baja presión, drenaje, encharcamientos y problemas de suministro.', '*426 / 55 5654 3210', NULL, 'Las 24 horas, los 365 días del año.',
'Río de la Plata 48, Colonia Cuauhtémoc, Alcaldía Cuauhtémoc, C.P. 06500, Ciudad de México',
'https://www.sacmex.cdmx.gob.mx'),
(107, 'SOBSE - Secretaría de Obras y Servicios de la Ciudad de México', 6, 'Recibe reportes sobre baches, alumbrado público, mantenimiento urbano y vialidades.', '55 5345 8000', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Avenida Universidad 800, Colonia Santa Cruz Atoyac, Alcaldía Benito Juárez, C.P. 03310, Ciudad de México',
'https://www.obras.cdmx.gob.mx'),
(108, 'SEDEMA - Secretaría del Medio Ambiente de la Ciudad de México', 6, 'Atiende reportes sobre contaminación ambiental, verificación vehicular y áreas verdes.', '55 5278 9931', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Plaza de la Constitución 1, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México',
'https://www.sedema.cdmx.gob.mx'),
(109, 'ADIP - Agencia Digital de Innovación Pública', 6, 'Gestiona la atención ciudadana digital y reportes mediante plataformas tecnológicas.', NULL, NULL, 'Atención digital 24/7',
'Plaza de la Constitución 2, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06000, Ciudad de México',
'https://adip.cdmx.gob.mx'),
(110, 'CFE - Comisión Federal de Electricidad', 6, 'Atiende reportes sobre fallas eléctricas, apagones y problemas de suministro.', '071', NULL, 'Las 24 horas, los 365 días del año.',
'Avenida Paseo de la Reforma 164, Colonia Juárez, Alcaldía Cuauhtémoc, C.P. 06600, Ciudad de México',
'https://www.cfe.mx'),
(111, 'Alcaldías de la Ciudad de México', 6, 'Reciben reportes vecinales sobre servicios urbanos, mantenimiento y espacios públicos.', NULL, NULL, 'Lunes a viernes de 09:00 a 14:00 horas.',
'Diversas sedes: Canario s/n Col. Tolteca (Álvaro Obregón); División del Norte 1611 Col. Santa Cruz Atoyac (Benito Juárez); Parque Lira 94 Col. Observatorio (Miguel Hidalgo); y demás alcaldías en CDMX',
'https://www.cdmx.gob.mx/alcaldias'),
(112, 'INVEA - Instituto de Verificación Administrativa', 6, 'Recibe reportes sobre establecimientos mercantiles y uso de suelo.', '55 4737 7700', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Calle Carolina 132, Colonia Nochebuena, Alcaldía Benito Juárez, C.P. 03720, Ciudad de México',
'https://www.invea.cdmx.gob.mx'),
(113, 'STC Metro', 6, 'Atiende reportes sobre fallas en estaciones, trenes y servicios del Metro.', '55 5627 4950', NULL, 'Diario de 05:00 a 24:00 horas.',
'Avenida Delicias 67, Colonia Centro, Alcaldía Cuauhtémoc, C.P. 06070, Ciudad de México',
'https://www.metro.cdmx.gob.mx'),
(114, 'Metrobús CDMX', 6, 'Recibe reportes sobre operación, estaciones y unidades del Metrobús.', '55 5761 6858', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Avenida Cuauhtémoc 16, Colonia Doctores, Alcaldía Cuauhtémoc, C.P. 06720, Ciudad de México',
'https://www.metrobus.cdmx.gob.mx'),
(115, 'RTP - Red de Transporte de Pasajeros', 6, 'Atiende reportes sobre rutas, unidades y servicio de transporte RTP.', '55 1328 6300', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Calzada de Tlalpan 3465, Colonia Santa Úrsula Coapa, Alcaldía Coyoacán, C.P. 04850, Ciudad de México',
'https://www.rtp.cdmx.gob.mx'),
(116, 'PROSOC - Procuraduría Social de la Ciudad de México', 6, 'Atiende conflictos vecinales y condominales.', '55 5128 5210', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Calle Mitla 250, Colonia Vértiz Narvarte, Alcaldía Benito Juárez, C.P. 03600, Ciudad de México',
'https://www.prosoc.cdmx.gob.mx'),
(117, 'CDHCM - Comisión de Derechos Humanos de la Ciudad de México', 6, 'Recibe quejas por violaciones a derechos humanos.', '55 5229 5600', 'contacto@cdhcm.org.mx', 'Las 24 horas, los 365 días del año.',
'Avenida Universidad 1449, Colonia Pueblo Axotla, Alcaldía Álvaro Obregón, C.P. 01030, Ciudad de México',
'https://cdhcm.org.mx'),
(118, 'IAPA - Instituto para la Atención y Prevención de las Adicciones', 6, 'Brinda orientación sobre adicciones y canalización a tratamiento.', '55 4631 3035', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Avenida Río Mixcoac 234, Colonia Acacias, Alcaldía Benito Juárez, C.P. 03240, Ciudad de México',
'https://www.iapa.cdmx.gob.mx'),
(119, 'DIF CDMX', 6, 'Atiende reportes sobre asistencia social y apoyo a población vulnerable.', '55 8957 3450', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Avenida San Francisco 1374, Colonia Tlacoquemécatl del Valle, Alcaldía Benito Juárez, C.P. 03200, Ciudad de México',
'https://www.dif.cdmx.gob.mx'),
(120, 'INJUVE - Instituto de la Juventud de la Ciudad de México', 6, 'Atiende programas, reportes y servicios dirigidos a jóvenes.', '55 5341 7488', NULL, 'Lunes a viernes de 09:00 a 18:00 horas.',
'Calzada México-Tacuba 235, Colonia Un Hogar para Nosotros, Alcaldía Miguel Hidalgo, C.P. 11330, Ciudad de México',
'https://www.injuve.cdmx.gob.mx');