INSERT INTO ReporteNarcomenudeo (ReporteId,TipoActividadSospechosa,NumeroPersonasInvolucradas,DescripcionPersonasInvolucradas,VehiculosRelacionados,FrecuenciaSuceso)
VALUES
(5251,'Venta cerca de escuela',NULL,'Punto de reunión con entregas constantes','Motocicleta','Diario'),
(5252,'Venta de drogas en vía pública',7,'Dos personas realizando entregas rápidas','Camioneta','Varias veces por semana'),
(5253,'Puntos de venta recurrentes',5,'Persona recibiendo efectivo y entregando bolsitas','Sin placas','Ocasional'),
(5254,'Intercambio sospechoso de paquetes',5,'Punto de reunión con entregas constantes','Motocicleta','Fines de semana'),
(5255,'Puntos de venta recurrentes',3,'Hombre con gorra negra entregando paquetes',NULL,'Fines de semana'),
(5256,'Venta de drogas en vía pública',4,'Persona vigilando en la esquina','Bicicleta','Fines de semana'),
(5257,'Intercambio sospechoso de paquetes',2,'Dos personas realizando entregas rápidas','Moto','Ocasional'),
(5258,'Distribución desde vehículo',4,'Punto de reunión con entregas constantes','Camioneta','Fines de semana'),
(5259,'Distribución desde vehículo',NULL,'Punto de reunión con entregas constantes','Bicicleta','Cada noche'),
(5260,'Puntos de venta recurrentes',3,'Persona vigilando en la esquina',NULL,'Ocasional'),
(5261,'Entrega rápida a transeúntes',5,'Grupo de 3 personas intercambiando bolsitas',NULL,'Ocasional'),
(5262,'Entrega rápida a transeúntes',NULL,'Entrega de paquetes cerca de la entrada principal',NULL,'Varias veces por semana'),
(5263,'Entrega rápida a transeúntes',NULL,'Grupo de 3 personas intercambiando bolsitas','Camioneta','Varias veces por semana'),
(5264,'Intercambio sospechoso de paquetes',6,'Dos personas realizando entregas rápidas','Automóvil','Ocasional'),
(5265,'Entrega rápida a transeúntes',6,'Punto de reunión con entregas constantes',NULL,'Ocasional'),
(5266,'Venta de drogas en vía pública',4,'Venta a transeúntes con señas discretas','Camioneta','Diario'),
(5267,'Venta cerca de escuela',7,'Dos personas realizando entregas rápidas',NULL,'Fines de semana'),
(5268,'Intercambio sospechoso de paquetes',NULL,'Presunto punto fijo con flujo continuo de compradores','Camioneta','Fines de semana'),
(5269,'Puntos de venta recurrentes',NULL,'Intercambio rápido de paquetes en la banqueta','Motocicleta','Diario'),
(5270,'Entrega rápida a transeúntes',7,'Entrega de paquetes cerca de la entrada principal','Motocicleta','Ocasional'),
(5271,'Intercambio sospechoso de paquetes',6,'Intercambio rápido de paquetes en la banqueta','Motocicleta','Cada noche'),
(5272,'Entrega rápida a transeúntes',NULL,'Punto de reunión con entregas constantes',NULL,'Fines de semana'),
(5273,'Intercambio sospechoso de paquetes',4,'Persona recibiendo efectivo y entregando bolsitas',NULL,'Cada noche'),
(5274,'Distribución desde vehículo',7,'Grupo de 3 personas intercambiando bolsitas','Sin placas','Diario'),
(5275,'Puntos de venta recurrentes',6,'Presunto punto fijo con flujo continuo de compradores','Camioneta','Diario'),
(5276,'Venta de drogas en vía pública',7,'Dos personas realizando entregas rápidas','Bicicleta','Varias veces por semana'),
(5277,'Distribución desde vehículo',5,'Presunto punto fijo con flujo continuo de compradores','Sin placas','Diario'),
(5278,'Distribución desde vehículo',6,'Presunto punto fijo con flujo continuo de compradores',NULL,'Ocasional'),
(5279,'Venta de drogas en vía pública',2,'Venta a transeúntes con señas discretas','Camioneta','Cada noche'),
(5280,'Entrega rápida a transeúntes',4,'Venta a transeúntes con señas discretas','Camioneta','Diario'),
(5281,'Puntos de venta recurrentes',NULL,'Persona vigilando en la esquina','Bicicleta','Cada noche'),
(5282,'Puntos de venta recurrentes',5,'Hombre con gorra negra entregando paquetes','Moto','Ocasional'),
(5283,'Venta de drogas en vía pública',5,'Persona vigilando en la esquina','Camioneta','Ocasional'),
(5284,'Venta de drogas en vía pública',8,'Punto de reunión con entregas constantes','Bicicleta','Fines de semana'),
(5285,'Entrega rápida a transeúntes',2,'Persona recibiendo efectivo y entregando bolsitas','Taxi','Fines de semana'),
(5286,'Entrega rápida a transeúntes',NULL,'Grupo de 3 personas intercambiando bolsitas','Sin placas','Ocasional'),
(5287,'Puntos de venta recurrentes',2,'Entrega de paquetes cerca de la entrada principal',NULL,'Cada noche'),
(5288,'Venta cerca de escuela',5,'Intercambio rápido de paquetes en la banqueta','Sin placas','Ocasional'),
(5289,'Intercambio sospechoso de paquetes',2,'Presunto punto fijo con flujo continuo de compradores',NULL,'Varias veces por semana'),
(5290,'Venta de drogas en vía pública',5,'Hombre con gorra negra entregando paquetes','Bicicleta','Diario'),
(5291,'Intercambio sospechoso de paquetes',NULL,'Entrega de paquetes cerca de la entrada principal','Motocicleta','Fines de semana'),
(5292,'Venta de drogas en vía pública',3,'Intercambio rápido de paquetes en la banqueta','Bicicleta','Ocasional'),
(5293,'Distribución desde vehículo',7,'Presunto punto fijo con flujo continuo de compradores',NULL,'Diario'),
(5294,'Puntos de venta recurrentes',8,'Entrega de paquetes cerca de la entrada principal','Taxi','Fines de semana'),
(5295,'Intercambio sospechoso de paquetes',4,'Dos personas realizando entregas rápidas','Bicicleta','Cada noche'),
(5296,'Distribución desde vehículo',6,'Punto de reunión con entregas constantes','Taxi','Cada noche'),
(5297,'Entrega rápida a transeúntes',8,'Grupo de 3 personas intercambiando bolsitas','Camioneta','Ocasional'),
(5298,'Intercambio sospechoso de paquetes',7,'Dos personas realizando entregas rápidas',NULL,'Ocasional'),
(5299,'Venta de drogas en vía pública',7,'Hombre con gorra negra entregando paquetes',NULL,'Ocasional'),
(5300,'Venta cerca de escuela',8,'Venta a transeúntes con señas discretas',NULL,'Varias veces por semana'),
(5301,'Venta cerca de escuela',8,'Punto de reunión con entregas constantes','Camioneta','Varias veces por semana'),
(5302,'Distribución desde vehículo',4,'Grupo de 3 personas intercambiando bolsitas',NULL,'Ocasional'),
(5303,'Entrega rápida a transeúntes',8,'Hombre con gorra negra entregando paquetes','Sin placas','Diario'),
(5304,'Puntos de venta recurrentes',6,'Presunto punto fijo con flujo continuo de compradores','Moto','Ocasional'),
(5305,'Puntos de venta recurrentes',5,'Dos personas realizando entregas rápidas','Motocicleta','Ocasional'),
(5306,'Venta de drogas en vía pública',4,'Punto de reunión con entregas constantes',NULL,'Fines de semana'),
(5307,'Distribución desde vehículo',3,'Dos personas realizando entregas rápidas',NULL,'Diario'),
(5308,'Entrega rápida a transeúntes',7,'Dos personas realizando entregas rápidas',NULL,'Ocasional'),
(5309,'Entrega rápida a transeúntes',8,'Entrega de paquetes cerca de la entrada principal',NULL,'Ocasional'),
(5310,'Distribución desde vehículo',5,'Punto de reunión con entregas constantes','Camioneta','Cada noche'),
(5311,'Venta de drogas en vía pública',6,'Dos personas realizando entregas rápidas',NULL,'Diario'),
(5312,'Entrega rápida a transeúntes',3,'Punto de reunión con entregas constantes',NULL,'Diario'),
(5313,'Venta cerca de escuela',6,'Dos personas realizando entregas rápidas',NULL,'Ocasional'),
(5314,'Venta de drogas en vía pública',3,'Dos personas realizando entregas rápidas','Moto','Diario'),
(5315,'Venta de drogas en vía pública',3,'Entrega de paquetes cerca de la entrada principal','Motocicleta','Ocasional'),
(5316,'Distribución desde vehículo',NULL,'Dos personas realizando entregas rápidas','Taxi','Cada noche'),
(5317,'Puntos de venta recurrentes',5,'Persona vigilando en la esquina',NULL,'Fines de semana'),
(5318,'Venta cerca de escuela',8,'Dos personas realizando entregas rápidas','Motocicleta','Fines de semana'),
(5319,'Puntos de venta recurrentes',2,'Entrega de paquetes cerca de la entrada principal','Sin placas','Fines de semana'),
(5320,'Venta cerca de escuela',3,'Persona vigilando en la esquina','Automóvil','Fines de semana'),
(5321,'Venta cerca de escuela',6,'Entrega de paquetes cerca de la entrada principal','Sin placas','Diario'),
(5322,'Intercambio sospechoso de paquetes',7,'Persona recibiendo efectivo y entregando bolsitas','Sin placas','Fines de semana'),
(5323,'Entrega rápida a transeúntes',2,'Dos personas realizando entregas rápidas','Bicicleta','Cada noche'),
(5324,'Venta cerca de escuela',NULL,'Presunto punto fijo con flujo continuo de compradores','Sin placas','Varias veces por semana'),
(5325,'Distribución desde vehículo',7,'Persona recibiendo efectivo y entregando bolsitas','Motocicleta','Fines de semana'),
(5326,'Puntos de venta recurrentes',8,'Presunto punto fijo con flujo continuo de compradores','Motocicleta','Varias veces por semana'),
(5327,'Entrega rápida a transeúntes',8,'Persona vigilando en la esquina',NULL,'Ocasional'),
(5328,'Entrega rápida a transeúntes',NULL,'Persona recibiendo efectivo y entregando bolsitas','Bicicleta','Fines de semana'),
(5329,'Venta de drogas en vía pública',2,'Hombre con gorra negra entregando paquetes','Automóvil','Fines de semana'),
(5330,'Distribución desde vehículo',3,'Grupo de 3 personas intercambiando bolsitas',NULL,'Varias veces por semana'),
(5331,'Distribución desde vehículo',NULL,'Entrega de paquetes cerca de la entrada principal',NULL,'Fines de semana'),
(5332,'Venta cerca de escuela',NULL,'Persona vigilando en la esquina','Sin placas','Diario'),
(5333,'Venta cerca de escuela',4,'Entrega de paquetes cerca de la entrada principal','Sin placas','Ocasional'),
(5334,'Intercambio sospechoso de paquetes',NULL,'Grupo de 3 personas intercambiando bolsitas','Moto','Ocasional'),
(5335,'Puntos de venta recurrentes',NULL,'Venta a transeúntes con señas discretas',NULL,'Varias veces por semana'),
(5336,'Venta de drogas en vía pública',4,'Presunto punto fijo con flujo continuo de compradores','Sin placas','Diario'),
(5337,'Puntos de venta recurrentes',5,'Entrega de paquetes cerca de la entrada principal','Motocicleta','Varias veces por semana'),
(5338,'Distribución desde vehículo',2,'Presunto punto fijo con flujo continuo de compradores','Moto','Cada noche'),
(5339,'Venta cerca de escuela',5,'Persona vigilando en la esquina',NULL,'Diario'),
(5340,'Distribución desde vehículo',5,'Persona recibiendo efectivo y entregando bolsitas',NULL,'Ocasional'),
(5341,'Venta cerca de escuela',NULL,'Persona recibiendo efectivo y entregando bolsitas',NULL,'Fines de semana'),
(5342,'Intercambio sospechoso de paquetes',6,'Punto de reunión con entregas constantes',NULL,'Diario'),
(5343,'Distribución desde vehículo',2,'Presunto punto fijo con flujo continuo de compradores','Taxi','Fines de semana'),
(5344,'Entrega rápida a transeúntes',8,'Persona recibiendo efectivo y entregando bolsitas','Sin placas','Fines de semana'),
(5345,'Puntos de venta recurrentes',4,'Persona vigilando en la esquina','Sin placas','Cada noche'),
(5346,'Intercambio sospechoso de paquetes',3,'Intercambio rápido de paquetes en la banqueta','Camioneta','Cada noche'),
(5347,'Entrega rápida a transeúntes',3,'Dos personas realizando entregas rápidas',NULL,'Diario'),
(5348,'Distribución desde vehículo',4,'Entrega de paquetes cerca de la entrada principal','Moto','Diario'),
(5349,'Entrega rápida a transeúntes',NULL,'Venta a transeúntes con señas discretas','Automóvil','Fines de semana'),
(5350,'Entrega rápida a transeúntes',4,'Grupo de 3 personas intercambiando bolsitas','Moto','Cada noche'),
(5351,'Puntos de venta recurrentes',8,'Persona vigilando en la esquina','Moto','Ocasional'),
(5352,'Distribución desde vehículo',6,'Intercambio rápido de paquetes en la banqueta','Motocicleta','Ocasional'),
(5353,'Intercambio sospechoso de paquetes',2,'Punto de reunión con entregas constantes',NULL,'Diario'),
(5354,'Venta de drogas en vía pública',7,'Persona recibiendo efectivo y entregando bolsitas','Bicicleta','Fines de semana'),
(5355,'Puntos de venta recurrentes',6,'Persona vigilando en la esquina','Bicicleta','Cada noche'),
(5356,'Entrega rápida a transeúntes',NULL,'Presunto punto fijo con flujo continuo de compradores','Automóvil','Cada noche'),
(5357,'Distribución desde vehículo',6,'Intercambio rápido de paquetes en la banqueta','Automóvil','Diario'),
(5358,'Venta cerca de escuela',NULL,'Persona recibiendo efectivo y entregando bolsitas',NULL,'Fines de semana'),
(5359,'Intercambio sospechoso de paquetes',6,'Entrega de paquetes cerca de la entrada principal','Sin placas','Fines de semana'),
(5360,'Distribución desde vehículo',7,'Hombre con gorra negra entregando paquetes','Taxi','Diario'),
(5361,'Venta de drogas en vía pública',4,'Hombre con gorra negra entregando paquetes',NULL,'Diario'),
(5362,'Intercambio sospechoso de paquetes',2,'Dos personas realizando entregas rápidas','Moto','Fines de semana'),
(5363,'Entrega rápida a transeúntes',NULL,'Punto de reunión con entregas constantes','Motocicleta','Cada noche'),
(5364,'Venta cerca de escuela',NULL,'Entrega de paquetes cerca de la entrada principal','Sin placas','Diario'),
(5365,'Entrega rápida a transeúntes',6,'Hombre con gorra negra entregando paquetes','Sin placas','Varias veces por semana'),
(5366,'Puntos de venta recurrentes',7,'Persona vigilando en la esquina',NULL,'Varias veces por semana'),
(5367,'Venta de drogas en vía pública',NULL,'Persona vigilando en la esquina',NULL,'Fines de semana'),
(5368,'Entrega rápida a transeúntes',8,'Venta a transeúntes con señas discretas','Moto','Varias veces por semana'),
(5369,'Venta cerca de escuela',NULL,'Persona vigilando en la esquina','Taxi','Ocasional'),
(5370,'Venta de drogas en vía pública',NULL,'Presunto punto fijo con flujo continuo de compradores','Camioneta','Diario'),
(5371,'Venta de drogas en vía pública',6,'Dos personas realizando entregas rápidas','Taxi','Ocasional'),
(5372,'Venta cerca de escuela',7,'Venta a transeúntes con señas discretas','Motocicleta','Diario'),
(5373,'Venta cerca de escuela',NULL,'Venta a transeúntes con señas discretas','Motocicleta','Cada noche'),
(5374,'Entrega rápida a transeúntes',5,'Hombre con gorra negra entregando paquetes','Camioneta','Fines de semana'),
(5375,'Distribución desde vehículo',7,'Hombre con gorra negra entregando paquetes',NULL,'Cada noche'),
(5376,'Venta de drogas en vía pública',5,'Entrega de paquetes cerca de la entrada principal','Automóvil','Diario'),
(5377,'Venta de drogas en vía pública',2,'Intercambio rápido de paquetes en la banqueta','Motocicleta','Diario'),
(5378,'Distribución desde vehículo',NULL,'Punto de reunión con entregas constantes','Taxi','Cada noche'),
(5379,'Puntos de venta recurrentes',3,'Persona recibiendo efectivo y entregando bolsitas','Moto','Varias veces por semana'),
(5380,'Venta cerca de escuela',NULL,'Entrega de paquetes cerca de la entrada principal','Sin placas','Ocasional'),
(5381,'Entrega rápida a transeúntes',NULL,'Venta a transeúntes con señas discretas','Taxi','Cada noche'),
(5382,'Distribución desde vehículo',NULL,'Grupo de 3 personas intercambiando bolsitas','Taxi','Ocasional'),
(5383,'Venta de drogas en vía pública',6,'Persona vigilando en la esquina','Moto','Varias veces por semana'),
(5384,'Venta de drogas en vía pública',5,'Persona vigilando en la esquina',NULL,'Varias veces por semana'),
(5385,'Distribución desde vehículo',3,'Entrega de paquetes cerca de la entrada principal','Moto','Ocasional'),
(5386,'Puntos de venta recurrentes',2,'Entrega de paquetes cerca de la entrada principal',NULL,'Ocasional'),
(5387,'Venta cerca de escuela',5,'Punto de reunión con entregas constantes','Sin placas','Varias veces por semana'),
(5388,'Puntos de venta recurrentes',NULL,'Entrega de paquetes cerca de la entrada principal','Taxi','Cada noche'),
(5389,'Venta de drogas en vía pública',5,'Punto de reunión con entregas constantes','Sin placas','Cada noche'),
(5390,'Venta de drogas en vía pública',6,'Punto de reunión con entregas constantes','Sin placas','Ocasional'),
(5391,'Intercambio sospechoso de paquetes',3,'Grupo de 3 personas intercambiando bolsitas','Camioneta','Fines de semana'),
(5392,'Puntos de venta recurrentes',3,'Intercambio rápido de paquetes en la banqueta',NULL,'Ocasional'),
(5393,'Venta de drogas en vía pública',2,'Grupo de 3 personas intercambiando bolsitas','Taxi','Ocasional'),
(5394,'Venta cerca de escuela',NULL,'Persona vigilando en la esquina','Automóvil','Diario'),
(5395,'Puntos de venta recurrentes',NULL,'Persona vigilando en la esquina','Taxi','Varias veces por semana'),
(5396,'Intercambio sospechoso de paquetes',5,'Hombre con gorra negra entregando paquetes','Taxi','Cada noche'),
(5397,'Entrega rápida a transeúntes',5,'Presunto punto fijo con flujo continuo de compradores','Sin placas','Fines de semana'),
(5398,'Puntos de venta recurrentes',2,'Grupo de 3 personas intercambiando bolsitas','Taxi','Cada noche'),
(5399,'Puntos de venta recurrentes',NULL,'Persona vigilando en la esquina','Automóvil','Ocasional'),
(5400,'Entrega rápida a transeúntes',8,'Persona vigilando en la esquina','Taxi','Diario'),
(5401,'Venta de drogas en vía pública',NULL,'Persona vigilando en la esquina','Bicicleta','Ocasional'),
(5402,'Intercambio sospechoso de paquetes',3,'Venta a transeúntes con señas discretas','Moto','Varias veces por semana'),
(5403,'Entrega rápida a transeúntes',4,'Persona vigilando en la esquina','Camioneta','Fines de semana'),
(5404,'Entrega rápida a transeúntes',8,'Hombre con gorra negra entregando paquetes','Camioneta','Diario'),
(5405,'Venta cerca de escuela',7,'Persona recibiendo efectivo y entregando bolsitas','Bicicleta','Varias veces por semana'),
(5406,'Distribución desde vehículo',8,'Intercambio rápido de paquetes en la banqueta','Motocicleta','Fines de semana'),
(5407,'Venta de drogas en vía pública',7,'Dos personas realizando entregas rápidas','Automóvil','Cada noche'),
(5408,'Distribución desde vehículo',8,'Punto de reunión con entregas constantes','Automóvil','Fines de semana'),
(5409,'Puntos de venta recurrentes',2,'Intercambio rápido de paquetes en la banqueta','Motocicleta','Varias veces por semana'),
(5410,'Puntos de venta recurrentes',NULL,'Dos personas realizando entregas rápidas','Automóvil','Ocasional'),
(5411,'Venta cerca de escuela',6,'Intercambio rápido de paquetes en la banqueta','Camioneta','Varias veces por semana'),
(5412,'Intercambio sospechoso de paquetes',2,'Punto de reunión con entregas constantes','Taxi','Varias veces por semana'),
(5413,'Venta cerca de escuela',7,'Dos personas realizando entregas rápidas','Sin placas','Cada noche'),
(5414,'Entrega rápida a transeúntes',6,'Persona recibiendo efectivo y entregando bolsitas',NULL,'Cada noche'),
(5415,'Entrega rápida a transeúntes',6,'Grupo de 3 personas intercambiando bolsitas','Moto','Varias veces por semana'),
(5416,'Venta de drogas en vía pública',8,'Dos personas realizando entregas rápidas',NULL,'Varias veces por semana'),
(5417,'Distribución desde vehículo',4,'Entrega de paquetes cerca de la entrada principal','Taxi','Fines de semana'),
(5418,'Entrega rápida a transeúntes',2,'Hombre con gorra negra entregando paquetes','Moto','Ocasional'),
(5419,'Entrega rápida a transeúntes',5,'Persona vigilando en la esquina','Bicicleta','Varias veces por semana'),
(5420,'Intercambio sospechoso de paquetes',4,'Presunto punto fijo con flujo continuo de compradores','Camioneta','Ocasional'),
(5421,'Puntos de venta recurrentes',2,'Venta a transeúntes con señas discretas','Motocicleta','Diario'),
(5422,'Entrega rápida a transeúntes',4,'Dos personas realizando entregas rápidas','Camioneta','Fines de semana'),
(5423,'Distribución desde vehículo',6,'Presunto punto fijo con flujo continuo de compradores','Automóvil','Cada noche'),
(5424,'Distribución desde vehículo',2,'Grupo de 3 personas intercambiando bolsitas','Moto','Ocasional'),
(5425,'Intercambio sospechoso de paquetes',3,'Persona vigilando en la esquina','Taxi','Cada noche'),
(5426,'Distribución desde vehículo',5,'Persona recibiendo efectivo y entregando bolsitas','Automóvil','Cada noche'),
(5427,'Distribución desde vehículo',6,'Punto de reunión con entregas constantes','Bicicleta','Cada noche'),
(5428,'Intercambio sospechoso de paquetes',NULL,'Intercambio rápido de paquetes en la banqueta',NULL,'Varias veces por semana'),
(5429,'Puntos de venta recurrentes',8,'Hombre con gorra negra entregando paquetes','Motocicleta','Diario'),
(5430,'Entrega rápida a transeúntes',8,'Venta a transeúntes con señas discretas','Moto','Ocasional'),
(5431,'Entrega rápida a transeúntes',7,'Persona recibiendo efectivo y entregando bolsitas','Taxi','Ocasional'),
(5432,'Entrega rápida a transeúntes',4,'Venta a transeúntes con señas discretas','Sin placas','Diario'),
(5433,'Distribución desde vehículo',6,'Intercambio rápido de paquetes en la banqueta','Bicicleta','Fines de semana'),
(5434,'Venta cerca de escuela',2,'Presunto punto fijo con flujo continuo de compradores','Automóvil','Fines de semana'),
(5435,'Distribución desde vehículo',NULL,'Persona vigilando en la esquina',NULL,'Fines de semana'),
(5436,'Venta cerca de escuela',5,'Punto de reunión con entregas constantes','Automóvil','Varias veces por semana'),
(5437,'Distribución desde vehículo',7,'Persona vigilando en la esquina',NULL,'Varias veces por semana'),
(5438,'Intercambio sospechoso de paquetes',3,'Intercambio rápido de paquetes en la banqueta','Moto','Diario'),
(5439,'Distribución desde vehículo',4,'Presunto punto fijo con flujo continuo de compradores',NULL,'Varias veces por semana'),
(5440,'Entrega rápida a transeúntes',6,'Presunto punto fijo con flujo continuo de compradores','Automóvil','Diario'),
(5441,'Distribución desde vehículo',3,'Punto de reunión con entregas constantes','Bicicleta','Ocasional'),
(5442,'Venta cerca de escuela',8,'Dos personas realizando entregas rápidas',NULL,'Varias veces por semana'),
(5443,'Puntos de venta recurrentes',7,'Grupo de 3 personas intercambiando bolsitas',NULL,'Diario'),
(5444,'Entrega rápida a transeúntes',7,'Entrega de paquetes cerca de la entrada principal',NULL,'Fines de semana'),
(5445,'Intercambio sospechoso de paquetes',5,'Entrega de paquetes cerca de la entrada principal','Automóvil','Cada noche'),
(5446,'Venta de drogas en vía pública',3,'Dos personas realizando entregas rápidas','Sin placas','Varias veces por semana'),
(5447,'Intercambio sospechoso de paquetes',4,'Dos personas realizando entregas rápidas',NULL,'Diario'),
(5448,'Puntos de venta recurrentes',7,'Persona recibiendo efectivo y entregando bolsitas','Moto','Varias veces por semana'),
(5449,'Intercambio sospechoso de paquetes',7,'Intercambio rápido de paquetes en la banqueta',NULL,'Cada noche'),
(5450,'Puntos de venta recurrentes',6,'Hombre con gorra negra entregando paquetes',NULL,'Diario'),
(5451,'Puntos de venta recurrentes',7,'Venta a transeúntes con señas discretas','Sin placas','Diario'),
(5452,'Distribución desde vehículo',7,'Persona vigilando en la esquina',NULL,'Fines de semana'),
(5453,'Distribución desde vehículo',NULL,'Persona vigilando en la esquina','Bicicleta','Diario'),
(5454,'Puntos de venta recurrentes',8,'Grupo de 3 personas intercambiando bolsitas','Automóvil','Varias veces por semana'),
(5455,'Venta de drogas en vía pública',NULL,'Venta a transeúntes con señas discretas','Motocicleta','Fines de semana'),
(5456,'Entrega rápida a transeúntes',2,'Dos personas realizando entregas rápidas','Moto','Ocasional'),
(5457,'Intercambio sospechoso de paquetes',7,'Intercambio rápido de paquetes en la banqueta',NULL,'Diario'),
(5458,'Entrega rápida a transeúntes',4,'Intercambio rápido de paquetes en la banqueta','Moto','Diario'),
(5459,'Venta cerca de escuela',3,'Hombre con gorra negra entregando paquetes','Moto','Varias veces por semana'),
(5460,'Distribución desde vehículo',8,'Punto de reunión con entregas constantes',NULL,'Ocasional'),
(5461,'Distribución desde vehículo',8,'Entrega de paquetes cerca de la entrada principal','Camioneta','Varias veces por semana'),
(5462,'Distribución desde vehículo',3,'Hombre con gorra negra entregando paquetes','Bicicleta','Cada noche'),
(5463,'Venta cerca de escuela',4,'Dos personas realizando entregas rápidas','Bicicleta','Diario'),
(5464,'Intercambio sospechoso de paquetes',5,'Intercambio rápido de paquetes en la banqueta','Camioneta','Fines de semana'),
(5465,'Venta de drogas en vía pública',6,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Ocasional'),
(5466,'Entrega rápida a transeúntes',3,'Grupo de 3 personas intercambiando bolsitas','Motocicleta','Diario'),
(5467,'Puntos de venta recurrentes',NULL,'Dos personas realizando entregas rápidas','Taxi','Cada noche'),
(5468,'Venta de drogas en vía pública',7,'Persona recibiendo efectivo y entregando bolsitas','Taxi','Ocasional'),
(5469,'Venta cerca de escuela',4,'Entrega de paquetes cerca de la entrada principal',NULL,'Fines de semana'),
(5470,'Venta de drogas en vía pública',5,'Venta a transeúntes con señas discretas','Taxi','Diario'),
(5471,'Puntos de venta recurrentes',6,'Venta a transeúntes con señas discretas','Taxi','Varias veces por semana'),
(5472,'Distribución desde vehículo',5,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Cada noche'),
(5473,'Entrega rápida a transeúntes',4,'Grupo de 3 personas intercambiando bolsitas',NULL,'Diario'),
(5474,'Entrega rápida a transeúntes',5,'Intercambio rápido de paquetes en la banqueta',NULL,'Cada noche'),
(5475,'Venta de drogas en vía pública',8,'Venta a transeúntes con señas discretas',NULL,'Cada noche'),
(5476,'Venta de drogas en vía pública',7,'Persona vigilando en la esquina','Taxi','Fines de semana'),
(5477,'Distribución desde vehículo',6,'Presunto punto fijo con flujo continuo de compradores','Moto','Varias veces por semana'),
(5478,'Distribución desde vehículo',7,'Presunto punto fijo con flujo continuo de compradores',NULL,'Ocasional'),
(5479,'Distribución desde vehículo',5,'Grupo de 3 personas intercambiando bolsitas','Moto','Varias veces por semana'),
(5480,'Venta de drogas en vía pública',8,'Entrega de paquetes cerca de la entrada principal','Moto','Diario'),
(5481,'Puntos de venta recurrentes',5,'Entrega de paquetes cerca de la entrada principal','Camioneta','Fines de semana'),
(5482,'Puntos de venta recurrentes',8,'Punto de reunión con entregas constantes','Automóvil','Ocasional'),
(5483,'Puntos de venta recurrentes',8,'Presunto punto fijo con flujo continuo de compradores',NULL,'Cada noche'),
(5484,'Distribución desde vehículo',NULL,'Dos personas realizando entregas rápidas','Camioneta','Cada noche'),
(5485,'Entrega rápida a transeúntes',5,'Dos personas realizando entregas rápidas','Moto','Varias veces por semana'),
(5486,'Entrega rápida a transeúntes',3,'Dos personas realizando entregas rápidas','Camioneta','Cada noche'),
(5487,'Venta cerca de escuela',8,'Dos personas realizando entregas rápidas','Bicicleta','Diario'),
(5488,'Puntos de venta recurrentes',NULL,'Persona recibiendo efectivo y entregando bolsitas',NULL,'Cada noche'),
(5489,'Entrega rápida a transeúntes',3,'Entrega de paquetes cerca de la entrada principal',NULL,'Cada noche'),
(5490,'Entrega rápida a transeúntes',5,'Intercambio rápido de paquetes en la banqueta','Automóvil','Ocasional'),
(5491,'Venta cerca de escuela',NULL,'Venta a transeúntes con señas discretas',NULL,'Diario'),
(5492,'Venta de drogas en vía pública',NULL,'Intercambio rápido de paquetes en la banqueta','Automóvil','Diario'),
(5493,'Venta de drogas en vía pública',3,'Entrega de paquetes cerca de la entrada principal','Motocicleta','Fines de semana'),
(5494,'Entrega rápida a transeúntes',2,'Presunto punto fijo con flujo continuo de compradores',NULL,'Fines de semana'),
(5495,'Venta cerca de escuela',5,'Punto de reunión con entregas constantes','Taxi','Diario'),
(5496,'Puntos de venta recurrentes',6,'Grupo de 3 personas intercambiando bolsitas','Motocicleta','Cada noche'),
(5497,'Venta de drogas en vía pública',4,'Entrega de paquetes cerca de la entrada principal','Automóvil','Ocasional'),
(5498,'Intercambio sospechoso de paquetes',NULL,'Grupo de 3 personas intercambiando bolsitas','Sin placas','Fines de semana'),
(5499,'Puntos de venta recurrentes',2,'Intercambio rápido de paquetes en la banqueta',NULL,'Diario'),
(5500,'Distribución desde vehículo',5,'Punto de reunión con entregas constantes','Taxi','Cada noche'),
(5501,'Venta cerca de escuela',NULL,'Presunto punto fijo con flujo continuo de compradores',NULL,'Varias veces por semana'),
(5502,'Venta de drogas en vía pública',2,'Entrega de paquetes cerca de la entrada principal',NULL,'Cada noche'),
(5503,'Distribución desde vehículo',4,'Hombre con gorra negra entregando paquetes','Sin placas','Diario'),
(5504,'Venta de drogas en vía pública',NULL,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Cada noche'),
(5505,'Venta de drogas en vía pública',8,'Hombre con gorra negra entregando paquetes','Sin placas','Varias veces por semana'),
(5506,'Puntos de venta recurrentes',3,'Persona vigilando en la esquina','Automóvil','Fines de semana'),
(5507,'Puntos de venta recurrentes',NULL,'Intercambio rápido de paquetes en la banqueta','Motocicleta','Ocasional'),
(5508,'Puntos de venta recurrentes',5,'Intercambio rápido de paquetes en la banqueta','Camioneta','Cada noche'),
(5509,'Intercambio sospechoso de paquetes',7,'Persona vigilando en la esquina','Automóvil','Varias veces por semana'),
(5510,'Venta cerca de escuela',6,'Intercambio rápido de paquetes en la banqueta',NULL,'Ocasional'),
(5511,'Venta de drogas en vía pública',7,'Dos personas realizando entregas rápidas',NULL,'Diario'),
(5512,'Venta cerca de escuela',8,'Intercambio rápido de paquetes en la banqueta','Sin placas','Cada noche'),
(5513,'Distribución desde vehículo',NULL,'Persona vigilando en la esquina','Moto','Ocasional'),
(5514,'Venta cerca de escuela',5,'Punto de reunión con entregas constantes',NULL,'Ocasional'),
(5515,'Distribución desde vehículo',NULL,'Presunto punto fijo con flujo continuo de compradores','Moto','Diario'),
(5516,'Venta cerca de escuela',6,'Punto de reunión con entregas constantes','Taxi','Ocasional'),
(5517,'Venta cerca de escuela',3,'Grupo de 3 personas intercambiando bolsitas','Moto','Ocasional'),
(5518,'Venta cerca de escuela',6,'Punto de reunión con entregas constantes','Automóvil','Fines de semana'),
(5519,'Puntos de venta recurrentes',4,'Dos personas realizando entregas rápidas',NULL,'Varias veces por semana'),
(5520,'Venta de drogas en vía pública',5,'Venta a transeúntes con señas discretas',NULL,'Ocasional'),
(5521,'Distribución desde vehículo',NULL,'Grupo de 3 personas intercambiando bolsitas',NULL,'Varias veces por semana'),
(5522,'Intercambio sospechoso de paquetes',5,'Venta a transeúntes con señas discretas','Bicicleta','Varias veces por semana'),
(5523,'Venta de drogas en vía pública',4,'Intercambio rápido de paquetes en la banqueta','Sin placas','Diario'),
(5524,'Venta de drogas en vía pública',6,'Hombre con gorra negra entregando paquetes','Motocicleta','Varias veces por semana'),
(5525,'Venta cerca de escuela',8,'Intercambio rápido de paquetes en la banqueta','Camioneta','Varias veces por semana'),
(5526,'Distribución desde vehículo',3,'Presunto punto fijo con flujo continuo de compradores','Sin placas','Cada noche'),
(5527,'Venta de drogas en vía pública',NULL,'Dos personas realizando entregas rápidas','Moto','Fines de semana'),
(5528,'Distribución desde vehículo',NULL,'Persona recibiendo efectivo y entregando bolsitas','Camioneta','Fines de semana'),
(5529,'Venta cerca de escuela',NULL,'Grupo de 3 personas intercambiando bolsitas','Motocicleta','Fines de semana'),
(5530,'Distribución desde vehículo',NULL,'Hombre con gorra negra entregando paquetes',NULL,'Fines de semana'),
(5531,'Entrega rápida a transeúntes',5,'Venta a transeúntes con señas discretas',NULL,'Varias veces por semana'),
(5532,'Intercambio sospechoso de paquetes',3,'Persona recibiendo efectivo y entregando bolsitas','Moto','Ocasional'),
(5533,'Intercambio sospechoso de paquetes',8,'Intercambio rápido de paquetes en la banqueta','Sin placas','Fines de semana'),
(5534,'Venta cerca de escuela',NULL,'Grupo de 3 personas intercambiando bolsitas','Automóvil','Cada noche'),
(5535,'Puntos de venta recurrentes',4,'Presunto punto fijo con flujo continuo de compradores','Moto','Cada noche'),
(5536,'Intercambio sospechoso de paquetes',5,'Venta a transeúntes con señas discretas','Moto','Ocasional'),
(5537,'Intercambio sospechoso de paquetes',3,'Hombre con gorra negra entregando paquetes',NULL,'Fines de semana'),
(5538,'Venta de drogas en vía pública',NULL,'Grupo de 3 personas intercambiando bolsitas','Automóvil','Ocasional'),
(5539,'Puntos de venta recurrentes',2,'Entrega de paquetes cerca de la entrada principal','Camioneta','Fines de semana'),
(5540,'Distribución desde vehículo',6,'Grupo de 3 personas intercambiando bolsitas',NULL,'Fines de semana'),
(5541,'Puntos de venta recurrentes',6,'Hombre con gorra negra entregando paquetes','Taxi','Fines de semana'),
(5542,'Intercambio sospechoso de paquetes',7,'Persona recibiendo efectivo y entregando bolsitas',NULL,'Cada noche'),
(5543,'Intercambio sospechoso de paquetes',5,'Hombre con gorra negra entregando paquetes',NULL,'Ocasional'),
(5544,'Venta cerca de escuela',NULL,'Venta a transeúntes con señas discretas','Automóvil','Fines de semana'),
(5545,'Venta de drogas en vía pública',2,'Intercambio rápido de paquetes en la banqueta',NULL,'Varias veces por semana'),
(5546,'Entrega rápida a transeúntes',4,'Punto de reunión con entregas constantes','Motocicleta','Cada noche'),
(5547,'Entrega rápida a transeúntes',6,'Grupo de 3 personas intercambiando bolsitas','Bicicleta','Varias veces por semana'),
(5548,'Venta de drogas en vía pública',5,'Intercambio rápido de paquetes en la banqueta','Camioneta','Varias veces por semana'),
(5549,'Distribución desde vehículo',5,'Entrega de paquetes cerca de la entrada principal','Taxi','Ocasional'),
(5550,'Venta de drogas en vía pública',7,'Entrega de paquetes cerca de la entrada principal','Camioneta','Diario');