INSERT INTO ReporteViolenciaGenero (ReporteId,TipoViolencia,RelacionPersonaAgresora,NombreAgresor)
VALUES
(5551,'Violencia sexual','Amigo','Ángel Romero'),
(5552,'Violencia económica','Familiar','Alias "El Rayo"'),
(5553,'Violencia física','Desconocido','Carlos Hernández'),
(5554,'Violencia digital','Desconocido','Andrés López'),
(5555,'Violencia sexual','Compañero de trabajo/escuela','Enrique Vargas'),
(5556,'Violencia psicológica','Desconocido','Alias "El Chino"'),
(5557,'Violencia sexual','Amigo','Héctor Cruz'),
(5558,'Violencia digital','Desconocido','Alias "El Chino"'),
(5559,'Violencia sexual','Expareja','Roberto Díaz'),
(5560,'Violencia económica','Familiar','Alias "El Güero"'),
(5561,'Violencia física','Compañero de trabajo/escuela','Alias "El Flaco"'),
(5562,'Violencia psicológica','Familiar','Mario Aguilar'),
(5563,'Violencia psicológica','Desconocido','Arturo Medina'),
(5564,'Violencia económica','Desconocido','Fernando Ortiz'),
(5565,'Violencia digital','Desconocido','Enrique Vargas'),
(5566,'Violencia física','Compañero de trabajo/escuela','Iván Navarro'),
(5567,'Violencia sexual','Familiar','Enrique Vargas'),
(5568,'Violencia digital','Familiar','Fernando Ortiz'),
(5569,'Violencia digital','Amigo','Carlos Hernández'),
(5570,'Violencia digital','Compañero de trabajo/escuela','Ángel Romero'),
(5571,'Violencia sexual','Amigo','Alias "El Rayo"'),
(5572,'Violencia sexual','Expareja','Héctor Cruz'),
(5573,'Violencia digital','Amigo','Iván Navarro'),
(5574,'Violencia económica','Amigo','Sergio Torres'),
(5575,'Violencia digital','Amigo','Alias "El Chino"'),
(5576,'Violencia física','Compañero de trabajo/escuela','Alias "El Rayo"'),
(5577,'Violencia física','Amigo','Pedro García'),
(5578,'Violencia económica','Compañero de trabajo/escuela','Arturo Medina'),
(5579,'Violencia sexual','Expareja','Alias "El Rayo"'),
(5580,'Violencia económica','Amigo','Héctor Cruz'),
(5581,'Violencia física','Expareja','Miguel Sánchez'),
(5582,'Violencia económica','Desconocido','Jorge Castillo'),
(5583,'Violencia sexual','Expareja','Roberto Díaz'),
(5584,'Violencia física','Amigo','Carlos Hernández'),
(5585,'Violencia sexual','Familiar','Enrique Vargas'),
(5586,'Violencia económica','Desconocido','Alejandro Ruiz'),
(5587,'Violencia física','Familiar','Fernando Ortiz'),
(5588,'Violencia psicológica','Amigo','Iván Navarro'),
(5589,'Violencia psicológica','Desconocido','José Ramírez'),
(5590,'Violencia física','Familiar','Juan Pérez'),
(5591,'Violencia física','Familiar','Roberto Díaz'),
(5592,'Violencia psicológica','Familiar','José Ramírez'),
(5593,'Violencia psicológica','Compañero de trabajo/escuela','Héctor Cruz'),
(5594,'Violencia física','Familiar','Pedro García'),
(5595,'Violencia psicológica','Pareja actual','Alias "El Rayo"'),
(5596,'Violencia digital','Compañero de trabajo/escuela','Enrique Vargas'),
(5597,'Violencia física','Pareja actual','Alias "El Flaco"'),
(5598,'Violencia sexual','Desconocido','Enrique Vargas'),
(5599,'Violencia física','Desconocido','Enrique Vargas'),
(5600,'Violencia económica','Pareja actual','José Ramírez'),
(5601,'Violencia sexual','Amigo','Héctor Cruz'),
(5602,'Violencia sexual','Familiar','Luis Martínez'),
(5603,'Violencia psicológica','Familiar','Héctor Cruz'),
(5604,'Violencia física','Amigo','Alias "El Chino"'),
(5605,'Violencia económica','Amigo','Juan Pérez'),
(5606,'Violencia económica','Familiar','David Flores'),
(5607,'Violencia económica','Familiar','David Flores'),
(5608,'Violencia psicológica','Desconocido','Arturo Medina'),
(5609,'Violencia sexual','Compañero de trabajo/escuela','Juan Pérez'),
(5610,'Violencia sexual','Compañero de trabajo/escuela','Alias "El Flaco"'),
(5611,'Violencia económica','Expareja','Mario Aguilar'),
(5612,'Violencia económica','Familiar','Jorge Castillo'),
(5613,'Violencia sexual','Amigo','Iván Navarro'),
(5614,'Violencia psicológica','Pareja actual','Alias "El Flaco"'),
(5615,'Violencia económica','Compañero de trabajo/escuela','Arturo Medina'),
(5616,'Violencia digital','Pareja actual','Andrés López'),
(5617,'Violencia física','Expareja','David Flores'),
(5618,'Violencia económica','Pareja actual','Alias "El Güero"'),
(5619,'Violencia física','Compañero de trabajo/escuela','Ricardo Vega'),
(5620,'Violencia económica','Amigo','Alias "El Chino"'),
(5621,'Violencia sexual','Desconocido','Héctor Cruz'),
(5622,'Violencia sexual','Expareja','Roberto Díaz'),
(5623,'Violencia psicológica','Expareja','Alias "El Rayo"'),
(5624,'Violencia física','Familiar','Ricardo Vega'),
(5625,'Violencia física','Expareja','Juan Pérez'),
(5626,'Violencia económica','Desconocido','Ricardo Vega'),
(5627,'Violencia psicológica','Desconocido','Sergio Torres'),
(5628,'Violencia económica','Desconocido','Pedro García'),
(5629,'Violencia psicológica','Desconocido','Luis Martínez'),
(5630,'Violencia digital','Compañero de trabajo/escuela','Fernando Ortiz'),
(5631,'Violencia física','Desconocido','Mario Aguilar'),
(5632,'Violencia digital','Desconocido','Jorge Castillo'),
(5633,'Violencia económica','Amigo','José Ramírez'),
(5634,'Violencia sexual','Desconocido','Ángel Romero'),
(5635,'Violencia económica','Expareja','José Ramírez'),
(5636,'Violencia sexual','Expareja','Andrés López'),
(5637,'Violencia psicológica','Desconocido','Alias "El Rayo"'),
(5638,'Violencia psicológica','Compañero de trabajo/escuela','Alias "El Güero"'),
(5639,'Violencia física','Amigo','Roberto Díaz'),
(5640,'Violencia digital','Pareja actual','Jorge Castillo'),
(5641,'Violencia sexual','Expareja','Carlos Hernández'),
(5642,'Violencia sexual','Amigo','Ricardo Vega'),
(5643,'Violencia digital','Desconocido','Alias "El Güero"'),
(5644,'Violencia digital','Expareja','Pedro García'),
(5645,'Violencia física','Amigo','Alias "El Rayo"'),
(5646,'Violencia física','Compañero de trabajo/escuela','Arturo Medina'),
(5647,'Violencia económica','Pareja actual','Mario Aguilar'),
(5648,'Violencia digital','Amigo','Enrique Vargas'),
(5649,'Violencia económica','Familiar','Alejandro Ruiz'),
(5650,'Violencia económica','Compañero de trabajo/escuela','Miguel Sánchez'),
(5651,'Violencia física','Pareja actual','Iván Navarro'),
(5652,'Violencia económica','Compañero de trabajo/escuela','Alias "El Rayo"'),
(5653,'Violencia digital','Amigo','Ángel Romero'),
(5654,'Violencia física','Familiar','Andrés López'),
(5655,'Violencia sexual','Expareja','Roberto Díaz'),
(5656,'Violencia sexual','Familiar','Luis Martínez'),
(5657,'Violencia física','Familiar','Alias "El Flaco"'),
(5658,'Violencia física','Familiar','Ricardo Vega'),
(5659,'Violencia sexual','Familiar','José Ramírez'),
(5660,'Violencia psicológica','Compañero de trabajo/escuela','Iván Navarro'),
(5661,'Violencia económica','Compañero de trabajo/escuela','Luis Martínez'),
(5662,'Violencia física','Familiar','Andrés López'),
(5663,'Violencia sexual','Expareja','Enrique Vargas'),
(5664,'Violencia física','Amigo','Mario Aguilar'),
(5665,'Violencia sexual','Familiar','Iván Navarro'),
(5666,'Violencia psicológica','Expareja','Alias "El Güero"'),
(5667,'Violencia digital','Familiar','Juan Pérez'),
(5668,'Violencia digital','Expareja','Sergio Torres'),
(5669,'Violencia digital','Expareja','Alejandro Ruiz'),
(5670,'Violencia económica','Amigo','Alias "El Flaco"'),
(5671,'Violencia digital','Amigo','Roberto Díaz'),
(5672,'Violencia física','Familiar','Arturo Medina'),
(5673,'Violencia sexual','Desconocido','David Flores'),
(5674,'Violencia digital','Compañero de trabajo/escuela','Alias "El Chino"'),
(5675,'Violencia psicológica','Pareja actual','Jorge Castillo'),
(5676,'Violencia física','Desconocido','Roberto Díaz'),
(5677,'Violencia psicológica','Familiar','Ángel Romero'),
(5678,'Violencia económica','Familiar','Alias "El Chino"'),
(5679,'Violencia económica','Familiar','Roberto Díaz'),
(5680,'Violencia psicológica','Desconocido','Ricardo Vega'),
(5681,'Violencia física','Amigo','Alias "El Flaco"'),
(5682,'Violencia psicológica','Expareja','Héctor Cruz'),
(5683,'Violencia digital','Pareja actual','Alias "El Güero"'),
(5684,'Violencia psicológica','Familiar','Miguel Sánchez'),
(5685,'Violencia física','Desconocido','Jorge Castillo'),
(5686,'Violencia digital','Familiar','Arturo Medina'),
(5687,'Violencia digital','Familiar','Enrique Vargas'),
(5688,'Violencia física','Pareja actual','Ricardo Vega'),
(5689,'Violencia digital','Expareja','José Ramírez'),
(5690,'Violencia psicológica','Expareja','Héctor Cruz'),
(5691,'Violencia económica','Familiar','Pedro García'),
(5692,'Violencia digital','Familiar','Jorge Castillo'),
(5693,'Violencia sexual','Amigo','José Ramírez'),
(5694,'Violencia física','Desconocido','Alias "El Güero"'),
(5695,'Violencia económica','Expareja','Roberto Díaz'),
(5696,'Violencia digital','Familiar','Iván Navarro'),
(5697,'Violencia digital','Pareja actual','Luis Martínez'),
(5698,'Violencia psicológica','Compañero de trabajo/escuela','Pedro García'),
(5699,'Violencia sexual','Amigo','Alejandro Ruiz'),
(5700,'Violencia económica','Expareja','Arturo Medina'),
(5701,'Violencia digital','Familiar','Miguel Sánchez'),
(5702,'Violencia económica','Amigo','José Ramírez'),
(5703,'Violencia sexual','Familiar','Alias "El Rayo"'),
(5704,'Violencia digital','Pareja actual','Pedro García'),
(5705,'Violencia sexual','Expareja','Jorge Castillo'),
(5706,'Violencia económica','Familiar','Iván Navarro'),
(5707,'Violencia sexual','Amigo','David Flores'),
(5708,'Violencia sexual','Desconocido','Sergio Torres'),
(5709,'Violencia física','Desconocido','Héctor Cruz'),
(5710,'Violencia psicológica','Amigo','Enrique Vargas'),
(5711,'Violencia física','Compañero de trabajo/escuela','Enrique Vargas'),
(5712,'Violencia digital','Amigo','Juan Pérez'),
(5713,'Violencia psicológica','Pareja actual','Andrés López'),
(5714,'Violencia sexual','Desconocido','Arturo Medina'),
(5715,'Violencia psicológica','Compañero de trabajo/escuela','Andrés López'),
(5716,'Violencia física','Compañero de trabajo/escuela','Alias "El Chino"'),
(5717,'Violencia psicológica','Familiar','Fernando Ortiz'),
(5718,'Violencia económica','Familiar','Pedro García'),
(5719,'Violencia psicológica','Amigo','Fernando Ortiz'),
(5720,'Violencia económica','Compañero de trabajo/escuela','Enrique Vargas'),
(5721,'Violencia digital','Compañero de trabajo/escuela','Alias "El Chino"'),
(5722,'Violencia física','Pareja actual','Alias "El Flaco"'),
(5723,'Violencia económica','Desconocido','Alejandro Ruiz'),
(5724,'Violencia digital','Expareja','Mario Aguilar'),
(5725,'Violencia psicológica','Pareja actual','Juan Pérez'),
(5726,'Violencia física','Compañero de trabajo/escuela','Ricardo Vega'),
(5727,'Violencia económica','Familiar','Ricardo Vega'),
(5728,'Violencia económica','Pareja actual','Alias "El Chino"'),
(5729,'Violencia digital','Pareja actual','Sergio Torres'),
(5730,'Violencia física','Amigo','Ángel Romero'),
(5731,'Violencia sexual','Pareja actual','Carlos Hernández'),
(5732,'Violencia digital','Amigo','Juan Pérez'),
(5733,'Violencia sexual','Expareja','Sergio Torres'),
(5734,'Violencia psicológica','Amigo','Alias "El Chino"'),
(5735,'Violencia digital','Pareja actual','Carlos Hernández'),
(5736,'Violencia psicológica','Familiar','Alias "El Rayo"'),
(5737,'Violencia económica','Desconocido','Andrés López'),
(5738,'Violencia sexual','Familiar','Fernando Ortiz'),
(5739,'Violencia psicológica','Desconocido','Alejandro Ruiz'),
(5740,'Violencia física','Pareja actual','Juan Pérez'),
(5741,'Violencia física','Pareja actual','Andrés López'),
(5742,'Violencia digital','Expareja','Carlos Hernández'),
(5743,'Violencia psicológica','Compañero de trabajo/escuela','Alias "El Chino"'),
(5744,'Violencia económica','Amigo','Jorge Castillo'),
(5745,'Violencia económica','Compañero de trabajo/escuela','Pedro García'),
(5746,'Violencia económica','Amigo','Alias "El Flaco"'),
(5747,'Violencia física','Desconocido','Pedro García'),
(5748,'Violencia física','Familiar','Pedro García'),
(5749,'Violencia económica','Expareja','Alias "El Güero"'),
(5750,'Violencia psicológica','Compañero de trabajo/escuela','David Flores'),
(5751,'Violencia sexual','Familiar','Alias "El Güero"'),
(5752,'Violencia digital','Pareja actual','Ricardo Vega'),
(5753,'Violencia económica','Compañero de trabajo/escuela','Ricardo Vega'),
(5754,'Violencia económica','Expareja','Enrique Vargas'),
(5755,'Violencia digital','Pareja actual','Luis Martínez'),
(5756,'Violencia psicológica','Compañero de trabajo/escuela','Alias "El Rayo"'),
(5757,'Violencia psicológica','Expareja','David Flores'),
(5758,'Violencia psicológica','Pareja actual','Alias "El Flaco"'),
(5759,'Violencia sexual','Amigo','Ángel Romero'),
(5760,'Violencia digital','Compañero de trabajo/escuela','David Flores'),
(5761,'Violencia física','Desconocido','Alias "El Rayo"'),
(5762,'Violencia sexual','Desconocido','Arturo Medina'),
(5763,'Violencia económica','Expareja','Fernando Ortiz'),
(5764,'Violencia física','Expareja','David Flores'),
(5765,'Violencia psicológica','Pareja actual','Mario Aguilar'),
(5766,'Violencia psicológica','Familiar','Luis Martínez'),
(5767,'Violencia digital','Desconocido','Jorge Castillo'),
(5768,'Violencia sexual','Compañero de trabajo/escuela','Héctor Cruz'),
(5769,'Violencia digital','Familiar','Ricardo Vega'),
(5770,'Violencia sexual','Familiar','Carlos Hernández'),
(5771,'Violencia psicológica','Compañero de trabajo/escuela','Mario Aguilar'),
(5772,'Violencia económica','Expareja','Juan Pérez'),
(5773,'Violencia económica','Familiar','Jorge Castillo'),
(5774,'Violencia sexual','Amigo','Mario Aguilar'),
(5775,'Violencia sexual','Compañero de trabajo/escuela','José Ramírez'),
(5776,'Violencia digital','Compañero de trabajo/escuela','José Ramírez'),
(5777,'Violencia económica','Amigo','Héctor Cruz'),
(5778,'Violencia digital','Compañero de trabajo/escuela','Iván Navarro'),
(5779,'Violencia sexual','Expareja','Iván Navarro'),
(5780,'Violencia sexual','Expareja','Alias "El Güero"'),
(5781,'Violencia psicológica','Expareja','Pedro García'),
(5782,'Violencia económica','Amigo','Roberto Díaz'),
(5783,'Violencia económica','Familiar','José Ramírez'),
(5784,'Violencia digital','Compañero de trabajo/escuela','Sergio Torres'),
(5785,'Violencia psicológica','Familiar','Iván Navarro'),
(5786,'Violencia física','Compañero de trabajo/escuela','Arturo Medina'),
(5787,'Violencia digital','Expareja','Sergio Torres'),
(5788,'Violencia sexual','Amigo','Héctor Cruz'),
(5789,'Violencia digital','Familiar','Alias "El Chino"'),
(5790,'Violencia económica','Desconocido','Alias "El Rayo"'),
(5791,'Violencia económica','Desconocido','Carlos Hernández'),
(5792,'Violencia física','Compañero de trabajo/escuela','Sergio Torres'),
(5793,'Violencia digital','Pareja actual','Sergio Torres'),
(5794,'Violencia sexual','Amigo','Carlos Hernández'),
(5795,'Violencia psicológica','Amigo','Juan Pérez'),
(5796,'Violencia física','Familiar','Alias "El Flaco"'),
(5797,'Violencia psicológica','Expareja','Luis Martínez'),
(5798,'Violencia digital','Pareja actual','José Ramírez'),
(5799,'Violencia económica','Amigo','Luis Martínez'),
(5800,'Violencia económica','Familiar','Miguel Sánchez'),
(5801,'Violencia sexual','Compañero de trabajo/escuela','David Flores'),
(5802,'Violencia psicológica','Expareja','Alias "El Chino"'),
(5803,'Violencia física','Desconocido','Arturo Medina'),
(5804,'Violencia digital','Expareja','Alias "El Flaco"'),
(5805,'Violencia psicológica','Pareja actual','Luis Martínez'),
(5806,'Violencia psicológica','Desconocido','Ángel Romero'),
(5807,'Violencia económica','Desconocido','Alejandro Ruiz'),
(5808,'Violencia física','Pareja actual','Alias "El Güero"'),
(5809,'Violencia sexual','Compañero de trabajo/escuela','Héctor Cruz'),
(5810,'Violencia económica','Desconocido','Alias "El Rayo"'),
(5811,'Violencia económica','Amigo','Carlos Hernández'),
(5812,'Violencia digital','Compañero de trabajo/escuela','José Ramírez'),
(5813,'Violencia sexual','Familiar','Jorge Castillo'),
(5814,'Violencia psicológica','Familiar','Mario Aguilar'),
(5815,'Violencia económica','Expareja','Pedro García'),
(5816,'Violencia física','Desconocido','Carlos Hernández'),
(5817,'Violencia sexual','Familiar','Ángel Romero'),
(5818,'Violencia digital','Familiar','Alias "El Güero"'),
(5819,'Violencia digital','Desconocido','Enrique Vargas'),
(5820,'Violencia sexual','Desconocido','Alias "El Flaco"'),
(5821,'Violencia sexual','Amigo','Ricardo Vega'),
(5822,'Violencia económica','Familiar','Miguel Sánchez'),
(5823,'Violencia económica','Amigo','Roberto Díaz'),
(5824,'Violencia económica','Familiar','Ángel Romero'),
(5825,'Violencia económica','Desconocido','José Ramírez'),
(5826,'Violencia digital','Expareja','Sergio Torres'),
(5827,'Violencia psicológica','Pareja actual','Roberto Díaz'),
(5828,'Violencia digital','Desconocido','Pedro García'),
(5829,'Violencia económica','Pareja actual','Sergio Torres'),
(5830,'Violencia sexual','Familiar','Ángel Romero'),
(5831,'Violencia económica','Amigo','Miguel Sánchez'),
(5832,'Violencia digital','Amigo','Luis Martínez'),
(5833,'Violencia económica','Familiar','Enrique Vargas'),
(5834,'Violencia económica','Expareja','Juan Pérez'),
(5835,'Violencia digital','Expareja','Pedro García'),
(5836,'Violencia psicológica','Compañero de trabajo/escuela','Alias "El Güero"'),
(5837,'Violencia económica','Expareja','Alias "El Flaco"'),
(5838,'Violencia psicológica','Desconocido','Arturo Medina'),
(5839,'Violencia digital','Desconocido','Pedro García'),
(5840,'Violencia sexual','Familiar','Héctor Cruz'),
(5841,'Violencia digital','Compañero de trabajo/escuela','Andrés López'),
(5842,'Violencia sexual','Compañero de trabajo/escuela','Enrique Vargas'),
(5843,'Violencia sexual','Amigo','Miguel Sánchez'),
(5844,'Violencia psicológica','Amigo','Héctor Cruz'),
(5845,'Violencia psicológica','Desconocido','Mario Aguilar'),
(5846,'Violencia psicológica','Compañero de trabajo/escuela','Alias "El Chino"'),
(5847,'Violencia digital','Desconocido','Mario Aguilar'),
(5848,'Violencia económica','Expareja','David Flores'),
(5849,'Violencia física','Familiar','Ricardo Vega'),
(5850,'Violencia digital','Amigo','Roberto Díaz'),
(5851,'Violencia física','Pareja actual','Mario Aguilar'),
(5852,'Violencia psicológica','Amigo','Mario Aguilar'),
(5853,'Violencia sexual','Desconocido','Héctor Cruz'),
(5854,'Violencia económica','Amigo','Roberto Díaz'),
(5855,'Violencia sexual','Compañero de trabajo/escuela','Arturo Medina'),
(5856,'Violencia digital','Familiar','Arturo Medina'),
(5857,'Violencia digital','Expareja','Enrique Vargas'),
(5858,'Violencia psicológica','Expareja','Miguel Sánchez'),
(5859,'Violencia digital','Compañero de trabajo/escuela','Ricardo Vega'),
(5860,'Violencia económica','Desconocido','Alias "El Chino"'),
(5861,'Violencia sexual','Familiar','Sergio Torres'),
(5862,'Violencia económica','Amigo','Carlos Hernández'),
(5863,'Violencia psicológica','Desconocido','Iván Navarro'),
(5864,'Violencia económica','Desconocido','Iván Navarro'),
(5865,'Violencia física','Amigo','Pedro García'),
(5866,'Violencia digital','Expareja','Carlos Hernández'),
(5867,'Violencia sexual','Compañero de trabajo/escuela','Ángel Romero'),
(5868,'Violencia digital','Desconocido','Alias "El Güero"'),
(5869,'Violencia psicológica','Pareja actual','Alias "El Rayo"'),
(5870,'Violencia psicológica','Pareja actual','Juan Pérez'),
(5871,'Violencia física','Compañero de trabajo/escuela','José Ramírez'),
(5872,'Violencia sexual','Expareja','Alias "El Chino"'),
(5873,'Violencia psicológica','Desconocido','Sergio Torres'),
(5874,'Violencia psicológica','Compañero de trabajo/escuela','Jorge Castillo'),
(5875,'Violencia económica','Desconocido','Iván Navarro'),
(5876,'Violencia digital','Desconocido','Mario Aguilar'),
(5877,'Violencia sexual','Compañero de trabajo/escuela','Pedro García'),
(5878,'Violencia sexual','Amigo','Carlos Hernández'),
(5879,'Violencia física','Expareja','Roberto Díaz'),
(5880,'Violencia económica','Pareja actual','Roberto Díaz'),
(5881,'Violencia económica','Pareja actual','Arturo Medina'),
(5882,'Violencia sexual','Compañero de trabajo/escuela','Alias "El Güero"'),
(5883,'Violencia física','Expareja','Alias "El Güero"'),
(5884,'Violencia económica','Amigo','Héctor Cruz'),
(5885,'Violencia económica','Expareja','Arturo Medina'),
(5886,'Violencia psicológica','Desconocido','Enrique Vargas'),
(5887,'Violencia sexual','Pareja actual','Iván Navarro'),
(5888,'Violencia psicológica','Desconocido','Alias "El Rayo"'),
(5889,'Violencia psicológica','Amigo','Mario Aguilar'),
(5890,'Violencia sexual','Compañero de trabajo/escuela','Mario Aguilar'),
(5891,'Violencia digital','Pareja actual','Enrique Vargas'),
(5892,'Violencia digital','Amigo','Alias "El Flaco"'),
(5893,'Violencia digital','Expareja','Jorge Castillo'),
(5894,'Violencia sexual','Expareja','Alias "El Chino"'),
(5895,'Violencia digital','Desconocido','Ángel Romero'),
(5896,'Violencia económica','Amigo','Pedro García'),
(5897,'Violencia sexual','Desconocido','Miguel Sánchez'),
(5898,'Violencia económica','Pareja actual','Alias "El Chino"'),
(5899,'Violencia económica','Compañero de trabajo/escuela','Enrique Vargas'),
(5900,'Violencia sexual','Desconocido','Ricardo Vega'),
(5901,'Violencia sexual','Pareja actual','Jorge Castillo'),
(5902,'Violencia económica','Expareja','Alias "El Güero"'),
(5903,'Violencia económica','Familiar','Iván Navarro'),
(5904,'Violencia económica','Expareja','Roberto Díaz'),
(5905,'Violencia digital','Familiar','Ricardo Vega'),
(5906,'Violencia sexual','Pareja actual','Alias "El Rayo"'),
(5907,'Violencia física','Desconocido','David Flores'),
(5908,'Violencia psicológica','Amigo','Jorge Castillo'),
(5909,'Violencia psicológica','Desconocido','Carlos Hernández'),
(5910,'Violencia física','Compañero de trabajo/escuela','Arturo Medina'),
(5911,'Violencia económica','Amigo','José Ramírez'),
(5912,'Violencia sexual','Desconocido','Miguel Sánchez'),
(5913,'Violencia económica','Pareja actual','Alejandro Ruiz'),
(5914,'Violencia digital','Familiar','Alias "El Rayo"'),
(5915,'Violencia digital','Compañero de trabajo/escuela','Enrique Vargas'),
(5916,'Violencia digital','Expareja','Arturo Medina'),
(5917,'Violencia económica','Familiar','Alejandro Ruiz'),
(5918,'Violencia psicológica','Compañero de trabajo/escuela','Héctor Cruz'),
(5919,'Violencia psicológica','Compañero de trabajo/escuela','Alias "El Rayo"'),
(5920,'Violencia sexual','Familiar','Alias "El Flaco"'),
(5921,'Violencia física','Desconocido','Jorge Castillo'),
(5922,'Violencia psicológica','Familiar','Miguel Sánchez'),
(5923,'Violencia física','Familiar','Sergio Torres'),
(5924,'Violencia física','Expareja','Iván Navarro'),
(5925,'Violencia económica','Expareja','Fernando Ortiz'),
(5926,'Violencia física','Compañero de trabajo/escuela','Alias "El Rayo"'),
(5927,'Violencia física','Desconocido','Mario Aguilar'),
(5928,'Violencia sexual','Familiar','Juan Pérez'),
(5929,'Violencia física','Desconocido','Mario Aguilar'),
(5930,'Violencia económica','Pareja actual','Carlos Hernández'),
(5931,'Violencia física','Amigo','Iván Navarro'),
(5932,'Violencia psicológica','Desconocido','Miguel Sánchez'),
(5933,'Violencia psicológica','Desconocido','Sergio Torres'),
(5934,'Violencia física','Expareja','Héctor Cruz'),
(5935,'Violencia económica','Pareja actual','Luis Martínez'),
(5936,'Violencia económica','Familiar','Héctor Cruz'),
(5937,'Violencia física','Pareja actual','Luis Martínez'),
(5938,'Violencia digital','Amigo','Ricardo Vega'),
(5939,'Violencia física','Pareja actual','Alias "El Rayo"'),
(5940,'Violencia física','Familiar','Mario Aguilar'),
(5941,'Violencia psicológica','Familiar','Carlos Hernández'),
(5942,'Violencia digital','Compañero de trabajo/escuela','José Ramírez'),
(5943,'Violencia digital','Amigo','Iván Navarro'),
(5944,'Violencia económica','Pareja actual','Alias "El Rayo"'),
(5945,'Violencia psicológica','Desconocido','Iván Navarro'),
(5946,'Violencia psicológica','Desconocido','Alias "El Güero"'),
(5947,'Violencia económica','Desconocido','Roberto Díaz'),
(5948,'Violencia económica','Expareja','David Flores'),
(5949,'Violencia económica','Familiar','Juan Pérez'),
(5950,'Violencia sexual','Expareja','Sergio Torres'),
(5951,'Violencia psicológica','Compañero de trabajo/escuela','Enrique Vargas'),
(5952,'Violencia psicológica','Compañero de trabajo/escuela','Alias "El Rayo"'),
(5953,'Violencia económica','Pareja actual','Sergio Torres'),
(5954,'Violencia digital','Desconocido','Alias "El Chino"'),
(5955,'Violencia digital','Amigo','José Ramírez'),
(5956,'Violencia económica','Pareja actual','Alias "El Güero"'),
(5957,'Violencia física','Familiar','Alias "El Chino"'),
(5958,'Violencia psicológica','Desconocido','Mario Aguilar'),
(5959,'Violencia sexual','Compañero de trabajo/escuela','Carlos Hernández'),
(5960,'Violencia psicológica','Compañero de trabajo/escuela','Miguel Sánchez'),
(5961,'Violencia económica','Familiar','Alias "El Flaco"'),
(5962,'Violencia física','Familiar','Sergio Torres'),
(5963,'Violencia física','Pareja actual','Arturo Medina'),
(5964,'Violencia sexual','Desconocido','Mario Aguilar'),
(5965,'Violencia psicológica','Compañero de trabajo/escuela','Mario Aguilar'),
(5966,'Violencia física','Pareja actual','Roberto Díaz'),
(5967,'Violencia sexual','Desconocido','Alias "El Rayo"'),
(5968,'Violencia psicológica','Familiar','Andrés López'),
(5969,'Violencia económica','Expareja','Pedro García'),
(5970,'Violencia digital','Pareja actual','Luis Martínez'),
(5971,'Violencia digital','Pareja actual','Alias "El Chino"'),
(5972,'Violencia psicológica','Amigo','Andrés López'),
(5973,'Violencia psicológica','Desconocido','Roberto Díaz'),
(5974,'Violencia digital','Desconocido','David Flores'),
(5975,'Violencia física','Compañero de trabajo/escuela','Luis Martínez'),
(5976,'Violencia económica','Expareja','Alias "El Güero"'),
(5977,'Violencia sexual','Pareja actual','Juan Pérez'),
(5978,'Violencia económica','Pareja actual','Alejandro Ruiz'),
(5979,'Violencia física','Compañero de trabajo/escuela','Ángel Romero'),
(5980,'Violencia sexual','Amigo','Héctor Cruz'),
(5981,'Violencia digital','Pareja actual','Alias "El Güero"'),
(5982,'Violencia psicológica','Amigo','Miguel Sánchez'),
(5983,'Violencia física','Pareja actual','Andrés López'),
(5984,'Violencia física','Compañero de trabajo/escuela','Iván Navarro'),
(5985,'Violencia física','Expareja','Carlos Hernández'),
(5986,'Violencia económica','Desconocido','Roberto Díaz'),
(5987,'Violencia física','Desconocido','Miguel Sánchez'),
(5988,'Violencia sexual','Desconocido','José Ramírez'),
(5989,'Violencia económica','Pareja actual','Iván Navarro'),
(5990,'Violencia sexual','Desconocido','Andrés López'),
(5991,'Violencia económica','Expareja','Alias "El Flaco"'),
(5992,'Violencia psicológica','Amigo','Alejandro Ruiz'),
(5993,'Violencia física','Compañero de trabajo/escuela','Andrés López'),
(5994,'Violencia física','Desconocido','Alias "El Rayo"'),
(5995,'Violencia digital','Amigo','Ricardo Vega'),
(5996,'Violencia digital','Expareja','Mario Aguilar'),
(5997,'Violencia sexual','Amigo','Mario Aguilar'),
(5998,'Violencia física','Compañero de trabajo/escuela','David Flores'),
(5999,'Violencia económica','Pareja actual','Jorge Castillo'),
(6000,'Violencia económica','Compañero de trabajo/escuela','Luis Martínez'),
(6001,'Violencia sexual','Pareja actual','Arturo Medina'),
(6002,'Violencia psicológica','Amigo','Carlos Hernández'),
(6003,'Violencia sexual','Familiar','Ricardo Vega'),
(6004,'Violencia sexual','Familiar','Arturo Medina'),
(6005,'Violencia psicológica','Desconocido','Miguel Sánchez'),
(6006,'Violencia psicológica','Amigo','Sergio Torres'),
(6007,'Violencia psicológica','Compañero de trabajo/escuela','Pedro García'),
(6008,'Violencia económica','Amigo','Juan Pérez'),
(6009,'Violencia digital','Familiar','Fernando Ortiz'),
(6010,'Violencia económica','Compañero de trabajo/escuela','Pedro García'),
(6011,'Violencia sexual','Amigo','Pedro García'),
(6012,'Violencia psicológica','Amigo','Carlos Hernández'),
(6013,'Violencia sexual','Compañero de trabajo/escuela','Alejandro Ruiz'),
(6014,'Violencia económica','Compañero de trabajo/escuela','Alias "El Flaco"'),
(6015,'Violencia psicológica','Expareja','Enrique Vargas'),
(6016,'Violencia psicológica','Compañero de trabajo/escuela','Iván Navarro'),
(6017,'Violencia económica','Compañero de trabajo/escuela','Mario Aguilar'),
(6018,'Violencia económica','Pareja actual','Carlos Hernández'),
(6019,'Violencia económica','Familiar','Jorge Castillo'),
(6020,'Violencia sexual','Amigo','Alias "El Chino"'),
(6021,'Violencia económica','Compañero de trabajo/escuela','Iván Navarro'),
(6022,'Violencia económica','Amigo','Mario Aguilar'),
(6023,'Violencia física','Pareja actual','David Flores'),
(6024,'Violencia sexual','Expareja','Roberto Díaz'),
(6025,'Violencia sexual','Pareja actual','Juan Pérez'),
(6026,'Violencia sexual','Expareja','Jorge Castillo'),
(6027,'Violencia sexual','Amigo','Roberto Díaz'),
(6028,'Violencia física','Expareja','Andrés López'),
(6029,'Violencia sexual','Desconocido','Alias "El Güero"'),
(6030,'Violencia física','Expareja','Iván Navarro'),
(6031,'Violencia sexual','Pareja actual','Roberto Díaz'),
(6032,'Violencia sexual','Familiar','Alias "El Rayo"'),
(6033,'Violencia sexual','Pareja actual','Ricardo Vega'),
(6034,'Violencia psicológica','Familiar','Sergio Torres'),
(6035,'Violencia física','Desconocido','Alias "El Chino"'),
(6036,'Violencia sexual','Compañero de trabajo/escuela','Roberto Díaz'),
(6037,'Violencia psicológica','Amigo','Juan Pérez'),
(6038,'Violencia digital','Desconocido','Miguel Sánchez'),
(6039,'Violencia sexual','Expareja','Jorge Castillo'),
(6040,'Violencia económica','Desconocido','Ricardo Vega'),
(6041,'Violencia psicológica','Familiar','Roberto Díaz'),
(6042,'Violencia física','Familiar','Carlos Hernández'),
(6043,'Violencia sexual','Expareja','Roberto Díaz'),
(6044,'Violencia económica','Expareja','Arturo Medina'),
(6045,'Violencia económica','Amigo','Alejandro Ruiz'),
(6046,'Violencia física','Familiar','Enrique Vargas'),
(6047,'Violencia digital','Compañero de trabajo/escuela','Alias "El Güero"'),
(6048,'Violencia física','Amigo','Pedro García'),
(6049,'Violencia sexual','Amigo','Fernando Ortiz'),
(6050,'Violencia económica','Expareja','Luis Martínez'),
(6051,'Violencia física','Amigo','Arturo Medina'),
(6052,'Violencia psicológica','Compañero de trabajo/escuela','Ángel Romero'),
(6053,'Violencia digital','Expareja','Miguel Sánchez'),
(6054,'Violencia económica','Amigo','Sergio Torres'),
(6055,'Violencia digital','Familiar','Roberto Díaz'),
(6056,'Violencia física','Compañero de trabajo/escuela','Enrique Vargas'),
(6057,'Violencia psicológica','Pareja actual','Iván Navarro'),
(6058,'Violencia psicológica','Familiar','Alias "El Rayo"'),
(6059,'Violencia física','Expareja','Ricardo Vega'),
(6060,'Violencia psicológica','Amigo','Ángel Romero'),
(6061,'Violencia económica','Pareja actual','Pedro García'),
(6062,'Violencia económica','Desconocido','Iván Navarro'),
(6063,'Violencia económica','Compañero de trabajo/escuela','David Flores'),
(6064,'Violencia sexual','Familiar','Andrés López'),
(6065,'Violencia sexual','Expareja','Héctor Cruz'),
(6066,'Violencia sexual','Desconocido','Sergio Torres'),
(6067,'Violencia digital','Expareja','Pedro García'),
(6068,'Violencia económica','Compañero de trabajo/escuela','Alejandro Ruiz'),
(6069,'Violencia digital','Compañero de trabajo/escuela','Fernando Ortiz'),
(6070,'Violencia sexual','Desconocido','Enrique Vargas'),
(6071,'Violencia sexual','Familiar','Juan Pérez'),
(6072,'Violencia sexual','Amigo','Alias "El Flaco"'),
(6073,'Violencia física','Expareja','Iván Navarro'),
(6074,'Violencia digital','Desconocido','Ángel Romero'),
(6075,'Violencia sexual','Pareja actual','Alias "El Güero"'),
(6076,'Violencia psicológica','Pareja actual','Alejandro Ruiz'),
(6077,'Violencia económica','Expareja','Andrés López'),
(6078,'Violencia digital','Compañero de trabajo/escuela','Roberto Díaz'),
(6079,'Violencia sexual','Pareja actual','Mario Aguilar'),
(6080,'Violencia sexual','Desconocido','Héctor Cruz'),
(6081,'Violencia física','Compañero de trabajo/escuela','Arturo Medina'),
(6082,'Violencia económica','Expareja','José Ramírez'),
(6083,'Violencia psicológica','Expareja','Mario Aguilar'),
(6084,'Violencia física','Desconocido','Sergio Torres'),
(6085,'Violencia digital','Familiar','José Ramírez'),
(6086,'Violencia física','Amigo','Pedro García'),
(6087,'Violencia psicológica','Familiar','Roberto Díaz'),
(6088,'Violencia sexual','Amigo','Mario Aguilar'),
(6089,'Violencia física','Pareja actual','Alias "El Chino"'),
(6090,'Violencia física','Amigo','Héctor Cruz'),
(6091,'Violencia psicológica','Familiar','Pedro García'),
(6092,'Violencia sexual','Compañero de trabajo/escuela','David Flores'),
(6093,'Violencia digital','Expareja','Luis Martínez'),
(6094,'Violencia psicológica','Desconocido','Ángel Romero'),
(6095,'Violencia psicológica','Familiar','Alias "El Güero"'),
(6096,'Violencia física','Pareja actual','David Flores'),
(6097,'Violencia sexual','Familiar','Ricardo Vega'),
(6098,'Violencia sexual','Compañero de trabajo/escuela','Miguel Sánchez'),
(6099,'Violencia física','Familiar','Iván Navarro'),
(6100,'Violencia psicológica','Amigo','Pedro García'),
(6101,'Violencia psicológica','Amigo','Pedro García'),
(6102,'Violencia psicológica','Expareja','Ricardo Vega'),
(6103,'Violencia sexual','Amigo','Alejandro Ruiz'),
(6104,'Violencia económica','Compañero de trabajo/escuela','Andrés López'),
(6105,'Violencia sexual','Desconocido','Juan Pérez'),
(6106,'Violencia digital','Desconocido','Ángel Romero'),
(6107,'Violencia económica','Pareja actual','Héctor Cruz'),
(6108,'Violencia económica','Pareja actual','Fernando Ortiz'),
(6109,'Violencia psicológica','Pareja actual','Miguel Sánchez'),
(6110,'Violencia psicológica','Expareja','Héctor Cruz'),
(6111,'Violencia física','Desconocido','Jorge Castillo'),
(6112,'Violencia económica','Familiar','Jorge Castillo'),
(6113,'Violencia física','Amigo','Alias "El Chino"'),
(6114,'Violencia digital','Compañero de trabajo/escuela','David Flores'),
(6115,'Violencia psicológica','Compañero de trabajo/escuela','Juan Pérez'),
(6116,'Violencia económica','Pareja actual','Alejandro Ruiz'),
(6117,'Violencia económica','Compañero de trabajo/escuela','Ricardo Vega'),
(6118,'Violencia física','Amigo','Ricardo Vega'),
(6119,'Violencia sexual','Expareja','David Flores'),
(6120,'Violencia económica','Amigo','Andrés López'),
(6121,'Violencia digital','Pareja actual','Ricardo Vega'),
(6122,'Violencia económica','Desconocido','Ángel Romero'),
(6123,'Violencia física','Expareja','Mario Aguilar'),
(6124,'Violencia física','Compañero de trabajo/escuela','Juan Pérez'),
(6125,'Violencia económica','Pareja actual','Alias "El Chino"'),
(6126,'Violencia sexual','Expareja','Roberto Díaz'),
(6127,'Violencia psicológica','Familiar','Ángel Romero'),
(6128,'Violencia económica','Amigo','Pedro García'),
(6129,'Violencia sexual','Familiar','Luis Martínez'),
(6130,'Violencia psicológica','Familiar','Roberto Díaz'),
(6131,'Violencia psicológica','Amigo','Héctor Cruz'),
(6132,'Violencia digital','Pareja actual','Pedro García'),
(6133,'Violencia económica','Pareja actual','Héctor Cruz'),
(6134,'Violencia psicológica','Pareja actual','Héctor Cruz'),
(6135,'Violencia física','Compañero de trabajo/escuela','Andrés López'),
(6136,'Violencia psicológica','Expareja','Alias "El Chino"'),
(6137,'Violencia psicológica','Amigo','Ángel Romero'),
(6138,'Violencia digital','Amigo','Carlos Hernández'),
(6139,'Violencia sexual','Compañero de trabajo/escuela','Arturo Medina'),
(6140,'Violencia digital','Compañero de trabajo/escuela','Ángel Romero'),
(6141,'Violencia psicológica','Desconocido','Andrés López'),
(6142,'Violencia económica','Pareja actual','Luis Martínez'),
(6143,'Violencia física','Expareja','Luis Martínez'),
(6144,'Violencia física','Desconocido','Arturo Medina'),
(6145,'Violencia económica','Familiar','Carlos Hernández'),
(6146,'Violencia psicológica','Amigo','José Ramírez'),
(6147,'Violencia digital','Compañero de trabajo/escuela','Héctor Cruz'),
(6148,'Violencia psicológica','Familiar','Héctor Cruz'),
(6149,'Violencia digital','Desconocido','Héctor Cruz'),
(6150,'Violencia sexual','Familiar','Andrés López');