INSERT INTO ReporteCorrupcion (ReporteId,TipoFaltaReportada,DependenciaInstitucionInvolucrada,NombreServidorPublico,CargoServidorPublico)
VALUES
(5001,'Uso indebido de recursos','Secretaría de Obras y Servicios','Paola Moreno','Subdirector'),
(5002,'Soborno','Alcaldía Álvaro Obregón','Luis Martínez','Coordinador'),
(5003,'Negativa de servicio','Fiscalía General de Justicia de la CDMX',NULL,'Coordinador'),
(5004,'Uso indebido de recursos','Alcaldía Álvaro Obregón','Pedro Sánchez','Analista'),
(5005,'Soborno','Fiscalía General de Justicia de la CDMX',NULL,'Analista'),
(5006,'Negativa de servicio','Secretaría de Movilidad','Lucía Vargas','Subdirector'),
(5007,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','Paola Moreno','Analista'),
(5008,'Soborno','Sistema de Aguas de la CDMX',NULL,'Analista'),
(5009,'Abuso de autoridad','Alcaldía Álvaro Obregón',NULL,'Director'),
(5010,'Negativa de servicio','Secretaría de Movilidad','Karla Sánchez','Enlace operativo'),
(5011,'Uso indebido de recursos','Instituto de Verificación Administrativa','Paola Moreno','Enlace operativo'),
(5012,'Negativa de servicio','Sistema de Aguas de la CDMX',NULL,NULL),
(5013,'Tráfico de influencias','Sistema de Aguas de la CDMX',NULL,'Inspector'),
(5014,'Uso indebido de recursos','Sistema de Aguas de la CDMX','Lucía Vargas','Analista'),
(5015,'Tráfico de influencias','Secretaría de Administración y Finanzas','Ricardo Vega','Director'),
(5016,'Abuso de autoridad','Secretaría de Movilidad','Paola Moreno','Enlace operativo'),
(5017,'Soborno','Sistema de Aguas de la CDMX','Pedro Sánchez','Subdirector'),
(5018,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','José Ramírez','Coordinador'),
(5019,'Uso indebido de recursos','Sistema de Aguas de la CDMX','Karla Sánchez','Inspector'),
(5020,'Negativa de servicio','Secretaría de Obras y Servicios','Ricardo Vega','Director'),
(5021,'Negativa de servicio','Sistema de Aguas de la CDMX',NULL,'Analista'),
(5022,'Soborno','Secretaría de Administración y Finanzas',NULL,'Coordinador'),
(5023,'Uso indebido de recursos','Secretaría de Movilidad','José Ramírez','Inspector'),
(5024,'Omisión de funciones','Sistema de Aguas de la CDMX',NULL,'Coordinador'),
(5025,'Abuso de autoridad','Alcaldía Azcapotzalco','Karla Sánchez','Enlace operativo'),
(5026,'Negativa de servicio','Instituto de Verificación Administrativa','Lucía Vargas','Coordinador'),
(5027,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Paola Moreno','Director'),
(5028,'Tráfico de influencias','Secretaría de Movilidad',NULL,'Jefe de área'),
(5029,'Abuso de autoridad','Secretaría de Obras y Servicios','Pedro Sánchez','Coordinador'),
(5030,'Omisión de funciones','Instituto de Verificación Administrativa','Lucía Vargas',NULL),
(5031,'Omisión de funciones','Fiscalía General de Justicia de la CDMX',NULL,'Analista'),
(5032,'Uso indebido de recursos','Fiscalía General de Justicia de la CDMX',NULL,'Analista'),
(5033,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Jefe de área'),
(5034,'Soborno','Secretaría de Administración y Finanzas','Lucía Vargas','Enlace operativo'),
(5035,'Omisión de funciones','Secretaría de Movilidad','José Ramírez','Analista'),
(5036,'Soborno','Secretaría de Seguridad Ciudadana','Karla Sánchez',NULL),
(5037,'Soborno','Alcaldía Benito Juárez','José Ramírez','Inspector'),
(5038,'Omisión de funciones','Secretaría de Movilidad','Pedro Sánchez','Jefe de área'),
(5039,'Tráfico de influencias','Secretaría de Movilidad','Karla Sánchez','Analista'),
(5040,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,NULL),
(5041,'Negativa de servicio','Secretaría de Obras y Servicios','José Ramírez','Director'),
(5042,'Soborno','Fiscalía General de Justicia de la CDMX','José Ramírez','Jefe de área'),
(5043,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,'Subdirector'),
(5044,'Uso indebido de recursos','Sistema de Aguas de la CDMX','José Ramírez','Director'),
(5045,'Tráfico de influencias','Alcaldía Coyoacán',NULL,'Inspector'),
(5046,'Soborno','Alcaldía Coyoacán','José Ramírez','Inspector'),
(5047,'Omisión de funciones','Sistema de Aguas de la CDMX','Karla Sánchez',NULL),
(5048,'Tráfico de influencias','Secretaría de Administración y Finanzas','Karla Sánchez','Coordinador'),
(5049,'Omisión de funciones','Secretaría de Administración y Finanzas',NULL,'Subdirector'),
(5050,'Tráfico de influencias','Secretaría de Movilidad','Paola Moreno','Coordinador'),
(5051,'Negativa de servicio','Alcaldía Coyoacán','Lucía Vargas','Coordinador'),
(5052,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Pedro Sánchez','Enlace operativo'),
(5053,'Soborno','Sistema de Aguas de la CDMX','Karla Sánchez','Subdirector'),
(5054,'Omisión de funciones','Alcaldía Coyoacán',NULL,NULL),
(5055,'Abuso de autoridad','Alcaldía Coyoacán',NULL,'Enlace operativo'),
(5056,'Uso indebido de recursos','Alcaldía Coyoacán','Ricardo Vega','Jefe de área'),
(5057,'Omisión de funciones','Sistema de Aguas de la CDMX','Karla Sánchez','Enlace operativo'),
(5058,'Omisión de funciones','Alcaldía Coyoacán','Ricardo Vega','Jefe de área'),
(5059,'Omisión de funciones','Sistema de Aguas de la CDMX',NULL,'Analista'),
(5060,'Abuso de autoridad','Instituto de Verificación Administrativa',NULL,'Director'),
(5061,'Soborno','Alcaldía Coyoacán',NULL,'Subdirector'),
(5062,'Tráfico de influencias','Secretaría de Obras y Servicios','Ricardo Vega','Coordinador'),
(5063,'Negativa de servicio','Instituto de Verificación Administrativa','Pedro Sánchez','Subdirector'),
(5064,'Negativa de servicio','Fiscalía General de Justicia de la CDMX','Paola Moreno','Coordinador'),
(5065,'Tráfico de influencias','Secretaría de Movilidad','Luis Martínez',NULL),
(5066,'Negativa de servicio','Secretaría de Obras y Servicios','Lucía Vargas','Subdirector'),
(5067,'Uso indebido de recursos','Secretaría de Obras y Servicios',NULL,'Inspector'),
(5068,'Uso indebido de recursos','Fiscalía General de Justicia de la CDMX','Pedro Sánchez','Inspector'),
(5069,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Lucía Vargas','Enlace operativo'),
(5070,'Omisión de funciones','Secretaría de Administración y Finanzas',NULL,'Coordinador'),
(5071,'Negativa de servicio','Secretaría de Obras y Servicios','Luis Martínez','Enlace operativo'),
(5072,'Abuso de autoridad','Sistema de Aguas de la CDMX','José Ramírez','Inspector'),
(5073,'Tráfico de influencias','Sistema de Aguas de la CDMX','Pedro Sánchez','Director'),
(5074,'Omisión de funciones','Secretaría de Administración y Finanzas','Pedro Sánchez','Subdirector'),
(5075,'Uso indebido de recursos','Sistema de Aguas de la CDMX',NULL,'Analista'),
(5076,'Tráfico de influencias','Secretaría de Movilidad',NULL,'Director'),
(5077,'Abuso de autoridad','Secretaría de Obras y Servicios','Paola Moreno','Director'),
(5078,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Lucía Vargas','Jefe de área'),
(5079,'Omisión de funciones','Instituto de Verificación Administrativa','Luis Martínez','Jefe de área'),
(5080,'Omisión de funciones','Instituto de Verificación Administrativa',NULL,'Coordinador'),
(5081,'Uso indebido de recursos','Secretaría de Administración y Finanzas','Luis Martínez','Inspector'),
(5082,'Soborno','Secretaría de Seguridad Ciudadana',NULL,'Enlace operativo'),
(5083,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,'Analista'),
(5084,'Abuso de autoridad','Secretaría de Movilidad','Pedro Sánchez','Coordinador'),
(5085,'Abuso de autoridad','Instituto de Verificación Administrativa','Luis Martínez','Subdirector'),
(5086,'Soborno','Instituto de Verificación Administrativa','Lucía Vargas','Subdirector'),
(5087,'Tráfico de influencias','Instituto de Verificación Administrativa',NULL,'Coordinador'),
(5088,'Omisión de funciones','Instituto de Verificación Administrativa','Karla Sánchez',NULL),
(5089,'Tráfico de influencias','Alcaldía Gustavo A. Madero','Pedro Sánchez','Director'),
(5090,'Tráfico de influencias','Secretaría de Movilidad',NULL,'Director'),
(5091,'Uso indebido de recursos','Instituto de Verificación Administrativa',NULL,'Analista'),
(5092,'Tráfico de influencias','Secretaría de Administración y Finanzas',NULL,'Director'),
(5093,'Abuso de autoridad','Secretaría de Administración y Finanzas','Ricardo Vega','Analista'),
(5094,'Omisión de funciones','Secretaría de Movilidad',NULL,'Subdirector'),
(5095,'Omisión de funciones','Secretaría de Seguridad Ciudadana',NULL,'Enlace operativo'),
(5096,'Tráfico de influencias','Alcaldía Gustavo A. Madero',NULL,'Director'),
(5097,'Soborno','Secretaría de Seguridad Ciudadana','Luis Martínez','Subdirector'),
(5098,'Soborno','Instituto de Verificación Administrativa','Pedro Sánchez','Analista'),
(5099,'Abuso de autoridad','Secretaría de Movilidad',NULL,'Director'),
(5100,'Abuso de autoridad','Alcaldía Gustavo A. Madero','Pedro Sánchez','Jefe de área'),
(5101,'Omisión de funciones','Secretaría de Obras y Servicios','Lucía Vargas',NULL),
(5102,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Jefe de área'),
(5103,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Luis Martínez','Director'),
(5104,'Abuso de autoridad','Alcaldía Gustavo A. Madero','Paola Moreno','Inspector'),
(5105,'Negativa de servicio','Secretaría de Administración y Finanzas','Lucía Vargas',NULL),
(5106,'Uso indebido de recursos','Fiscalía General de Justicia de la CDMX','Pedro Sánchez','Analista'),
(5107,'Omisión de funciones','Sistema de Aguas de la CDMX','Pedro Sánchez','Inspector'),
(5108,'Uso indebido de recursos','Alcaldía Gustavo A. Madero','Ricardo Vega','Enlace operativo'),
(5109,'Tráfico de influencias','Secretaría de Administración y Finanzas','Pedro Sánchez','Inspector'),
(5110,'Uso indebido de recursos','Fiscalía General de Justicia de la CDMX',NULL,'Jefe de área'),
(5111,'Tráfico de influencias','Alcaldía Gustavo A. Madero','Ricardo Vega','Coordinador'),
(5112,'Omisión de funciones','Fiscalía General de Justicia de la CDMX','Lucía Vargas','Jefe de área'),
(5113,'Tráfico de influencias','Fiscalía General de Justicia de la CDMX','Karla Sánchez','Director'),
(5114,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana','Ricardo Vega','Coordinador'),
(5115,'Negativa de servicio','Instituto de Verificación Administrativa','José Ramírez','Jefe de área'),
(5116,'Abuso de autoridad','Fiscalía General de Justicia de la CDMX',NULL,'Enlace operativo'),
(5117,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Pedro Sánchez','Enlace operativo'),
(5118,'Abuso de autoridad','Alcaldía Iztacalco',NULL,'Jefe de área'),
(5119,'Negativa de servicio','Secretaría de Obras y Servicios','Pedro Sánchez','Director'),
(5120,'Abuso de autoridad','Secretaría de Administración y Finanzas','Ricardo Vega','Coordinador'),
(5121,'Abuso de autoridad','Alcaldía Iztacalco','Paola Moreno','Coordinador'),
(5122,'Soborno','Instituto de Verificación Administrativa','José Ramírez','Jefe de área'),
(5123,'Negativa de servicio','Secretaría de Administración y Finanzas',NULL,'Jefe de área'),
(5124,'Negativa de servicio','Sistema de Aguas de la CDMX','Ricardo Vega','Coordinador'),
(5125,'Soborno','Instituto de Verificación Administrativa',NULL,'Coordinador'),
(5126,'Omisión de funciones','Fiscalía General de Justicia de la CDMX','Pedro Sánchez','Jefe de área'),
(5127,'Negativa de servicio','Secretaría de Seguridad Ciudadana',NULL,'Analista'),
(5128,'Abuso de autoridad','Instituto de Verificación Administrativa','José Ramírez','Jefe de área'),
(5129,'Abuso de autoridad','Secretaría de Obras y Servicios',NULL,'Inspector'),
(5130,'Tráfico de influencias','Instituto de Verificación Administrativa','Paola Moreno','Director'),
(5131,'Tráfico de influencias','Secretaría de Seguridad Ciudadana',NULL,NULL),
(5132,'Omisión de funciones','Instituto de Verificación Administrativa','Pedro Sánchez','Inspector'),
(5133,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,'Subdirector'),
(5134,'Soborno','Secretaría de Movilidad',NULL,NULL),
(5135,'Soborno','Secretaría de Obras y Servicios',NULL,'Subdirector'),
(5136,'Uso indebido de recursos','Instituto de Verificación Administrativa','Lucía Vargas','Director'),
(5137,'Soborno','Fiscalía General de Justicia de la CDMX','Karla Sánchez','Coordinador'),
(5138,'Omisión de funciones','Secretaría de Movilidad',NULL,'Director'),
(5139,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Coordinador'),
(5140,'Uso indebido de recursos','Sistema de Aguas de la CDMX','José Ramírez','Jefe de área'),
(5141,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Coordinador'),
(5142,'Omisión de funciones','Secretaría de Movilidad',NULL,'Jefe de área'),
(5143,'Soborno','Secretaría de Administración y Finanzas','Luis Martínez','Director'),
(5144,'Soborno','Sistema de Aguas de la CDMX','Paola Moreno','Inspector'),
(5145,'Soborno','Secretaría de Movilidad','Pedro Sánchez','Director'),
(5146,'Abuso de autoridad','Fiscalía General de Justicia de la CDMX','José Ramírez','Jefe de área'),
(5147,'Tráfico de influencias','Secretaría de Seguridad Ciudadana','Pedro Sánchez','Jefe de área'),
(5148,'Abuso de autoridad','Secretaría de Movilidad','Luis Martínez','Director'),
(5149,'Abuso de autoridad','Secretaría de Seguridad Ciudadana',NULL,'Subdirector'),
(5150,'Uso indebido de recursos','Sistema de Aguas de la CDMX',NULL,'Analista'),
(5151,'Negativa de servicio','Instituto de Verificación Administrativa','Pedro Sánchez','Enlace operativo'),
(5152,'Soborno','Alcaldía Iztapalapa',NULL,'Subdirector'),
(5153,'Abuso de autoridad','Fiscalía General de Justicia de la CDMX','José Ramírez',NULL),
(5154,'Omisión de funciones','Secretaría de Administración y Finanzas','Lucía Vargas','Enlace operativo'),
(5155,'Abuso de autoridad','Secretaría de Obras y Servicios','Karla Sánchez','Director'),
(5156,'Uso indebido de recursos','Secretaría de Movilidad','José Ramírez','Inspector'),
(5157,'Negativa de servicio','Secretaría de Obras y Servicios','José Ramírez',NULL),
(5158,'Negativa de servicio','Secretaría de Seguridad Ciudadana','Ricardo Vega','Director'),
(5159,'Negativa de servicio','Secretaría de Movilidad','Lucía Vargas','Enlace operativo'),
(5160,'Soborno','Secretaría de Movilidad','Luis Martínez','Director'),
(5161,'Soborno','Fiscalía General de Justicia de la CDMX','José Ramírez','Inspector'),
(5162,'Tráfico de influencias','Secretaría de Obras y Servicios','Lucía Vargas',NULL),
(5163,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana','Paola Moreno','Coordinador'),
(5164,'Negativa de servicio','Instituto de Verificación Administrativa','Paola Moreno','Enlace operativo'),
(5165,'Soborno','Secretaría de Obras y Servicios','Paola Moreno','Subdirector'),
(5166,'Abuso de autoridad','Secretaría de Obras y Servicios',NULL,'Subdirector'),
(5167,'Omisión de funciones','Secretaría de Administración y Finanzas','Paola Moreno','Analista'),
(5168,'Omisión de funciones','Alcaldía Iztapalapa',NULL,'Director'),
(5169,'Soborno','Fiscalía General de Justicia de la CDMX','Pedro Sánchez','Enlace operativo'),
(5170,'Negativa de servicio','Secretaría de Seguridad Ciudadana',NULL,'Director'),
(5171,'Abuso de autoridad','Instituto de Verificación Administrativa','Paola Moreno','Coordinador'),
(5172,'Negativa de servicio','Alcaldía Iztapalapa','Lucía Vargas','Enlace operativo'),
(5173,'Abuso de autoridad','Secretaría de Movilidad','José Ramírez','Inspector'),
(5174,'Soborno','Alcaldía Iztapalapa','Lucía Vargas','Inspector'),
(5175,'Omisión de funciones','Fiscalía General de Justicia de la CDMX','Paola Moreno',NULL),
(5176,'Negativa de servicio','Secretaría de Obras y Servicios','Ricardo Vega','Coordinador'),
(5177,'Tráfico de influencias','Secretaría de Administración y Finanzas',NULL,'Director'),
(5178,'Abuso de autoridad','Secretaría de Administración y Finanzas','Luis Martínez','Inspector'),
(5179,'Tráfico de influencias','Instituto de Verificación Administrativa','Lucía Vargas','Analista'),
(5180,'Negativa de servicio','Secretaría de Obras y Servicios',NULL,'Subdirector'),
(5181,'Negativa de servicio','Instituto de Verificación Administrativa','Pedro Sánchez','Director'),
(5182,'Tráfico de influencias','Secretaría de Movilidad','Ricardo Vega','Inspector'),
(5183,'Abuso de autoridad','Secretaría de Administración y Finanzas',NULL,'Coordinador'),
(5184,'Omisión de funciones','Secretaría de Administración y Finanzas','Karla Sánchez','Inspector'),
(5185,'Negativa de servicio','Alcaldía Miguel Hidalgo',NULL,NULL),
(5186,'Abuso de autoridad','Secretaría de Obras y Servicios','Luis Martínez',NULL),
(5187,'Soborno','Sistema de Aguas de la CDMX','Paola Moreno','Jefe de área'),
(5188,'Omisión de funciones','Secretaría de Seguridad Ciudadana','Ricardo Vega','Inspector'),
(5189,'Soborno','Alcaldía Miguel Hidalgo','Pedro Sánchez',NULL),
(5190,'Abuso de autoridad','Instituto de Verificación Administrativa',NULL,'Jefe de área'),
(5191,'Negativa de servicio','Alcaldía Miguel Hidalgo','Pedro Sánchez','Jefe de área'),
(5192,'Negativa de servicio','Secretaría de Administración y Finanzas','José Ramírez',NULL),
(5193,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','Karla Sánchez','Jefe de área'),
(5194,'Tráfico de influencias','Secretaría de Administración y Finanzas','Karla Sánchez','Enlace operativo'),
(5195,'Omisión de funciones','Sistema de Aguas de la CDMX','Luis Martínez','Coordinador'),
(5196,'Soborno','Secretaría de Movilidad','Luis Martínez','Analista'),
(5197,'Negativa de servicio','Secretaría de Administración y Finanzas','Lucía Vargas','Coordinador'),
(5198,'Omisión de funciones','Secretaría de Administración y Finanzas','Pedro Sánchez','Analista'),
(5199,'Soborno','Sistema de Aguas de la CDMX',NULL,'Jefe de área'),
(5200,'Soborno','Alcaldía Tláhuac','Lucía Vargas','Analista'),
(5201,'Negativa de servicio','Alcaldía Tláhuac','Pedro Sánchez',NULL),
(5202,'Omisión de funciones','Fiscalía General de Justicia de la CDMX','Ricardo Vega',NULL),
(5203,'Abuso de autoridad','Alcaldía Tláhuac',NULL,'Jefe de área'),
(5204,'Uso indebido de recursos','Secretaría de Administración y Finanzas','Ricardo Vega','Jefe de área'),
(5205,'Abuso de autoridad','Instituto de Verificación Administrativa','Pedro Sánchez','Enlace operativo'),
(5206,'Omisión de funciones','Secretaría de Seguridad Ciudadana','José Ramírez',NULL),
(5207,'Omisión de funciones','Instituto de Verificación Administrativa','Ricardo Vega',NULL),
(5208,'Soborno','Instituto de Verificación Administrativa',NULL,'Enlace operativo'),
(5209,'Soborno','Secretaría de Administración y Finanzas','Pedro Sánchez','Jefe de área'),
(5210,'Soborno','Sistema de Aguas de la CDMX',NULL,'Jefe de área'),
(5211,'Omisión de funciones','Sistema de Aguas de la CDMX','Luis Martínez','Jefe de área'),
(5212,'Uso indebido de recursos','Secretaría de Obras y Servicios',NULL,NULL),
(5213,'Abuso de autoridad','Secretaría de Seguridad Ciudadana','Pedro Sánchez','Enlace operativo'),
(5214,'Negativa de servicio','Alcaldía Tlalpan','Lucía Vargas','Analista'),
(5215,'Soborno','Sistema de Aguas de la CDMX','Paola Moreno','Enlace operativo'),
(5216,'Tráfico de influencias','Secretaría de Obras y Servicios','José Ramírez',NULL),
(5217,'Negativa de servicio','Secretaría de Obras y Servicios','Ricardo Vega','Enlace operativo'),
(5218,'Soborno','Sistema de Aguas de la CDMX','Luis Martínez','Analista'),
(5219,'Negativa de servicio','Secretaría de Movilidad',NULL,'Coordinador'),
(5220,'Soborno','Sistema de Aguas de la CDMX','Karla Sánchez','Director'),
(5221,'Soborno','Secretaría de Seguridad Ciudadana',NULL,'Inspector'),
(5222,'Soborno','Alcaldía Tlalpan','Ricardo Vega','Enlace operativo'),
(5223,'Uso indebido de recursos','Secretaría de Obras y Servicios','Ricardo Vega','Coordinador'),
(5224,'Soborno','Secretaría de Seguridad Ciudadana','Luis Martínez','Director'),
(5225,'Uso indebido de recursos','Secretaría de Movilidad',NULL,NULL),
(5226,'Soborno','Instituto de Verificación Administrativa','Lucía Vargas','Analista'),
(5227,'Abuso de autoridad','Alcaldía Venustiano Carranza','José Ramírez','Inspector'),
(5228,'Soborno','Secretaría de Administración y Finanzas','Pedro Sánchez','Coordinador'),
(5229,'Soborno','Secretaría de Movilidad','Pedro Sánchez','Subdirector'),
(5230,'Omisión de funciones','Secretaría de Administración y Finanzas','José Ramírez',NULL),
(5231,'Abuso de autoridad','Sistema de Aguas de la CDMX','Ricardo Vega','Analista'),
(5232,'Abuso de autoridad','Fiscalía General de Justicia de la CDMX','Karla Sánchez','Subdirector'),
(5233,'Uso indebido de recursos','Secretaría de Seguridad Ciudadana','Luis Martínez','Inspector'),
(5234,'Negativa de servicio','Sistema de Aguas de la CDMX','Luis Martínez','Enlace operativo'),
(5235,'Tráfico de influencias','Secretaría de Obras y Servicios','José Ramírez','Analista'),
(5236,'Omisión de funciones','Secretaría de Movilidad',NULL,'Coordinador'),
(5237,'Soborno','Sistema de Aguas de la CDMX',NULL,'Subdirector'),
(5238,'Omisión de funciones','Secretaría de Administración y Finanzas','Ricardo Vega','Inspector'),
(5239,'Tráfico de influencias','Secretaría de Administración y Finanzas','José Ramírez','Director'),
(5240,'Omisión de funciones','Sistema de Aguas de la CDMX','Karla Sánchez','Coordinador'),
(5241,'Soborno','Secretaría de Obras y Servicios','José Ramírez','Director'),
(5242,'Abuso de autoridad','Alcaldía Xochimilco',NULL,'Jefe de área'),
(5243,'Negativa de servicio','Secretaría de Obras y Servicios',NULL,NULL),
(5244,'Abuso de autoridad','Secretaría de Movilidad',NULL,'Enlace operativo'),
(5245,'Omisión de funciones','Alcaldía Xochimilco','Paola Moreno','Analista'),
(5246,'Abuso de autoridad','Instituto de Verificación Administrativa','Karla Sánchez','Subdirector'),
(5247,'Abuso de autoridad','Fiscalía General de Justicia de la CDMX','Karla Sánchez','Director'),
(5248,'Uso indebido de recursos','Instituto de Verificación Administrativa','Luis Martínez','Enlace operativo'),
(5249,'Uso indebido de recursos','Secretaría de Movilidad',NULL,'Inspector'),
(5250,'Omisión de funciones','Secretaría de Movilidad',NULL,'Subdirector');